import {it,expect,vi} from 'vitest';
import {deviceLogin} from '../cli/deviceLogin';
const secret='S'.repeat(43),token=`nd_${'T'.repeat(43)}`;
const start={device_code:secret,user_code:'BCDF-GHJK',verification_uri:'https://druggie.org/agents/device',verification_uri_complete:'https://druggie.org/agents/device?code=BCDF-GHJK',expires_in:600,interval:5};
function harness(responses:any[]){let clock=0;const set=vi.fn(),announce=vi.fn(),verify=vi.fn().mockResolvedValue({id:'owner',scope:'read'}),delays:number[]=[],bodies:any[]=[];const fetch=vi.fn(async(_url:any,init:any)=>{bodies.push(JSON.parse(init.body));const data=responses.shift();return new Response(JSON.stringify(data),{status:data?.error?400:200,headers:{'Content-Type':'application/json'}});}) as unknown as typeof globalThis.fetch;return {set,announce,verify,delays,bodies,deps:{store:{set},announce,verify,fetch,now:()=>clock,sleep:async(ms:number)=>{delays.push(ms);clock+=ms;}}};}
const options={url:'https://druggie.org',profile:'cloud',name:'Cloud CLI',scope:'read' as const};
it('polls pending/slow responses, verifies identity, then saves a pinned profile without announcing secrets',async()=>{
 const h=harness([start,{error:'authorization_pending'},{error:'slow_down',interval:10},{access_token:token,token_type:'Bearer',scope:'read'}]);
 await expect(deviceLogin(options,h.deps)).resolves.toMatchObject({id:'owner'});expect(h.delays).toEqual([5000,5000,10000]);expect(h.set).toHaveBeenCalledWith('cloud',{url:'https://druggie.org',token});expect(h.verify.mock.invocationCallOrder[0]).toBeLessThan(h.set.mock.invocationCallOrder[0]);expect(JSON.stringify(h.announce.mock.calls)).not.toContain(secret);expect(JSON.stringify(h.announce.mock.calls)).not.toContain(token);expect(h.bodies[1]).toEqual({device_code:secret});
});
it.each(['access_denied','expired_token'])('does not save or verify credentials after %s',async error=>{const h=harness([start,{error}]);await expect(deviceLogin(options,h.deps)).rejects.toThrow(error==='access_denied'?'denied':'expired');expect(h.set).not.toHaveBeenCalled();expect(h.verify).not.toHaveBeenCalled();});
it('leaves profiles untouched when identity verification fails',async()=>{const h=harness([start,{access_token:token,token_type:'Bearer',scope:'read'}]);h.verify.mockRejectedValue(new Error('Revoked'));await expect(deviceLogin(options,h.deps)).rejects.toThrow('Revoked');expect(h.set).not.toHaveBeenCalled();});
it('expires locally instead of polling forever',async()=>{const h=harness([{...start,expires_in:5}]);await expect(deviceLogin(options,h.deps)).rejects.toThrow('expired');expect(h.bodies).toHaveLength(1);expect(h.set).not.toHaveBeenCalled();});
it('rejects an approval link to another host',async()=>{const h=harness([{...start,verification_uri_complete:'https://elsewhere.example/agents/device?code=BCDF-GHJK'}]);await expect(deviceLogin(options,h.deps)).rejects.toThrow('selected site');expect(h.announce).not.toHaveBeenCalled();});
it('backs off after a polling timeout and completes on retry',async()=>{const h=harness([start,{access_token:token,token_type:'Bearer',scope:'read'}]),send=h.deps.fetch;let calls=0;h.deps.fetch=async(...args)=>{if(++calls===2)throw new DOMException('Timed out','TimeoutError');return send(...args);};await expect(deviceLogin(options,h.deps)).resolves.toMatchObject({id:'owner'});expect(h.delays).toEqual([5000,10000]);expect(h.set).toHaveBeenCalledOnce();});
