import {beforeAll,beforeEach,afterAll,it,expect} from 'vitest';
import {connectDatabase,db,mongo,rows} from '../server/db';
import {users,type User,type Actor,hash} from '../server/auth';
import {config} from '../server/config';
import {startDeviceLogin,readDeviceLogin,decideDeviceLogin,pollDeviceLogin} from '../server/deviceLogin';
import {createApp} from '../server/app';
const owner:Actor={userId:'owner',source:'browser',scope:'write'};
async function clean(){if(db().databaseName!=='newdrugs_test')throw Error('Isolated database required');for(const name of ['users','tokens','deviceLogins','requestRates','sessions'])await rows(name).deleteMany({});}
beforeAll(async()=>{if(new URL(config.MONGODB_URI).pathname!=='/newdrugs_test')throw Error('Isolated database required');await connectDatabase();});
beforeEach(async()=>{await clean();const user:User={_id:'owner',handle:'owner',name:'Owner',city:'',cityKey:'',bio:'',interests:[],discoverable:false,balanceNanos:0,reservedNanos:0,createdAt:new Date().toISOString()};await users().insertMany([user,{...user,_id:'other',handle:'other'}]);});
afterAll(async()=>{await clean();await mongo.close();});
async function ready(){await rows('deviceLogins').updateMany({},{$set:{nextPollAt:new Date(0)}});}
const access={name:'Cloud check',scope:'read' as const,expiresInDays:7};
it('approves into ordinary Connected agents tokens and permits idempotent delivery retries',async()=>{
 const start=await startDeviceLogin({name:'Remote CLI',scope:'write'});expect(await readDeviceLogin(owner,start.user_code)).toMatchObject({status:'pending'});await decideDeviceLogin(owner,start.user_code,'approve',access);await ready();const first=await pollDeviceLogin(start.device_code);expect(first).toMatchObject({token_type:'Bearer',scope:'read'});if(!('access_token' in first))throw Error('Token expected');const record=await rows('tokens').findOne({hash:hash(first.access_token)});expect(record).toMatchObject({userId:'owner',name:'Cloud check',scope:'read',revokedAt:null});expect(record?.expiresAt).toBeInstanceOf(Date);expect(JSON.stringify(await rows('deviceLogins').findOne({}))).not.toContain(start.device_code);expect(JSON.stringify(await rows('deviceLogins').findOne({}))).not.toContain(first.access_token);await ready();expect(await pollDeviceLogin(start.device_code)).toMatchObject({access_token:first.access_token,token_type:'Bearer',scope:'read'});expect(await rows('tokens').countDocuments({})).toBe(1);
});
it('denies without issuing credentials',async()=>{const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});await decideDeviceLogin(owner,start.user_code,'deny');expect(await pollDeviceLogin(start.device_code)).toEqual({error:'access_denied'});expect(await rows('tokens').countDocuments({})).toBe(0);});
it('checks logical expiry even before TTL deletion',async()=>{const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});await rows('deviceLogins').updateMany({},{$set:{expiresAt:new Date(0)}});expect(await pollDeviceLogin(start.device_code)).toEqual({error:'expired_token'});await expect(decideDeviceLogin(owner,start.user_code,'approve',access)).rejects.toThrow();expect(await rows('tokens').countDocuments({})).toBe(0);});
it('slows down early polling and returns pending after the interval',async()=>{const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});expect(await pollDeviceLogin(start.device_code)).toEqual({error:'slow_down',interval:10});await ready();expect(await pollDeviceLogin(start.device_code)).toEqual({error:'authorization_pending',interval:10});});
it('honors revocation before delivering approved credentials',async()=>{const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});await decideDeviceLogin(owner,start.user_code,'approve',access);await rows('tokens').updateMany({},{$set:{revokedAt:new Date().toISOString()}});await ready();expect(await pollDeviceLogin(start.device_code)).toEqual({error:'access_denied'});});
it('honors the ordinary token expiration before delivery',async()=>{const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});await decideDeviceLogin(owner,start.user_code,'approve',access);await rows('tokens').updateMany({},{$set:{expiresAt:new Date(0)}});await ready();expect(await pollDeviceLogin(start.device_code)).toEqual({error:'access_denied'});});
it('shares the Connected agents cap without deciding or issuing a request that exceeds it',async()=>{await rows('tokens').insertMany(Array.from({length:20},(_,index)=>({_id:`fixture-${index}`,hash:`fixture-${index}`,userId:'owner',revokedAt:null})));const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});await expect(decideDeviceLogin(owner,start.user_code,'approve',access)).rejects.toMatchObject({code:'token_limit'});expect(await readDeviceLogin(owner,start.user_code)).toMatchObject({status:'pending'});expect(await rows('tokens').countDocuments({})).toBe(20);await rows('tokens').updateOne({_id:'fixture-0'},{$set:{revokedAt:new Date().toISOString()}});expect(await decideDeviceLogin(owner,start.user_code,'approve',access)).toMatchObject({status:'approved'});});
it('honors owner suspension before delivering approved credentials',async()=>{const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});await decideDeviceLogin(owner,start.user_code,'approve',access);await users().updateOne({_id:'owner'},{$set:{suspendedAt:new Date().toISOString()}});await ready();expect(await pollDeviceLogin(start.device_code)).toEqual({error:'access_denied'});});
it('rejects external approval and competing browser decisions',async()=>{const start=await startDeviceLogin({name:'Remote CLI',scope:'read'});await expect(decideDeviceLogin({...owner,source:'external'},start.user_code,'approve',access)).rejects.toMatchObject({status:403});const outcomes=await Promise.allSettled([decideDeviceLogin(owner,start.user_code,'approve',access),decideDeviceLogin({...owner,userId:'other'},start.user_code,'approve',access)]);expect(outcomes.filter(item=>item.status==='fulfilled')).toHaveLength(1);expect(await rows('tokens').countDocuments({})).toBe(1);});
it('requires the normal browser cookie and Origin to approve through HTTP',async()=>{
 const server=createApp().listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('Port expected');const base=`http://127.0.0.1:${address.port}`,headers={'Content-Type':'application/json','X-NewDrugs-Dev-Key':'isolated-test-setup'};
 try{expect((await fetch(`${base}/api/agent-login/device`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status).toBe(404);expect((await fetch(`${base}/api/agent-login/device`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer invalid'},body:'{}'})).status).toBe(401);const response=await fetch(`${base}/api/agent-login/device`,{method:'POST',headers,body:JSON.stringify({name:'Cloud CLI',scope:'read'})});expect(response.status).toBe(200);const start=await response.json();const secret='browser-fixture';await rows('sessions').insertOne({_id:hash(secret),userId:'owner',expiresAt:new Date(Date.now()+60000)});const body=JSON.stringify({userCode:start.user_code,access});expect((await fetch(`${base}/api/agent-login/approve`,{method:'POST',headers:{...headers,Cookie:`${config.SESSION_COOKIE}=${secret}`},body})).status).toBe(403);expect((await fetch(`${base}/api/agent-login/approve`,{method:'POST',headers:{...headers,Cookie:`${config.SESSION_COOKIE}=${secret}`,Origin:config.APP_ORIGIN},body})).status).toBe(200);}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
});
