import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {beforeAll,beforeEach,afterAll,it,expect} from 'vitest';import {connectDatabase,db,mongo,rows} from '../server/db';
import {importLogcalPerson} from '../scripts/migrations/logcal-import-person';
let directory:string;const now=new Date().toISOString(),target=randomUUID(),cyrus=randomUUID(),laura=randomUUID();
async function clean(){if(db().databaseName!=='newdrugs_test')throw Error('Isolated DB required');for(const collection of await db().collections())await collection.deleteMany({});}
beforeAll(async()=>{await connectDatabase();if(db().databaseName!=='newdrugs_test')throw Error('Isolated DB required');directory=await fs.mkdtemp(path.join(os.tmpdir(),'nd-person-migration-'));await fs.mkdir(path.join(directory,'files'));});
beforeEach(async()=>{await clean();await rows('users').insertMany([{_id:target,handle:'ancatdubh2',storageBytes:10},{_id:cyrus,handle:'cyrus',storageBytes:123},{_id:laura,handle:'laura',storageBytes:456}]);});
afterAll(async()=>{await clean();await mongo.close();await fs.rm(directory,{recursive:true,force:true});});
const entry=(id=randomUUID())=>({_id:id,title:'Source title',date:'2020-01-02',place:'Source place',links:[],recurrence:'none',coverFileId:null,ownerId:target,members:[target],invited:[],contributions:[{userId:target,note:'Their original words',fileIds:[] as string[]}],historicalPeople:['Cyrus'],revision:1,createdAt:now,updatedAt:now,migration:{source:'logcal.app',sourceId:`source-${id}`,sourceHash:'b'.repeat(64),historicalPeople:[{sourceId:'old-cyrus',name:'Cyrus'}],missingMedia:[],version:1}});
const plan=(entries:ReturnType<typeof entry>[])=>({version:1,source:'logcal.app',sourceHash:'a'.repeat(64),exportedAt:now,accounts:[{sourceId:'old-ancat',handle:'ancatdubh2',userId:target,birthday:{month:3,day:4}}],entries,uploads:[] as any[],missing:[]});
const args=(input:unknown)=>({db:db(),client:mongo,input,preparedDir:path.join(directory,'files'),targetDir:path.join(directory,'target')});
async function previous(source:ReturnType<typeof entry>,changes:Record<string,unknown>={}){await rows('logEntries').insertOne({...source,ownerId:cyrus,members:[cyrus,laura],contributions:[{userId:cyrus,note:'Current Cyrus note',fileIds:[]},{userId:laura,note:'Current Laura note',fileIds:[]}],title:'Edited in New Drugs',place:'Updated place',revision:7,historicalPeople:['ancatdubh2','Former friend'],migration:{...source.migration,historicalPeople:[{sourceId:'old-ancat',name:'ancatdubh2'},{sourceId:'other',name:'Former friend'}]},...changes});}
it('adds just the new person, preserves earlier imports and edits, skips deletions, and retries without overwriting',async()=>{
 const existing=entry(),fresh=entry(),deleted=entry(),input=plan([existing,fresh,deleted]);await previous(existing);await previous(deleted,{deletedAt:now});
 const fileId=randomUUID(),bytes=Buffer.from('verified fixture bytes'),hash=createHash('sha256').update(bytes).digest('hex');existing.contributions[0].fileIds=[fileId];
 input.uploads=[{_id:fileId,userId:target,logEntryId:existing._id,purpose:'log_media',name:'photo.webp',expectedBytes:bytes.length,sourceHash:hash,bytes:bytes.length,mime:'image/webp',sha256:hash,ready:true,retained:true,referenceRevision:1,createdAt:now,migration:{source:'logcal.app',sourceId:existing.migration.sourceId,sourceUrl:'https://logcal-images-dev.s3.amazonaws.com/photo.jpg',kind:'image',version:1}}];await fs.writeFile(path.join(directory,'files',fileId),bytes);
 expect(await importLogcalPerson(args(input))).toMatchObject({entriesInserted:1,entriesLinked:1,skippedDeletedEntries:1,uploads:1,applied:false});expect(await rows('logEntries').countDocuments()).toBe(2);
 expect(await importLogcalPerson({...args(input),apply:true})).toMatchObject({applied:true});const merged=await rows('logEntries').findOne({_id:existing._id});
 expect(merged).toMatchObject({ownerId:cyrus,title:'Edited in New Drugs',place:'Updated place',revision:8,members:[cyrus,laura,target],historicalPeople:['Former friend'],contributions:[{userId:cyrus,note:'Current Cyrus note'},{userId:laura,note:'Current Laura note'},{userId:target,note:'Their original words',fileIds:[fileId]}]});expect(merged?.migration).toMatchObject({linkedAccounts:[{sourceUserId:'old-ancat',userId:target}],originalHistoricalPeople:[{sourceId:'old-ancat'},{sourceId:'other'}]});
 expect(await rows('users').findOne({_id:cyrus})).toMatchObject({storageBytes:123});expect(await rows('users').findOne({_id:laura})).toMatchObject({storageBytes:456});expect(await rows('users').findOne({_id:target})).toMatchObject({storageBytes:10+bytes.length});expect(await rows('users').countDocuments()).toBe(3);expect(await rows('notifications').countDocuments()).toBe(0);
 await rows('logEntries').updateOne({_id:existing._id,'contributions.userId':target},{$set:{'contributions.$.note':'Updated after migration'}});expect(await importLogcalPerson({...args(input),apply:true})).toMatchObject({alreadyApplied:true,applied:false});expect(await rows('logEntries').findOne({_id:existing._id})).toMatchObject({contributions:expect.arrayContaining([{userId:target,note:'Updated after migration',fileIds:[fileId],hasContributed:true}])});expect(await fs.readFile(path.join(directory,'target',fileId))).toEqual(bytes);
});
it('refuses blocked or already-participating joins instead of overwriting access or contribution data',async()=>{
 const source=entry(),input=plan([source]);await previous(source);await rows('blocks').insertOne({_id:'block',members:[target,cyrus]});await expect(importLogcalPerson({...args(input),apply:true})).rejects.toThrow('block');expect(await rows('dataMigrations').countDocuments()).toBe(0);
 await rows('blocks').deleteMany({});await rows<{_id:string;members:string[]}>('logEntries').updateOne({_id:source._id},{$addToSet:{members:target}});await expect(importLogcalPerson({...args(input),apply:true})).rejects.toThrow('already participates');
});

it('keeps an already joined contribution when the source contributes no content',async()=>{
 const source=entry();source.contributions[0].note='';await previous(source,{members:[cyrus,laura,target],contributions:[{userId:cyrus,note:'Cyrus note',fileIds:[]},{userId:laura,note:'Laura note',fileIds:[]},{userId:target,note:'Written in New Drugs',fileIds:[]}]});
 expect(await importLogcalPerson({...args(plan([source])),apply:true})).toMatchObject({entriesLinked:0,alreadyParticipatingEntries:1,applied:true});
 const row=await rows('logEntries').findOne({_id:source._id});expect(row?.members).toEqual([cyrus,laura,target]);expect(row?.contributions).toHaveLength(3);expect(row?.contributions).toEqual(expect.arrayContaining([{userId:target,note:'Written in New Drugs',fileIds:[]}]));expect(row?.historicalPeople).toEqual(['Former friend']);
});
