import {it,expect} from 'vitest';
import {logDate,recurrenceOn,logQueryGroups} from '../shared/log';
import {parseDestination,destinationPath} from '../shared/navigation';
import {modeForDestination} from '../shared/experience';
it('preserves date-only records and handles leap-year recurrences without UTC conversion',()=>{expect(logDate.safeParse('2025-02-29').success).toBe(false);expect(logDate.parse('2024-02-29')).toBe('2024-02-29');expect(recurrenceOn({date:'2024-02-29',recurrence:'anniversary'},2025)).toBe('2025-02-28');expect(recurrenceOn({date:'2024-02-29',recurrence:'birthday'},2023)).toBeNull();});
it('supports private phrases, AND/OR and exclusion without interpreting user regex',()=>{expect(logQueryGroups('tennis + "at the park" | walk -rain')).toEqual([[{text:'tennis',exclude:false},{text:'at the park',exclude:false}],[{text:'walk',exclude:false},{text:'rain',exclude:true}]]);});
it('routes native Log and alternate primary modes without shadowing entry or composer paths',()=>{const origin='https://druggie.org';for(const destination of [{view:'log' as const},{view:'log' as const,resourceId:'abc'},{view:'log_compose' as const,date:'2026-09-26'},{view:'log' as const,resourceId:'abc',mode:'posts' as const}]){expect(parseDestination(destinationPath(destination),origin)).toEqual(destination);}expect(parseDestination('/log',origin)).toMatchObject({view:'log'});expect(modeForDestination({view:'log'})).toBe('log');});
it('round-trips filtered calendar links and rejects impossible dates before rendering',()=>{const state={view:'log' as const,logMonth:'2026-02',logScope:'shared' as const,logArrangement:'gallery' as const,personId:'a-friend',query:'tennis'};expect(parseDestination(destinationPath(state),'https://druggie.org')).toEqual(state);expect(parseDestination('/log/new?date=2026-02-30','https://druggie.org')).toBeNull();expect(parseDestination('/log?month=2026-13','https://druggie.org')).toBeNull();});
it('rebases a draft without overwriting shared fields the person never edited',async()=>{const {rebaseLogDraft,logFields}=await import('../shared/log');const base={...logFields.parse({date:'2026-09-26',title:'Old title',place:'Park'}),id:'entry',ownerId:'me',revision:1,createdAt:'',updatedAt:'',membership:'member' as const,contributors:[{userId:'me',name:'Me',note:'Old note',files:[]}],invitations:[]};const latest={...base,title:'Their new title',place:'Their new place',revision:2};const draft=logFields.parse({date:base.date,title:'My new title',place:base.place});const result=rebaseLogDraft(base,latest,'me',draft,'My new note',[]);expect(result.entry.title).toBe('My new title');expect(result.entry.place).toBe('Their new place');expect(result.note).toBe('My new note');});
