// @vitest-environment jsdom
import {act,createElement} from 'react';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {LogSettings} from '../src/LogSettings';
import {setupDOM} from './dom';
const api=vi.hoisted(()=>({operation:vi.fn()}));vi.mock('../src/api',async original=>({...await original<typeof import('../src/api')>(),operation:api.operation}));
let dom:ReturnType<typeof setupDOM>;
beforeEach(()=>{dom=setupDOM();api.operation.mockReset().mockImplementation(async(name,input)=>name==='log.preferences'?{arrangement:'calendar',views:[],todayPresentation:'full'}:name==='log.birthday_get'?{birthday:null}:name==='log.birthday_update'?input:input);});afterEach(()=>dom.cleanup());
it('saves a month/day birthday from Log settings without requesting a year',async()=>{await act(async()=>dom.root.render(createElement(LogSettings,{close:vi.fn(),navigate:vi.fn()})));const month=dom.container.querySelector<HTMLSelectElement>('[aria-label="Birthday month"]')!,day=dom.container.querySelector<HTMLSelectElement>('[aria-label="Birthday day"]')!;await act(async()=>{month.value='2';month.dispatchEvent(new Event('change',{bubbles:true}));});await act(async()=>{day.value='29';day.dispatchEvent(new Event('change',{bubbles:true}));});expect(dom.container.textContent).toContain('Shown to friends.');await act(async()=>dom.container.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(api.operation).toHaveBeenCalledWith('log.birthday_update',{birthday:{month:2,day:29}},expect.objectContaining({key:expect.any(String)}));expect(dom.container.textContent).toContain('Remove birthday');expect(dom.container.querySelector('input[type=date]')).toBeNull();let finish!:(value:unknown)=>void;api.operation.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));act(()=>[...dom.container.querySelectorAll<HTMLButtonElement>('.view-tabs button')].find(button=>button.textContent==='Grid')!.click());expect(dom.container.querySelector('form button.solid')?.textContent).toBe('Saved');await act(async()=>finish({arrangement:'gallery',views:[],todayPresentation:'full'}));expect(dom.container.querySelector('form button.solid')?.textContent).toBe('Saved');});
