// @vitest-environment jsdom
import { act, createElement } from 'react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { setupDOM } from './dom';
import { NotificationsPanel } from '../src/NotificationsPanel';
import type { Notification } from '../shared/notifications';
const transport = vi.hoisted(() => ({ operation: vi.fn() }));
vi.mock('../src/api', async original => ({ ...await original<typeof import('../src/api')>(), operation: transport.operation }));
let dom: ReturnType<typeof setupDOM>;
const item: Notification = { id: 'notice', kind: 'message', title: 'Message from Friend', text: 'Saturday works', createdAt: '2026-09-25T12:00:00.000Z', read: false, link: { rel: 'open_in_newdrugs', targetKind: 'exact', resourceType: 'conversation', resourceId: 'connection', title: 'Open conversation', url: 'https://dev.druggie.org/messages/connection' } };
beforeEach(() => { dom = setupDOM(); transport.operation.mockReset().mockResolvedValue({ read: true }); });
afterEach(() => dom.cleanup());
it('retains a notification as read and lets it reopen the exact destination', async () => {
  const navigate = vi.fn();
  await act(async () => dom.root.render(createElement(NotificationsPanel, { state: { unread: 1, items: [item] }, navigate })));
  const link = dom.container.querySelector<HTMLAnchorElement>('.notification-list a')!;
  expect(link.textContent).toContain('Unread');
  await act(async () => link.click());
  expect(transport.operation).toHaveBeenCalledWith('notifications.read', { notificationId: item.id });
  await act(async () => dom.root.render(createElement(NotificationsPanel, { state: { unread: 0, items: [{ ...item, read: true }] }, navigate })));
  expect(dom.container.querySelector('.notification-list a')).toBe(link); expect(link.dataset.read).toBe('true'); expect(link.textContent).toContain('Read');
  expect(link.querySelector('time')?.dateTime).toBe(item.createdAt);
  transport.operation.mockClear();
  await act(async () => link.click());
  expect(navigate).toHaveBeenLastCalledWith(expect.objectContaining({ view: 'messages', resourceId: 'connection' }));
  expect(transport.operation).not.toHaveBeenCalled();
});
it('marks the visible history read without removing the notification cards',async()=>{
 const refresh=vi.fn().mockResolvedValue(undefined);
 transport.operation.mockResolvedValue({read:true,readAt:'2026-10-05T12:00:00.000Z'});
 await act(async()=>dom.root.render(createElement(NotificationsPanel,{state:{unread:1,items:[item]},navigate:vi.fn(),refresh})));
 const link=dom.container.querySelector<HTMLAnchorElement>('.notification-list a')!;
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.notification-toolbar button')!.click());
 expect(transport.operation).toHaveBeenCalledWith('notifications.read_all');
 expect(refresh).toHaveBeenCalledOnce();
 expect(dom.container.querySelector('.notification-list a')).toBe(link);
 expect(link.dataset.read).toBe('true');
 expect(link.textContent).toContain('Read');
 expect(dom.container.querySelector('.notification-toolbar')).toBeNull();
 await act(async()=>dom.root.render(createElement(NotificationsPanel,{state:{unread:1,items:[{...item,text:'A newer message',createdAt:'2026-10-05T12:01:00.000Z'}]},navigate:vi.fn(),refresh})));
 expect(link.dataset.read).toBeUndefined();
 expect(link.textContent).toContain('Unread');
 expect(dom.container.querySelector('.notification-toolbar button')?.textContent).toBe('Mark all read');
});
