// @vitest-environment jsdom
import {act,createElement,useState} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {TalkDock} from '../src/TalkDock';
import {TalkContext} from '../src/TalkSession';
import {NavigationContext} from '../src/NavigationContext';
import {setupDOM} from './dom';

let dom:ReturnType<typeof setupDOM>;
const on={identity:'host',name:'@host',metadata:'{}',audioTrackPublications:new Map([['mic',{track:{},isMuted:false}]])};
const muted={identity:'friend',name:'@friend',metadata:'{}',audioTrackPublications:new Map()};
function Harness({mic=true,role='host',profileIds=[],onEnd=vi.fn(),onLeave=vi.fn()}:{mic?:boolean;role?:'host'|'listener';profileIds?:string[];onEnd?:()=>Promise<void>;onLeave?:()=>Promise<void>}){const [expanded,setExpanded]=useState(false);const talk={space:{id:'space',title:'Night walks',description:'Outside',createdAt:new Date(Date.now()-90000).toISOString(),hostId:'host',speakerIds:['host','friend'],profileIds,participantCards:[{id:'host',name:'Host Person',handle:'host'},{id:'friend',name:'Friend Person',handle:'friend'}],myRole:role},room:{localParticipant:on},members:[on,muted],speaking:new Set(),reactions:[],requests:[{personId:'guest',name:'@guest'}],mic,audioBlocked:false,expanded,busy:false,error:'',copied:false,setExpanded,share:vi.fn(),end:onEnd,leave:onLeave,toggleMic:vi.fn(),respond:vi.fn()} as any;return createElement(TalkContext.Provider,{value:talk,children:createElement(TalkDock)});}
beforeEach(()=>{dom=setupDOM();});afterEach(()=>dom.cleanup());
it('shows compact participant photos without visible counts and keeps detailed controls in the expanded panel',async()=>{
 await act(async()=>dom.root.render(createElement(Harness)));
 expect(dom.container.querySelector('.talk-presence-group')?.getAttribute('aria-label')).toBe('2 speaking');
 expect(dom.container.querySelectorAll('.talk-compact-avatars .space-avatar')).toHaveLength(2);
 expect(dom.container.querySelector('.talk-compact-presence')?.textContent).not.toContain('speaking');
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.talk-dock-title')!.click());
 expect(dom.container.querySelector('.talk-compact-presence')).toBeNull();
 const headings=[...dom.container.querySelectorAll('.talk-dock-people h3')].map(node=>node.textContent);
 expect(headings).toEqual(['Speakers','Requests to speak','Listeners']);
 expect([...dom.container.querySelectorAll('.talk-person-mic')].map(node=>node.getAttribute('aria-label'))).toEqual(['@friend muted']);
 expect(dom.container.querySelector('.talk-dock-footer .talk-live-time')?.textContent).toMatch(/^Live \d+:\d\d$/);
 expect(dom.container.querySelector('.talk-dock-footer button[aria-label="Share talk space"]')).not.toBeNull();
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('button[aria-label="Options for @friend"]')!.click());
 expect(dom.container.querySelector('.talk-dock-people>.space-avatar-grid + .space-person-menu')?.textContent).toContain('Offer host');
 expect(dom.container.querySelector('.space-person-menu .space-person-actions')?.querySelectorAll('button')).toHaveLength(5);
 expect(dom.container.querySelector('.space-person-menu .space-person-actions')?.textContent).toContain('Report');
 expect([...dom.container.querySelectorAll('.talk-dock-bar>button')].map(button=>button.getAttribute('aria-label'))).toEqual([null,'End talk space','Mic on. Mute microphone','Collapse talk space']);
});
it('uses a slashed microphone icon while muted',async()=>{
 await act(async()=>dom.root.render(createElement(Harness,{mic:true})));
 const liveIcon=dom.container.querySelector('.talk-mic svg')?.innerHTML;
 await act(async()=>dom.root.render(createElement(Harness,{mic:false})));
 expect(dom.container.querySelector('.talk-mic')?.getAttribute('aria-label')).toBe('Mic off. Unmute microphone');
 expect(dom.container.querySelector('.talk-mic svg')?.innerHTML).not.toBe(liveIcon);
});
it('confirms before leaving or ending a Talk',async()=>{
 const onEnd=vi.fn(async()=>{}),onLeave=vi.fn(async()=>{});
 await act(async()=>dom.root.render(createElement(Harness,{onEnd})));
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.talk-hangup')!.click());
 expect(onEnd).not.toHaveBeenCalled();
 expect(dom.container.textContent).toContain('End this talk space?');
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.delete-confirmation-actions button')!.click());
 expect(onEnd).not.toHaveBeenCalled();
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.talk-hangup')!.click());
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.delete-confirmation-submit')!.click());
 expect(onEnd).toHaveBeenCalledTimes(1);
 await act(async()=>dom.root.render(createElement(Harness,{role:'listener',onLeave})));
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.talk-hangup')!.click());
 expect(dom.container.textContent).toContain('Leave this talk space?');
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.delete-confirmation-submit')!.click());
 expect(onLeave).toHaveBeenCalledTimes(1);
});
it('uses one two-step card for profile access and host controls without repeating the photo',async()=>{
 const navigate=vi.fn();
 await act(async()=>dom.root.render(createElement(NavigationContext.Provider,{value:navigate,children:createElement(Harness,{profileIds:['host','friend']})})));
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.talk-dock-title')!.click());
 const person=dom.container.querySelector<HTMLButtonElement>('button[aria-label="Options for @friend"]')!;
 expect(person.textContent).toBe('F@friend');
 await act(async()=>person.click());
 let menu=dom.container.querySelector('.space-person-menu')!;
 expect(menu.querySelector('strong')?.textContent).toBe('Friend Person');
 expect(menu.querySelector('small')?.textContent).toBe('@friend');
 expect(menu.querySelector('.space-avatar')).toBeNull();
 expect(menu.querySelector<HTMLAnchorElement>('a[href="/people/friend"]')?.textContent).toBe('View profile');
 expect(menu.textContent).toContain('Remove mic');
 await act(async()=>person.click());
 expect(dom.container.querySelector('.space-person-menu')).toBeNull();
 await act(async()=>person.click());
 menu=dom.container.querySelector('.space-person-menu')!;
 await act(async()=>menu.querySelector<HTMLAnchorElement>('a[href="/people/friend"]')!.click());
 expect(navigate).toHaveBeenCalledWith({view:'person',resourceId:'friend'});
 expect(dom.container.querySelector('.talk-dock')).not.toBeNull();
 expect(dom.container.querySelector('.talk-dock')?.hasAttribute('data-expanded')).toBe(false);
});
it('opens the same card for listeners and withholds private profile navigation',async()=>{
 const navigate=vi.fn();
 await act(async()=>dom.root.render(createElement(NavigationContext.Provider,{value:navigate,children:createElement(Harness,{role:'listener',profileIds:['friend']})})));
 await act(async()=>dom.container.querySelector<HTMLButtonElement>('.talk-dock-title')!.click());
 const host=dom.container.querySelector<HTMLButtonElement>('button[aria-label="Options for @host"]')!;
 await act(async()=>host.click());
 expect(dom.container.querySelector('.space-person-menu')?.textContent).toContain('Profile unavailable');
 expect(dom.container.querySelector('.space-person-menu a')).toBeNull();
 const friend=dom.container.querySelector<HTMLButtonElement>('button[aria-label="Options for @friend"]')!;
 await act(async()=>friend.click());
 expect(dom.container.querySelector('.space-person-menu a')?.getAttribute('href')).toBe('/people/friend');
 await act(async()=>dom.container.querySelector<HTMLAnchorElement>('.space-person-menu a')!.click());
 expect(navigate).toHaveBeenCalledWith({view:'person',resourceId:'friend'});
});
