import {Temporal} from '@js-temporal/polyfill';

/** Wayfinder supplies a request-local clock after its stable prompt prefix. */
export function agentClock(timeZone:string,now=Date.now()){
 let local:Temporal.ZonedDateTime;
 try{local=Temporal.Instant.fromEpochMilliseconds(now).toZonedDateTimeISO(timeZone);}catch{timeZone='UTC';local=Temporal.Instant.fromEpochMilliseconds(now).toZonedDateTimeISO(timeZone);}
 const start=local.startOfDay(),end=start.add({days:1});
 return {currentTimeEpochMs:now,currentTimeUtc:new Date(now).toISOString(),timeZone,localDate:local.toPlainDate().toString(),localTime:local.toPlainTime().toString({smallestUnit:'second'}),utcOffset:local.offset,todayStartUtc:start.toInstant().toString(),todayEndUtc:end.toInstant().toString()};
}
export const agentClockText=(timeZone:string,now=Date.now())=>`Trusted runtime clock, generated by the host for this request:\n${JSON.stringify(agentClock(timeZone,now))}\nUse this local date and timezone for today, yesterday and tomorrow, and for displaying message times. UTC timestamps are storage values, not the person's calendar day. Use the supplied day bounds when a calendar query needs UTC ranges.`;
