import { MongoClient, type ClientSession, type Db } from 'mongodb';
import { config } from './config';

export const mongo = new MongoClient(config.MONGODB_URI, { serverSelectionTimeoutMS: config.NODE_ENV==='test'?20000:5000, maxPoolSize: config.MONGODB_POOL_SIZE, maxConnecting: 2, waitQueueTimeoutMS: 10000 });
let database: Db;
export interface Row { _id: string; [key: string]: unknown }
export function db() { if (!database) throw new Error('Database is not connected.'); return database; }
export function rows<T extends { _id: string } = Row>(name: string) { return db().collection<T>(name); }
export async function transaction<T>(run: (session: ClientSession) => Promise<T>): Promise<T> {
  const session = mongo.startSession();
  try { return await session.withTransaction(() => run(session), { readConcern: { level: 'snapshot' }, writeConcern: { w: 'majority' } }) as T; }
  finally { await session.endSession(); }
}
export async function connectDatabase(name?: string,options:{indexes?:boolean}={}) {
  await mongo.connect();
  database = mongo.db(name);
  const hello = await database.admin().command({ hello: 1 });
  if (!hello.setName) throw new Error('The cloud MongoDB connection needs a replica set for atomic credits.');
  if(options.indexes===false)return;
  await Promise.all([
    rows('routerStates').createIndex({userId:1,purpose:1}),
    rows('routerUsageJobs').createIndex({availableAt:1}),
    rows('responseCleanup').createIndex({availableAt:1}),
    rows('responseCleanup').createIndex({userId:1}),
    rows('deviceLogins').createIndex({userCodeHash:1},{unique:true}),
    rows('deviceLogins').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('tokens').createIndex({userId:1,revokedAt:1}),
    rows('mediaWriteIntents').createIndex({availableAt:1}),
    rows('mediaDeletes').createIndex({availableAt:1}),
    rows('logSearchJobs').createIndex({availableAt:1}),
    rows('logSearchJobs').createIndex({viewerIds:1}),
    rows('logPhotoDescriptionJobs').createIndex({availableAt:1}),
    rows('iousLedgers').createIndex({members:1,updatedAt:-1,_id:-1}),
    rows('iousEntries').createIndex({pairId:1,revision:-1}),
    rows('logSearchChunks').createIndex({entryId:1}),
    rows('logSearchChunks').createIndex({viewerIds:1,indexVersion:1}),
    rows('logSearchResults').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('logSearchResults').createIndex({userId:1,expiresAt:-1}),
    rows('agentMemorySlots').createIndex({userId:1,key:1},{unique:true}),
    rows('agentMemorySlots').createIndex({userId:1,core:1,key:1}),
    rows('attachmentReferences').createIndex({kind:1,sourceId:1}),
    rows('attachmentReferences').createIndex({ownerId:1,fileId:1,_id:1}),
    rows('attachmentReferences').createIndex({ownerId:1,kind:1,fileId:1}),
    rows('uploads').createIndex({userId:1,attachmentKinds:1,_id:-1}),
    rows('uploads').createIndex({userId:1,attachmentKinds:1,createdAt:-1,_id:-1}),
    rows('retrievalJobs').createIndex({availableAt:1}),
    rows('retrievalJobs').createIndex({kind:1,userId:1}),
    rows('retrievalJobs').createIndex({kind:1,viewerIds:1}),
    rows('requestRates').createIndex({resetTime:1},{expireAfterSeconds:0}),
    rows('ledgerActivityReceipts').createIndex({userId:1,kind:1,orderKey:-1}),
    rows('ledgerActivityReceipts').createIndex({periodId:1,kind:1,orderKey:1}),
    rows('ledgerActivityPeriods').createIndex({userId:1,orderKey:-1}),
    rows('ledgerActivityJobs').createIndex({availableAt:1}),
    rows('ledgerActivityJobs').createIndex({userId:1}),
    rows('ledgerActivityMoves').createIndex({userId:1}),
    rows('ledgerActivityBuilds').createIndex({done:1,leaseUntil:1}),
    rows('recordEvents').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('liveSubscriptions').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('liveSubscriptions').createIndex({userId:1,channel:1}),
    rows('logContactSources').createIndex({members:1,_id:1}),
    rows('logContactCounts').createIndex({userId:1,count:-1,personId:1}),
    rows('connections').createIndex({members:1,status:1,_id:1}),
    rows('quizzes').createIndex({members:1,createdAt:-1,_id:-1}),
    rows('dinderMeals').createIndex({category:1,_id:1}),
    rows('dinderMeals').createIndex({name:1,_id:1}),
    rows('dinderMeals').createIndex({orderKey:1,_id:1}),
    rows('dinderMeals').createIndex({category:1,orderKey:1,_id:1}),
    rows('dinderMeals').createIndex({catalogApproved:1,name:1,_id:1}),
    rows('dinderMeals').createIndex({catalogApproved:1,orderKey:1,_id:1}),
    rows('dinderMatches').createIndex({members:1,createdAt:-1,_id:-1}),
    rows('dinderMatches').createIndex({members:1,status:1}),
    rows('dinderDays').createIndex({userId:1,date:1}),
    rows('dinderSwipes').createIndex({userId:1,desiredAt:1,mode:1,mealId:1}),
    rows('dinderChoices').createIndex({userId:1,pending:1,liked:1,_id:1}),
    rows('dinderChoices').createIndex({userId:1,mealId:1}),
    rows('dinderRollovers').createIndex({nextAt:1,leaseUntil:1}),
    rows('dinderLikes').createIndex({mealId:1,mode:1,areaCell:1,desiredAt:1,createdAt:1,_id:1}),
    rows('dinderLikes').createIndex({userId:1,date:1}),
    rows('dinderLikes').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('dinderMessages').createIndex({matchId:1,createdAt:-1,_id:-1}),
    rows('dinderMessages').createIndex({matchId:1,fromId:1,clientId:1},{unique:true}),
    rows('notifications').createIndex({userId:1,matchId:1,readAt:1}),
    rows('quizViews').createIndex({userId:1,sortKey:-1}),
    rows('bffs').createIndex({userId:1,createdAt:-1,_id:-1}),
    rows('circlePaths').createIndex({edgeIds:1,_id:1}),
    rows('circlePaths').createIndex({pairId:1,via:1}),
    rows('circlePairs').createIndex({members:1,mutualCount:-1,_id:1}),
    rows('circleJobs').createIndex({createdAt:1,_id:1}),
    rows('peopleHides').createIndex({userId:1,createdAt:-1,_id:-1}),
    rows('logContactStates').createIndex({dirty:1,leaseUntil:1}),
    rows('logEntries').createIndex({members:1,_id:1}),
    rows('logEntries').createIndex({calendarMonthDay:1,_id:1}),
    rows('logEntries').createIndex({members:1,calendarMonthDay:1,date:-1,createdAt:-1,_id:-1}),
    rows('logEntries').createIndex({members:1,recurrence:1,calendarMonthDay:1,_id:1}),
    rows('logEntries').createIndex({joinKey:1},{unique:true,partialFilterExpression:{joinKey:{$type:'string'}}}),
    rows('logEntries').createIndex({members:1,date:-1,createdAt:-1,_id:-1}),
    rows('logEntries').createIndex({members:1,updatedAt:-1,_id:-1}),
    rows('logEntries').createIndex({memberPairKeys:1,date:-1,createdAt:-1,_id:-1}),
    rows('logEntries').createIndex({invited:1,date:-1,createdAt:-1,_id:-1}),
    rows('logEntries').createIndex({'contributions.fileIds':1}),
    rows('makeDrafts').createIndex({userId:1,expiresAt:1}),
    rows('makeDrafts').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('websites').createIndex({code:1},{unique:true}),
    rows('websites').createIndex({previewToken:1},{unique:true}),
    rows('websiteRevisions').createIndex({userId:1,revision:-1}),
    rows('websiteCheckpoints').createIndex({userId:1,createdAt:-1,_id:-1}),
    rows('websiteSources').createIndex({userId:1,updatedAt:-1,_id:-1}),
    rows('websiteSourceRates').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('calls').createIndex({connectionId:1,createdAt:-1,_id:-1}),
    rows('calls').createIndex({connectionId:1,active:1},{unique:true,partialFilterExpression:{active:true}}),
    rows('calls').createIndex({members:1,active:1,createdAt:-1}),
    rows('calls').createIndex({calleeId:1,active:1,status:1,createdAt:-1}),
    rows('spaces').createIndex({status:1,createdAt:-1,_id:-1}),
    rows('spaces').createIndex({status:1,_id:1}),
    rows('spaces').createIndex({hostId:1,status:1},{unique:true,partialFilterExpression:{status:'live'}}),
    rows('spaces').createIndex({hostId:1},{name:'one_hosted_talk_start_or_live',unique:true,partialFilterExpression:{status:{$in:['starting','live']}}}),
    rows('spacePresenceHistory').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('spacePresence').createIndex({spaceId:1}),
    rows('spaceSpeakerRequests').createIndex({spaceId:1,status:1,createdAt:1}),
    rows('spaceRemovals').createIndex({spaceId:1,userId:1}),
    rows('spaceRemovals').createIndex({userId:1,spaceId:1}),
    rows('liveMediaEffects').createIndex({availableAt:1,leaseUntil:1}),
    rows('agentSessionCleanup').createIndex({ availableAt: 1 }),
    rows('automations').createIndex({ status: 1, nextRunAt: 1 }),
    rows('automations').createIndex({ userId: 1, createdAt: -1 }),
    rows('runs').createIndex({ automationId: 1, userId: 1, createdAt: -1, _id: -1 }),
    rows('runs').createIndex({ status: 1, 'sleep.until': 1 }),
    rows('agentInbox').createIndex({ userId: 1, createdAt: -1, _id: -1 }),
    rows('agentInbox').createIndex({ userId: 1, archivedAt: 1, readAt: 1 }),
    rows('agentInbox').createIndex({ runId: 1 }, { unique: true, partialFilterExpression: { runId: { $type: 'string' } } }),
    rows('chatSearchChunks').createIndex({ userId: 1, indexVersion: 1, role: 1 }),
    rows('chatSearchChunks').createIndex({ userId: 1, messageId: 1 }),
    rows('chatSearchJobs').createIndex({ availableAt: 1 }),
    rows('chatSearchJobs').createIndex({ userId: 1, messageId: 1 }),
    rows('chatSearchResults').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('chatSearchResults').createIndex({ userId: 1, expiresAt: -1 }),
    rows('dmSearchChunks').createIndex({viewerIds:1,indexVersion:1,connectionId:1}),
    rows('dmSearchChunks').createIndex({messageId:1}),
    rows('dmSearchJobs').createIndex({availableAt:1}),
    rows('dmSearchJobs').createIndex({messageId:1}),
    rows('dmSearchResults').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('dmSearchResults').createIndex({userId:1,expiresAt:-1}),
    rows('pushSubscriptions').createIndex({ userId: 1, revokedAt: 1 }),
    rows('pushSubscriptions').createIndex({ sessionId: 1 }),
    rows('pushOutbox').createIndex({ status: 1, availableAt: 1 }),
    rows('pushOutbox').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('users').createIndex({ suspendedAt: 1 }),
    rows('users').createIndex({createdAt:-1,_id:-1},{partialFilterExpression:{handle:{$type:'string'}}}),
    rows('users').createIndex({ handle: 1 }, { unique: true, partialFilterExpression: { handle: { $type: 'string' } } }),
    rows('users').createIndex({logHandleGrams:1}),
    rows('users').createIndex({logNameGrams:1}),
    rows('users').createIndex({ discoverable: 1, cityKey: 1, _id: 1 }),
    rows('users').createIndex({ 'area.point':'2dsphere' }),
    rows('sessions').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('passkeyChallenges').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('passkeys').createIndex({userId:1,createdAt:-1}),
    rows('tokens').createIndex({ userId: 1, createdAt: -1 }),
    rows('tokens').createIndex({ hash: 1 }, { unique: true }),
    rows('messages').createIndex({ userId: 1, createdAt: -1, _id: -1 }),
    rows('messages').createIndex({userId:1,'files.id':1}),
    rows('ledger').createIndex({ userId: 1, createdAt: -1 }),
    rows('ledger').createIndex({ userId: 1, createdAt: -1, _id: -1 }),
    rows('runs').createIndex({ userId: 1, status: 1 }),
    rows('runs').createIndex({status:1,priority:1,updatedAt:1}),
    rows('workerHealth').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('runs').createIndex({ status: 1, nextAttempt: 1, updatedAt: 1 }),
    rows('agentCredentials').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('operationEmbeddings').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    ...['postSaves'].map(name=>rows(name).createIndex({userId:1,targetId:1},{unique:true})),
    ...['postSaves'].map(name=>rows(name).createIndex({userId:1,createdAt:-1,_id:-1})),
    rows('posts').createIndex({ cityKey: 1, _id: -1 }),
    rows('posts').createIndex({ 'area.point':'2dsphere' }),
    rows('posts').createIndex({ userId: 1, _id: -1 }),
    rows('posts').createIndex({userId:1,rootId:1}),
    rows('postLikes').createIndex({createdAt:-1,_id:-1}),
    rows('postLikes').createIndex({userId:1,createdAt:-1,_id:-1}),
    rows('posts').createIndex({ parentId: 1, deletedAt: 1, _id: -1 }),
    rows('postLikes').createIndex({ postId: 1, userId: 1 }, { unique: true }),
    rows('postPollVotes').createIndex({postId:1}),
    rows('posts').createIndex({ fileIds: 1, deletedAt: 1 }),
    rows('linkPreviews').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('postVideoLinks').createIndex({userId:1,createdAt:-1,_id:-1}),
    rows('postVideoLinks').createIndex({postId:1}),
    rows('postVideoLinkJobs').createIndex({availableAt:1,leaseUntil:1}),
    rows('linkPreviewRates').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('connections').createIndex({ members: 1, _id: -1 }),
    rows('connections').createIndex({ members: 1, updatedAt: -1, _id: -1 }),
    rows('connections').createIndex({ toId: 1, status: 1, createdAt: -1 }),
    rows('notifications').createIndex({ userId: 1, readAt: 1, createdAt: -1 }),
    rows('notifications').createIndex({userId:1,readAt:1,createdAt:-1,_id:-1}),
    rows('notifications').createIndex({userId:1,createdAt:-1,_id:-1}),
    rows('notificationRules').createIndex({userId:1,createdAt:-1,_id:-1}),
    rows('notificationRules').createIndex({userId:1,signature:1},{unique:true,partialFilterExpression:{signature:{$type:'string'}}}),
    rows('notificationRules').createIndex({kind:1,personId:1,enabled:1,_id:1}),
    rows('notificationRules').createIndex({kind:1,postId:1,enabled:1,_id:1}),
    rows('notificationRules').createIndex({kind:1,enabled:1,createdAt:1,indexedAt:1}),
    rows('notificationRules').createIndex({enabled:1,nextAt:1,leaseUntil:1}),
    rows('notificationSettings').createIndex({'types.talk_first_live':1,_id:1}),
    rows('notificationEvents').createIndex({status:1,availableAt:1,createdAt:1}),
    rows('notificationEvents').createIndex({expiresAt:1},{expireAfterSeconds:0}),
    rows('notificationRuleJobs').createIndex({availableAt:1,leaseUntil:1}),
    rows('spacePresence').createIndex({userId:1,spaceId:1}),
    rows('connections').createIndex({toId:1,status:1,notificationReadAt:1,createdAt:-1,_id:-1}),
    rows('connections').createIndex({toId:1,createdAt:-1,_id:-1}),
    rows('uploads').createIndex({ retained: 1, expiresAt: 1 }),
    rows('uploads').createIndex({ userId: 1, _id: -1 }),
    rows('uploads').createIndex({ userId: 1, createdAt: -1, _id: -1 }),
    rows('directMessages').createIndex({ connectionId: 1, _id: -1 }),
    rows('blocks').createIndex({ members: 1 }),
    rows('blocks').createIndex({pairId:1}),
    rows('searchOutbox').createIndex({ status: 1, availableAt: 1 }),
    rows('searchDocuments').createIndex({ indexVersion: 1, indexedAt: -1, _id: 1 }),
    rows('searchDocuments').createIndex({ dataset: 1, ownerId: 1 }),
    rows('searchQueryVectors').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('searchRetrievals').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('searchRetrievals').createIndex({ userId: 1, expiresAt: -1 }),
    rows('searchRates').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 }),
    rows('receipts').createIndex({ userId: 1, createdAt: -1 }),
  ]);
}
