import {startWorkerHealth} from './workerHealth';
import {startLogContactWorker} from './logContacts';
import {startLogCalendarWorker} from './log';
import {startLogSearchWorker} from './search/log';
import {startLedgerActivityWorker} from './ledgerActivity';
import {startAttachmentReferenceWorker} from './attachmentReferences';
import {startRetrievalWorker} from './search/replication';
import { startChatSearchWorker } from './search/chat';
import {startDMSearchWorker} from './search/dm';
import { startPushWorker } from './push';
import { createApp } from './app';
import { connectDatabase, mongo } from './db';
import { config } from './config';
import { startWorker } from './agent';
import { ensureStarterPool } from './starterPool';
import { stopLiveState } from './liveState';
import { startSearchWorker } from './search/worker';
import { expireUploads } from './uploads';
import {startLiveMediaEffectWorker} from './liveMediaEffects';
import {startSpacePresenceWorker} from './spaces';
import {startCircleWorker} from './circle';
import {startNotificationWorker} from './notificationEvents';
import {startNotificationRuleIndex} from './notificationRuleIndex';
import {startNotificationSchedule} from './notificationSchedule';
import {startPostVideoLinkWorker} from './postVideoLinks';
import {migrateAutomationAuthority} from './automations';

await connectDatabase();
if(config.PROCESS_ROLE!=='web')await migrateAutomationAuthority();
await ensureStarterPool();
const background = config.PROCESS_ROLE !== 'web';
const stopWorkerHealth = background ? startWorkerHealth() : async () => {};
const stopWorker = background ? startWorker() : async () => {};
const stopSearch = background ? startSearchWorker() : async () => {};
const stopPush = background ? startPushWorker() : async () => {};
const stopChatSearch = background ? startChatSearchWorker() : async () => {};
const stopDMSearch = background ? startDMSearchWorker() : async () => {};
const stopLedgerActivity = background ? startLedgerActivityWorker() : async () => {};
const stopContacts = background ? startLogContactWorker() : async () => {};
const stopCalendar = background ? startLogCalendarWorker() : async () => {};
const stopLogSearch = background ? startLogSearchWorker() : async () => {};
const stopRetrieval = background ? startRetrievalWorker() : async () => {};
const stopAttachmentReferences = background ? startAttachmentReferenceWorker() : async () => {};
const stopLiveMediaEffects = background ? startLiveMediaEffectWorker() : async () => {};
const stopSpacePresence = background ? startSpacePresenceWorker() : async () => {};
const stopCircle = background ? startCircleWorker() : async () => {};
const stopNotifications = background ? startNotificationWorker() : async () => {};
const stopNotificationRules = background ? startNotificationRuleIndex() : async () => {};
const stopNotificationSchedule = background ? startNotificationSchedule() : async () => {};
const stopPostVideoLinks = background ? startPostVideoLinkWorker() : async () => {};
let cleaning = false;
const uploadCleanup = background ? setInterval(() => { if (cleaning) return; cleaning = true; void expireUploads().catch(error => console.error('Upload cleanup:', error.name)).finally(() => { cleaning = false; }); }, 10000) : undefined;
const server = config.PROCESS_ROLE !== 'worker' ? createApp().listen(config.PORT, '127.0.0.1', () => {
  console.log(`new drugs API · http://127.0.0.1:${config.PORT}`);
  console.log(`Agent: ${config.aiEnabled ? 'connected' : 'waiting for API key'} · payments: ${config.paymentsEnabled ? 'connected' : 'not configured'}`);
}) : undefined;
console.log(`Process role: ${config.PROCESS_ROLE}`);
if (server) server.requestTimeout = 600000;
let stopping = false;
const shutdown = async () => {
  if (stopping) return; stopping = true;
  setTimeout(() => process.exit(1), 20000).unref(); clearInterval(uploadCleanup);
  await Promise.all([stopWorker(),stopWorkerHealth(),stopSearch(),stopPush(),stopChatSearch(),stopDMSearch(),stopLedgerActivity(),stopRetrieval(),stopLogSearch(),stopCalendar(),stopContacts(),stopAttachmentReferences(),stopLiveMediaEffects(),stopSpacePresence(),stopCircle(),stopNotifications(),stopNotificationRules(),stopNotificationSchedule(),stopPostVideoLinks(),stopLiveState()]);
  if (server) await new Promise<void>((resolve,reject) => server.close(error => error ? reject(error) : resolve()));
  await mongo.close(); process.exit(0);
};
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
