import {DeleteConfirmation} from './DeleteConfirmation';
import { useState, type FormEvent } from 'react';
import { post, errorText } from './api';
import type { Profile } from '../shared/types';
export function AccountSettings({ user, refresh, cleared }: { user: Profile; refresh(): Promise<void>; cleared(): Promise<void> }) {
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
  const save=async(event:FormEvent<HTMLFormElement>,kind:'username'|'password')=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(true);setError('');setNotice('');try{await post(`/account/${kind}`,kind==='username'?{handle:data.get('handle'),currentPassword:data.get('currentPassword')}:{password:data.get('password'),currentPassword:data.get('currentPassword')});form.reset();await refresh();setNotice(kind==='username'?'Username saved.':'Password changed. Other browser sessions are signed out.');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  return <div className="account-settings"><form className="fields" onSubmit={event=>void save(event,'username')}><h3>Username</h3><label>Username<input name="handle" autoComplete="username" autoCapitalize="none" autoCorrect="off" required pattern="[a-z0-9_]{3,24}" minLength={3} maxLength={24} defaultValue={user.handle}/></label><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><button className="solid" disabled={busy}>Save username</button></form><form className="fields" onSubmit={event=>void save(event,'password')}><h3>Password</h3><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength={8} maxLength={128} required/></label><button className="solid" disabled={busy}>Change password</button></form><section><h3>Agent chat</h3><p>Clear your agent messages, searchable history and saved agent context. Active chat tasks will stop.</p><button className="solid" disabled={busy} onClick={()=>setConfirm(true)}>Clear chat</button>{confirm&&<DeleteConfirmation title="Clear this conversation?" detail="Your agent messages and saved context will be deleted. This can’t be undone." confirmLabel="Clear chat" pendingLabel="Clearing…" busy={busy} onCancel={()=>setConfirm(false)} onConfirm={()=>{setBusy(true);setError('');return post('/account/clear-chat',{confirmed:true}).then(cleared).then(()=>{setConfirm(false);setNotice('Agent chat cleared.');}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}/>}</section>{notice&&<p role="status">{notice}</p>}{error&&<p role="status" className="error">{error}</p>}</div>;
}
