import {useEffect,useState} from 'react';
import {X} from '@phosphor-icons/react';
import {operation,errorText} from './api';
import {useRecordRefresh} from './useRecordRefresh';
import type {MemoryNote,MemoryPressure} from '../shared/agentMemory';
type NoteMetadata=Omit<MemoryNote,'content'>;
interface NotePage {items:NoteMetadata[];nextCursor:string|null;pressure:MemoryPressure}
export function AgentMemoryPanel(){
 const [tab,setTab]=useState<'instructions'|'notes'>('instructions'),[instructions,setInstructions]=useState<{text:string;revision:number}|null>(null),[draft,setDraft]=useState('');
 const [page,setPage]=useState<NotePage|null>(null),[editing,setEditing]=useState<MemoryNote|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const loadNotes=async(before?:string)=>{const next=await operation<NotePage>('agent.memory.list',{...(before?{before}:{})});setPage(old=>old&&before?{...next,items:[...old.items,...next.items]}:next);};
 useEffect(()=>{let cancelled=false;void operation<{text:string;revision:number}>('agent.instructions.get').then(value=>{if(!cancelled){setInstructions(value);setDraft(value.text);}}).catch(error=>{if(!cancelled)setError(errorText(error));});void loadNotes().catch(error=>{if(!cancelled)setError(errorText(error));});return()=>{cancelled=true;};},[]);
 useRecordRefresh(['agent_memory'],async()=>{try{await loadNotes();if(instructions&&draft===instructions.text){const next=await operation<{text:string;revision:number}>('agent.instructions.get');setInstructions(next);setDraft(next.text);}}catch(error){setError(errorText(error));}});
 const perform=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await work();}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const saveInstructions=()=>perform(async()=>{if(!instructions)return;const saved=await operation<{text:string;revision:number}>('agent.instructions.update',{text:draft,revision:instructions.revision},{confirmed:true});setInstructions(saved);setDraft(saved.text);});
 const saveNote=()=>perform(async()=>{if(!editing)return;const {key,title,content,core,sources,revision}=editing;const saved=await operation<{saved:boolean;pressure:MemoryPressure;reason?:string}>('agent.memory.save',{key,title,content,core,sources,revision});setPage(old=>old&&{...old,pressure:saved.pressure});if(!saved.saved){setError(saved.reason||'This note could not be saved.');return;}setEditing(null);await loadNotes();});
 const removeNote=()=>perform(async()=>{if(!editing?.revision)return;await operation('agent.memory.delete',{key:editing.key,revision:editing.revision});setEditing(null);await loadNotes();});
 return <><nav className="view-tabs" aria-label="Agent preferences"><button aria-pressed={tab==='instructions'} onClick={()=>setTab('instructions')}>Your instructions</button><button aria-pressed={tab==='notes'} onClick={()=>setTab('notes')}>Agent notes</button></nav>
  {tab==='instructions'?<form className="fields" onSubmit={event=>{event.preventDefault();void saveInstructions();}}><label>Your instructions<textarea value={draft} maxLength={8000} rows={8} disabled={!instructions||busy} onChange={event=>setDraft(event.target.value)}/></label><button className="solid" disabled={busy||!instructions||draft===instructions.text}>{busy?'Saving...':'Save'}</button></form>:<>
   {page&&<div className="storage-summary"><p className="storage-total">Core context: {page.pressure.coreUsed.toLocaleString()} / {page.pressure.coreLimit.toLocaleString()} estimated tokens</p><progress className="storage-meter" value={page.pressure.coreUsed} max={page.pressure.coreLimit} aria-label="Core memory used"/></div>}
   <p className="quiet small">Core notes are included in each chat turn. Other notes are read when needed.</p>
   {editing?<form className="fields" onSubmit={event=>{event.preventDefault();void saveNote();}}><label>Title<input value={editing.title} maxLength={100} onChange={event=>setEditing({...editing,title:event.target.value})}/></label><label>Note<textarea rows={7} maxLength={4000} value={editing.content} onChange={event=>setEditing({...editing,content:event.target.value})}/></label><label className="check-row"><input type="checkbox" checked={editing.core} onChange={event=>setEditing({...editing,core:event.target.checked})}/>Core</label>
    {editing.sourceStatus&&editing.sourceStatus!=='current'&&<p className="quiet small">A source changed or is no longer available. This note is left out of automatic context.</p>}
    {editing.sources.length>0&&<div className="inline-actions">{editing.sources.map((source,index)=><button className="text-link small" type="button" key={`${source.kind}:${source.id}`} onClick={()=>setEditing({...editing,sources:editing.sources.filter((_,i)=>i!==index)})} aria-label={`Remove ${source.kind} source`}>{source.kind}<X size={14}/></button>)}</div>}
    <div className="panel-actions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="solid" disabled={busy||!editing.title.trim()||!editing.content.trim()}>{busy?'Saving...':'Save'}</button>{editing.revision>0&&<button type="button" disabled={busy} onClick={()=>void removeNote()}>Delete</button>}</div>
   </form>:<><div className="settings-menu">{page?.items.map(note=><button key={note.key} disabled={busy} onClick={()=>void perform(async()=>{const result=await operation<{slot:MemoryNote}>('agent.memory.get',{key:note.key});setEditing(result.slot);})}><span>{note.title}</span><small className="quiet">{note.core?'Core':'On demand'}</small></button>)}</div><div className="panel-actions"><button onClick={()=>setEditing({key:`note_${crypto.randomUUID().replaceAll('-','')}`,title:'',content:'',core:false,sources:[],revision:0,estimatedTokens:0,updatedAt:''})}>Add note</button>{page?.nextCursor&&<button disabled={busy} onClick={()=>void perform(()=>loadNotes(page.nextCursor!))}>More notes</button>}</div></>}
  </>}{error&&<p className="error" role="alert">{error}</p>}</>;
}
