import {useEffect,useState} from 'react';
import {Plus,X} from '@phosphor-icons/react';
import {operation,errorText} from './api';
import {useRecordRefresh} from './useRecordRefresh';
import type {MemoryNote,MemoryPressure} from '../shared/agentMemory';
type NoteMetadata=Omit<MemoryNote,'content'>;
interface NotePage {items:NoteMetadata[];nextCursor:string|null;pressure:MemoryPressure}
export function AgentMemoryPanel({section='memory'}:{section?:'instructions'|'memory'}){
 const [instructions,setInstructions]=useState<{text:string;revision:number}|null>(null),[draft,setDraft]=useState('');
 const [page,setPage]=useState<NotePage|null>(null),[editing,setEditing]=useState<MemoryNote|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const loadNotes=async(before?:string)=>{const next=await operation<NotePage>('agent.memory.list',{...(before?{before}:{})});setPage(old=>old&&before?{...next,items:[...old.items,...next.items]}:next);};
 const loadInstructions=async()=>{const next=await operation<{text:string;revision:number}>('agent.instructions.get');setInstructions(next);setDraft(next.text);};
 useEffect(()=>{let cancelled=false;setError('');setEditing(null);if(section==='instructions')void operation<{text:string;revision:number}>('agent.instructions.get').then(value=>{if(!cancelled){setInstructions(value);setDraft(value.text);}}).catch(error=>{if(!cancelled)setError(errorText(error));});else void operation<NotePage>('agent.memory.list',{}).then(value=>{if(!cancelled)setPage(value);}).catch(error=>{if(!cancelled)setError(errorText(error));});return()=>{cancelled=true;};},[section]);
 useRecordRefresh(['agent_memory'],async()=>{try{if(section==='memory')await loadNotes();else if(instructions&&draft===instructions.text)await loadInstructions();}catch(error){setError(errorText(error));}});
 const perform=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await work();}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const saveInstructions=()=>perform(async()=>{if(!instructions)return;const saved=await operation<{text:string;revision:number}>('agent.instructions.update',{text:draft,revision:instructions.revision},{confirmed:true});setInstructions(saved);setDraft(saved.text);});
 const saveNote=()=>perform(async()=>{if(!editing)return;const {key,title,content,core,sources,revision}=editing;const saved=await operation<{saved:boolean;pressure:MemoryPressure;reason?:string}>('agent.memory.save',{key,title,content,core,sources:sources.map(({kind,id})=>({kind,id})),revision});setPage(old=>old&&{...old,pressure:saved.pressure});if(!saved.saved){setError(saved.reason||'This memory could not be saved.');return;}setEditing(null);await loadNotes();});
 const removeNote=()=>perform(async()=>{if(!editing?.revision)return;await operation('agent.memory.delete',{key:editing.key,revision:editing.revision});setEditing(null);await loadNotes();});
 if(section==='instructions')return <div className="agent-memory-panel"><form className="fields agent-instructions-form" onSubmit={event=>{event.preventDefault();void saveInstructions();}}><textarea aria-label="Guidance" value={draft} maxLength={8000} rows={12} disabled={!instructions||busy} onChange={event=>setDraft(event.target.value)}/><p className="quiet small">These are your standing preferences. Current requests still take priority.</p><div className="panel-actions"><button className="solid" disabled={busy||!instructions||draft===instructions.text}>{busy?'Saving...':'Save guidance'}</button></div></form>{error&&<p className="error" role="alert">{error}</p>}</div>;
 const add=()=>setEditing({key:`note_${crypto.randomUUID().replaceAll('-','')}`,title:'',content:'',core:false,sources:[],revision:0,estimatedTokens:0,updatedAt:''});
 return <div className="agent-memory-panel">
  {page?.pressure&&<div className="storage-summary"><p className="storage-total">Core context: {page.pressure.coreUsed.toLocaleString()} / {page.pressure.coreLimit.toLocaleString()} estimated tokens</p><progress className="storage-meter" value={page.pressure.coreUsed} max={page.pressure.coreLimit} aria-label="Core memory used"/></div>}
  {!editing&&<div className="agent-memory-intro"><p className="quiet small">Core memories accompany each chat turn. Other memories are read when relevant.</p><button className="solid agent-memory-add" type="button" onClick={add}><Plus size={18}/>Add memory</button></div>}
  {editing?<form className="fields agent-memory-editor" onSubmit={event=>{event.preventDefault();void saveNote();}}><label>Title<input value={editing.title} maxLength={100} onChange={event=>setEditing({...editing,title:event.target.value})}/></label><label>Memory<textarea rows={9} maxLength={4000} value={editing.content} onChange={event=>setEditing({...editing,content:event.target.value})}/></label><label className="check-label"><input type="checkbox" checked={editing.core} onChange={event=>setEditing({...editing,core:event.target.checked})}/>Include in every chat</label>
   {editing.sourceStatus&&editing.sourceStatus!=='current'&&<p className="quiet small">A source changed or is no longer available. This memory is left out of automatic context.</p>}
   {editing.sources.length>0&&<div className="memory-source-chips">{editing.sources.map((source,index)=><button type="button" key={`${source.kind}:${source.id}`} onClick={()=>setEditing({...editing,sources:editing.sources.filter((_,i)=>i!==index)})} aria-label={`Remove ${source.date||'source'} source`}>{source.date||'source'}<X size={14}/></button>)}</div>}
   <div className="panel-actions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="solid" disabled={busy||!editing.title.trim()||!editing.content.trim()}>{busy?'Saving...':'Save memory'}</button>{editing.revision>0&&<button type="button" disabled={busy} onClick={()=>void removeNote()}>Delete</button>}</div>
  </form>:<><div className="settings-menu agent-memory-list">{page?.items.map(note=><button type="button" key={note.key} disabled={busy} onClick={()=>void perform(async()=>{const result=await operation<{slot:MemoryNote}>('agent.memory.get',{key:note.key});setEditing(result.slot);})}><span><strong>{note.title}</strong><small className="quiet">{note.core?'Every chat':'On demand'}</small></span><time className="quiet small" dateTime={note.updatedAt}>{note.updatedAt.slice(0,10)}</time></button>)}</div>{page&&!page.items.length&&<p className="quiet">No agent memories yet.</p>}{page?.nextCursor&&<button className="text-link" disabled={busy} onClick={()=>void perform(()=>loadNotes(page.nextCursor!))}>More memories</button>}</>}
  {error&&<p className="error" role="alert">{error}</p>}
 </div>;
}
