import {InlinePerson} from './InlinePerson';
import {useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowUp,ArrowDown,CircleNotch} from '@phosphor-icons/react';
import type {Profile} from '../shared/types';
import type {Destination} from '../shared/navigation';
import {DEFAULT_DINNER_START,addCookingDays,dateInZone,mealThumbnail,type DinderDeck,type DinderMatch,type DinderMessage,type DinderPreferences,type Meal,type MealCard} from '../shared/dinder';
import {operation,errorText,ApiError} from './api';
import {NavLink} from './NavLink';
import {PreservedPanels} from './PreservedPanels';
import {useVirtualizer} from '@tanstack/react-virtual';
import {observeVisibleElementRect,observeVisibleElementOffset} from './virtualScroll';
import {usePanelVisible,usePanelLoading} from './PanelReadiness';
import {useRecordRefresh} from './useRecordRefresh';
import {useHorizontalSwipe} from './useHorizontalSwipe';
import {captureHistoryAnchor,restoreHistoryAnchor,OlderMessages,useTopPagination} from './ChatHistory';
import {directMessageLayout,directMessageTimeLabel} from './directMessageGrouping';
import {CollapsibleMessage} from './CollapsibleMessage';
import {LinkPreviews} from './LinkPreview';
import {TransientError} from './TransientError';
import './dinder.css';

type Navigate=(destination:Destination)=>void;
type DinderSection='swipe'|'preparing'|'chat'|'calendar'|'settings'|'about';
type MessagePage={items:DinderMessage[];nextCursor:string|null;match:DinderMatch};
type CalendarItem={date:string;matchId:string;mealName:string;imageUrl:string;personName:string;startAt:string};
const deviceZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
const clock=(at:string,zone?:string)=>new Date(at).toLocaleTimeString(undefined,{...(zone?{timeZone:zone}:{}),hour:'numeric',minute:'2-digit'});
const dayLabel=(date:string)=>new Date(`${date}T12:00:00Z`).toLocaleDateString(undefined,{timeZone:'UTC',weekday:'long',month:'short',day:'numeric'});
const thumbnail=mealThumbnail;
const decks=new Map<string,DinderDeck>();
function remember(userId:string,deck:DinderDeck){decks.delete(userId);decks.set(userId,deck);while(decks.size>6)decks.delete(decks.keys().next().value!);}

/** Dinder's name / square photo / recipe link, retained in both swipe and match views. */
function RecipeCard({meal,leaving,lazy=false}:{meal:MealCard;leaving?:boolean;lazy?:boolean}){
 return <article className="dinder-card" inert={leaving||undefined}>
  <a className="dinder-recipe-name" href={meal.sourceUrl} target="_blank" rel="noopener noreferrer" title={meal.name}>{meal.name}</a>
  <a className="dinder-recipe-photo" href={meal.sourceUrl} target="_blank" rel="noopener noreferrer" draggable={false}><img src={thumbnail(meal.imageUrl)} alt={meal.name} draggable={false} loading={lazy?'lazy':undefined} decoding="async" onError={event=>{if(event.currentTarget.src!==meal.imageUrl)event.currentTarget.src=meal.imageUrl;}}/></a>
  <div className="dinder-card-footer"><span className="quiet small" title={meal.category}>{meal.category}</span><a className="text-link dinder-source" href={meal.sourceUrl} target="_blank" rel="noopener noreferrer">See recipe</a></div>
 </article>;
}
function Sections({active,select,matchId}:{active:DinderSection;select:(section:DinderSection)=>void;matchId?:string}){
 const items:{key:DinderSection;label:string;to:Destination}[]=matchId?[{key:'preparing',label:'Preparing',to:{view:'dinder',resourceId:matchId}},{key:'chat',label:'Chat',to:{view:'dinder',resourceId:matchId,dinderTab:'chat'}}]:[{key:'swipe',label:'Swipe',to:{view:'dinder'}}];
 items.push({key:'calendar',label:'Calendar',to:{view:'dinder',resourceId:'calendar'}},{key:'settings',label:'Settings',to:{view:'dinder',resourceId:'settings'}},{key:'about',label:'About',to:{view:'dinder',resourceId:'about'}});
 return <nav className="panel-actions dinder-nav" aria-label="Dinder sections">{items.map(item=><NavLink className={active===item.key?'solid':undefined} key={item.key} to={item.to} navigate={()=>select(item.key)} aria-current={active===item.key?'page':undefined}>{item.label}</NavLink>)}</nav>;
}

function Settings({user,navigate}:{user:Profile;navigate:Navigate}){
 const visible=usePanelVisible(),[preferences,setPreferences]=useState<DinderPreferences|null>(decks.get(user.id)?.preferences||null),[time,setTime]=useState(DEFAULT_DINNER_START),[carry,setCarry]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const edited=useRef(false),intent=useRef<{signature:string;key:string}|null>(null);
 useEffect(()=>{if(!visible)return;let cancelled=false;void operation<{preferences:DinderPreferences}>('dinder.preferences',{timeZone:deviceZone()},{dedupe:true}).then(({preferences})=>{if(cancelled)return;setPreferences(preferences);if(!edited.current){setTime(preferences.startTime);setCarry(preferences.carrySwipes);}}).catch(cause=>{if(!cancelled)setError(errorText(cause));});return()=>{cancelled=true;};},[visible]);
 usePanelLoading(visible&&!preferences&&!error);
 const save=async(event:FormEvent)=>{event.preventDefault();if(busy)return;const input={startTime:time,timeZone:deviceZone(),carrySwipes:carry},signature=JSON.stringify(input);if(intent.current?.signature!==signature)intent.current={signature,key:crypto.randomUUID()};setBusy(true);setError('');try{await operation('dinder.preferences_update',input,{confirmed:true,key:intent.current.key});decks.delete(user.id);intent.current=null;edited.current=false;navigate({view:'dinder'});}catch(cause){setError(errorText(cause));}finally{setBusy(false);}};
 return <form className="fields dinder-settings" onSubmit={save}><label>I want to start making dinner at<input type="time" value={time} required onChange={event=>{edited.current=true;setTime(event.target.value);}}/></label><p className="quiet small">Times use your device’s timezone automatically.</p><label className="check-label"><input type="checkbox" checked={carry} onChange={event=>{edited.current=true;setCarry(event.target.checked);}}/>Carry swipes over to the next day</label><p className="quiet small">Reuse recipes you’ve liked but haven’t matched on.</p><div className="dinder-setting-actions"><button className="solid" disabled={busy||!time}>Save</button><NavLink className="text-link" to={{view:'dinder'}} navigate={navigate}>Cancel</NavLink></div>{error&&<TransientError className="error" role="alert">{error}</TransientError>}</form>;
}

function Swipe({user,navigate,changed}:{user:Profile;navigate:Navigate;changed:(match:DinderMatch|null)=>void}){
 const visible=usePanelVisible(),[deck,setDeck]=useState<DinderDeck|null>(decks.get(user.id)||null),[error,setError]=useState(''),[status,setStatus]=useState(''),[pending,setPending]=useState(0),[back,setBack]=useState<Meal|null>(null),[busyBack,setBusyBack]=useState(false),[exit,setExit]=useState<{meal:Meal;direction:number}|null>(null),[drag,setDrag]=useState(0);
 const latest=useRef(deck);latest.current=deck;const generation=useRef(0),disposed=useRef(false),running=useRef(false),failed=useRef(false),cursor=useRef<string|undefined>(undefined),point=useRef<{x:number;y:number}|null>(null);
 type Choice={meal:Meal;liked:boolean;desiredAt:string;revision:number;timeZone:string;key:string};
 const queue=useRef<Choice[]>([]);
 const update=(next:DinderDeck)=>{latest.current=next;setDeck(next);remember(user.id,next);};
 const load=async(before?:string,append=false)=>{const ticket=++generation.current;try{const next=await operation<DinderDeck>('dinder.deck',{timeZone:deviceZone(),limit:10,...(before?{before}:{})},{dedupe:true});if(disposed.current||ticket!==generation.current)return;cursor.current=before;const previous=latest.current;update(append&&previous?{...next,items:[...new Map([...previous.items,...next.items].map(meal=>[meal.id,meal])).values()]}:next);setError('');}catch(cause){if(!disposed.current&&ticket===generation.current)setError(errorText(cause));}};
 useEffect(()=>{disposed.current=false;return()=>{disposed.current=true;generation.current++;queue.current=[];};},[]);
 useEffect(()=>{if(visible&&!queue.current.length)void load(cursor.current);},[visible]);
 useRecordRefresh(['dinder','people'],()=>{if(visible&&!queue.current.length&&!running.current)void load(cursor.current);});
 usePanelLoading(visible&&!deck&&!error);
 useEffect(()=>{if(visible&&deck)changed(deck.match);},[visible,deck?.match]);
 useEffect(()=>{if(!deck||!visible)return;const timer=setTimeout(()=>{cursor.current=undefined;setBack(null);void load();},Math.max(0,Date.parse(deck.plan.cutoffAt)-Date.now()+50));return()=>clearTimeout(timer);},[visible,deck?.plan.cutoffAt]);
 useEffect(()=>{if(!deck||!visible)return;const images=deck.items.slice(1,3).map(meal=>{const image=new Image();image.src=thumbnail(meal.imageUrl);return image;});return()=>{images.forEach(image=>{image.onload=null;});};},[visible,deck?.items[0]?.id]);
 useEffect(()=>{if(!exit)return;const timer=setTimeout(()=>setExit(null),160);return()=>clearTimeout(timer);},[exit]);
 const flush=async()=>{if(running.current||disposed.current)return;running.current=true;failed.current=false;while(queue.current.length&&!disposed.current){const choice=queue.current[0];try{const current=latest.current;if(choice.revision===0&&current?.preferences.revision===1)choice.revision=1;const revision=choice.revision;const result=await operation<{preferences:DinderPreferences;match:DinderMatch|null}>('dinder.swipe',{mealId:choice.meal.id,liked:choice.liked,desiredAt:choice.desiredAt,preferencesRevision:revision,timeZone:choice.timeZone},{confirmed:true,key:choice.key});if(disposed.current)break;queue.current.shift();setPending(queue.current.length);if(latest.current)update({...latest.current,preferences:result.preferences.revision>=latest.current.preferences.revision?result.preferences:latest.current.preferences,...(result.match?{match:result.match}:{})});if(result.match){queue.current=[];setPending(0);setBack(null);break;}setStatus(choice.liked?'Looking for someone who picked the same recipe.':'');}catch(cause){if(disposed.current)break;failed.current=true;setError(errorText(cause));if(cause instanceof ApiError&&cause.code==='dinder_slot_changed'){queue.current=[];setPending(0);setBack(null);cursor.current=undefined;void load();}break;}}running.current=false;};
 const swipe=(liked:boolean)=>{const current=latest.current,meal=current?.items[0];if(!current||!meal||current.match||queue.current.length>=8||failed.current||busyBack)return;setError('');setBack(meal);setExit({meal,direction:liked?1:-1});setDrag(0);queue.current.push({meal,liked,desiredAt:current.plan.desiredAt,revision:current.preferences.revision,timeZone:current.preferences.timeZone,key:crypto.randomUUID()});setPending(queue.current.length);const items=current.items.slice(1);update({...current,items});if(items.length<=2&&current.nextCursor)void load(current.nextCursor,true);void flush();};
 const gesture=useHorizontalSwipe({active:visible&&!deck?.match,allowMouse:true,canSwipe:()=>queue.current.length<8&&!failed.current&&!busyBack,swipe:direction=>swipe(direction===-1)});
 const undo=async()=>{const current=latest.current;if(!back||!current||queue.current.length||busyBack)return;setBusyBack(true);setError('');try{const result=await operation<{meal:Meal;preferences:DinderPreferences}>('dinder.back',{mealId:back.id,desiredAt:current.plan.desiredAt,preferencesRevision:current.preferences.revision,timeZone:current.preferences.timeZone});update({...current,preferences:result.preferences,items:[result.meal,...current.items.filter(meal=>meal.id!==result.meal.id)]});setBack(null);setStatus('');}catch(cause){setError(errorText(cause));}finally{setBusyBack(false);}};
 const filter=async(excludedCategories:string[])=>{const current=latest.current;if(!current||pending)return;setError('');try{await operation('dinder.preferences_update',{startTime:current.preferences.startTime,timeZone:current.preferences.timeZone,carrySwipes:current.preferences.carrySwipes,excludedCategories},{confirmed:true});cursor.current=undefined;setBack(null);await load();}catch(cause){setError(errorText(cause));}};
 if(deck?.match)return <MatchView user={user} matchId={deck.match.id} initial={deck.match} navigate={navigate} changed={changed}/>;
 if(!deck)return error?<><TransientError className="error" role="alert">{error}</TransientError><button className="text-link" onClick={()=>void load()}>Retry</button></>:null;
 const meal=deck.items[0],disabled=pending>=8||failed.current||busyBack;
 const actions=(placement:string)=><div className={`panel-actions dinder-actions ${placement}`}>{back&&<button className="dinder-back" disabled={pending>0||busyBack} aria-label="Previous recipe, undo last swipe" onClick={()=>void undo()}><ArrowLeft size={20}/></button>}<button disabled={disabled||!meal} onClick={()=>swipe(false)}>NO</button><button className="solid" disabled={disabled||!meal} onClick={()=>swipe(true)}>YES</button></div>;
 return <div className="dinder-swipe"><p className="dinder-day quiet small">{dayLabel(deck.plan.date)} · Start cooking at {clock(deck.plan.desiredAt,deck.preferences.timeZone)}</p>{meal?<>{actions('dinder-above')}<div className="dinder-card-stage" {...gesture} onPointerDown={event=>{gesture.onPointerDown(event);point.current={x:event.clientX,y:event.clientY};}} onPointerMove={event=>{gesture.onPointerMove(event);if(!point.current||event.pointerType==='mouse'&&event.buttons!==1)return;const x=event.clientX-point.current.x,y=event.clientY-point.current.y;if(Math.abs(x)>Math.abs(y)*1.25)setDrag(x);}} onPointerUp={event=>{gesture.onPointerUp(event);point.current=null;setDrag(0);}} onPointerCancel={event=>{gesture.onPointerCancel(event);point.current=null;setDrag(0);}}><div className="dinder-live-card" style={{transform:drag?`translateX(${drag}px)`:undefined}}><RecipeCard meal={meal}/></div>{exit&&<div className="dinder-leaving" key={exit.meal.id} style={{'--dinder-direction':exit.direction} as React.CSSProperties}><RecipeCard meal={exit.meal} leaving/></div>}</div>{actions('dinder-below')}<div className="panel-actions dinder-category-actions"><button disabled={pending>0} onClick={()=>void filter([...new Set([...deck.preferences.excludedCategories,meal.category])])}>Exclude {meal.category}</button><label className="dinder-only">Only show <select aria-label="Only show recipe category" disabled={pending>0} value={deck.preferences.excludedCategories.length===deck.categories.length-1?meal.category:''} onChange={event=>void filter(event.target.value?deck.categories.filter(category=>category!==event.target.value):[])}><option value="">All</option>{deck.categories.map(category=><option key={category}>{category}</option>)}</select></label>{deck.preferences.excludedCategories.length>0&&<button disabled={pending>0} onClick={()=>void filter([])}>Reset</button>}</div></>:<div className="dinder-empty"><p className="quiet">{deck.catalogReady?'No more recipes in this window. Your YES swipes are still looking for a match.':'Loading recipes…'}</p>{deck.nextCursor?<button className="text-link" onClick={()=>void load(deck.nextCursor!)}>More recipes</button>:deck.preferences.excludedCategories.length>0&&<button className="text-link" onClick={()=>void filter([])}>Reset filters</button>}</div>}{status&&<p className="quiet small" role="status">{status}</p>}{error&&<div><TransientError className="error" role="alert">{error}</TransientError>{failed.current&&queue.current.length>0&&<button className="text-link" onClick={()=>{setError('');void flush();}}>Retry saving swipe</button>}</div>}</div>;
}

function Calendar({user,navigate}:{user:Profile;navigate:Navigate}){
 const visible=usePanelVisible(),[anchor]=useState(()=>dateInZone(deviceZone())),[items,setItems]=useState<CalendarItem[]|null>(null),[error,setError]=useState(''),scroll=useRef<HTMLDivElement>(null),grid=useRef<HTMLDivElement>(null),generation=useRef(0),[width,setWidth]=useState(440),[gap,setGap]=useState(4);
 const {start,end,weeks}=useMemo(()=>{
  const start=addCookingDays(anchor,-729),end=addCookingDays(anchor,14),first=Date.parse(`${start}T12:00:00Z`),last=Date.parse(`${end}T12:00:00Z`),sunday=last-new Date(last).getUTCDay()*86400000,oldest=first-new Date(first).getUTCDay()*86400000;
  return {start,end,weeks:Array.from({length:Math.round((sunday-oldest)/604800000)+1},(_,index)=>Array.from({length:7},(_,day)=>{const at=sunday-index*604800000+day*86400000,date=new Date(at).toISOString().slice(0,10);return date<start||date>end?null:{date,at};}))};
 },[anchor]);
 const today=dateInZone(deviceZone()),byDate=useMemo(()=>new Map(items?.map(item=>[item.date,item])),[items]);
 const load=async()=>{const ticket=++generation.current;try{const result=await operation<{items:CalendarItem[]}>('dinder.calendar',{from:start,to:end},{dedupe:true});if(ticket===generation.current){setItems(result.items);setError('');}}catch(cause){if(ticket===generation.current)setError(errorText(cause));}};
 useEffect(()=>()=>{generation.current++;},[]);useEffect(()=>{if(visible&&!items)void load();},[visible]);useRecordRefresh(['dinder','people'],()=>{if(visible)void load();});
 useLayoutEffect(()=>{const node=grid.current;if(!node)return;const measure=()=>{if(node.clientWidth){setWidth(node.clientWidth);setGap(parseFloat(getComputedStyle(node).columnGap)||0);}};measure();const observer=new ResizeObserver(measure);observer.observe(node);return()=>observer.disconnect();},[]);
 const estimateSize=useCallback(()=>Math.max(1,(width-gap*6)/7),[width,gap]),getScrollElement=useCallback(()=>scroll.current,[]),getItemKey=useCallback((index:number)=>weeks[index].find(day=>day)?.date||index,[weeks]);
 const virtual=useVirtualizer({count:weeks.length,getScrollElement,getItemKey,estimateSize,gap,overscan:3,initialRect:{width:440,height:800},observeElementRect:observeVisibleElementRect,observeElementOffset:observeVisibleElementOffset});
 useLayoutEffect(()=>virtual.measure(),[width,gap,virtual]);
 const virtualRows=virtual.getVirtualItems(),cells=useMemo(()=> <div className="dinder-calendar-grid" ref={grid} style={{height:virtual.getTotalSize()}}>
    {virtualRows.map(row=><div className="dinder-calendar-week" key={row.key} data-index={row.index} style={{height:row.size,transform:`translateY(${row.start}px)`}}>{weeks[row.index].map((value,index)=>{
     if(!value)return <span key={`blank:${index}`}/>;
     const {date,at}=value,item=byDate.get(date),day=new Date(at);
     const content=<>
      <time dateTime={date}>{day.getUTCDate()}
       {day.getUTCDate()===1&&<small>{day.toLocaleDateString(undefined,{timeZone:'UTC',month:'short'})}{day.getUTCMonth()===0?` ${day.getUTCFullYear()}`:''}</small>}
      </time>
      {item&&<><img src={thumbnail(item.imageUrl)} alt="" loading="lazy" decoding="async"/><span>{item.personName}</span></>}
     </>;
     return item
      ?<NavLink className="dinder-calendar-day has-meal" key={date} to={{view:'dinder',resourceId:item.matchId}} navigate={navigate} title={`${dayLabel(date)}: ${item.mealName} with ${item.personName}`}>{content}</NavLink>
      :date===today?<NavLink className="dinder-calendar-day" key={date} data-today="true" to={{view:'dinder'}} navigate={navigate} aria-label="Today, return to Swipe">{content}</NavLink>:<div className="dinder-calendar-day" key={date}>{content}</div>;
    })}</div>)}
   </div>,[virtualRows,weeks,byDate,today,navigate,virtual]);
 return <div className="dinder-calendar">
  <div className="dinder-calendar-scroll" ref={scroll} aria-busy={!items&&!error}>{cells}
  </div>
  {!items&&!error&&<CircleNotch className="spin dinder-calendar-loading" size={18} aria-label="Loading meal matches"/>}
  {error&&<TransientError className="error" role="alert">{error}</TransientError>}
 </div>;
}

function MealMessages({user,match,changed}:{user:Profile;match:DinderMatch;changed(match:DinderMatch):void}){
 const visible=usePanelVisible(),[page,setPage]=useState<MessagePage|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[olderBusy,setOlderBusy]=useState(false),[olderError,setOlderError]=useState(''),[windowed,setWindowed]=useState(false),[away,setAway]=useState(false);
 const scroll=useRef<HTMLDivElement>(null),generation=useRef(0),following=useRef(true),initial=useRef(true),anchor=useRef<ReturnType<typeof captureHistoryAnchor>|null>(null),intent=useRef<{text:string;key:string}|null>(null),read=useRef('');
 const merge=(a:DinderMessage[],b:DinderMessage[],older=false)=>{const all=[...new Map([...a,...b].map(message=>[message.id,message])).values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));return older?all.slice(-600):all.slice(0,600);};
 const load=async(latest=false)=>{const ticket=++generation.current;try{if(windowed&&!latest){const current=await operation<DinderMatch>('dinder.get',{matchId:match.id});if(ticket===generation.current)changed(current);return;}const next=await operation<MessagePage>('dinder.messages',{matchId:match.id,limit:30},{dedupe:true});if(ticket===generation.current){changed(next.match);setPage(previous=>!latest&&previous?{...next,items:merge(previous.items,next.items),nextCursor:previous.items.length>30?previous.nextCursor:next.nextCursor}:next);if(latest){setWindowed(false);following.current=true;initial.current=true;setAway(false);}setError('');}}catch(cause){if(ticket===generation.current)setError(errorText(cause));}};
 useEffect(()=>{if(visible)void load();return()=>{generation.current++;};},[visible]);useRecordRefresh(['dinder','people'],()=>{if(visible)void load();});
 useLayoutEffect(()=>{if(!visible||!page||!scroll.current)return;if(anchor.current){restoreHistoryAnchor(scroll.current,anchor.current);anchor.current=null;}else if(initial.current||following.current){scroll.current.scrollTop=scroll.current.scrollHeight;initial.current=false;}},[visible,page?.items]);
 const markRead=()=>{if(!visible||!page||document.hidden)return;const latest=following.current&&!windowed?page.items[0]:undefined,key=`${match.revision}:${latest?.id||''}`;if(read.current===key)return;read.current=key;void operation('dinder.mark_read',{matchId:match.id,...(latest?{messageId:latest.id}:{})}).catch(()=>{read.current='';});};
 useEffect(markRead,[visible,page?.items[0]?.id,match.revision,windowed]);
 const older=async()=>{if(!page?.nextCursor||olderBusy||!scroll.current)return;setOlderBusy(true);setOlderError('');const ticket=generation.current;anchor.current=captureHistoryAnchor(scroll.current);following.current=false;try{const next=await operation<MessagePage>('dinder.messages',{matchId:match.id,before:page.nextCursor,limit:30});if(ticket===generation.current){if(page.items.length+next.items.length>600)setWindowed(true);setPage(previous=>previous?{...next,items:merge(previous.items,next.items,true)}:next);setAway(true);}}catch(cause){anchor.current=null;setOlderError(errorText(cause));}finally{setOlderBusy(false);}};
 useTopPagination(scroll,{enabled:visible&&!olderBusy&&!olderError,hasMore:Boolean(page?.nextCursor),count:page?.items.length||0,scope:match.id,load:older});
 const send=async(event?:FormEvent)=>{event?.preventDefault();const raw=text,value=raw.trim();if(!value||busy||match.status!=='matched')return;if(intent.current?.text!==value)intent.current={text:value,key:crypto.randomUUID()};const sending=intent.current;setBusy(true);setError('');try{const message=await operation<DinderMessage>('dinder.message_send',{matchId:match.id,text:value,clientId:sending.key},{key:sending.key});setText(current=>current===raw?'':current);intent.current=null;following.current=true;if(windowed)await load(true);else setPage(previous=>previous?{...previous,items:merge(previous.items,[message])}:previous);setAway(false);}catch(cause){setError(errorText(cause));}finally{setBusy(false);}};
 const timeline=[...(page?.items||[])].reverse(),layout=directMessageLayout(timeline);
 return <div className="dinder-meal-messages"><div className="direct-message-scroll"><div className="direct-messages" ref={scroll} onScroll={()=>{const node=scroll.current!;following.current=!windowed&&node.scrollHeight-node.clientHeight-node.scrollTop<24;setAway(!following.current);markRead();}}><div className="direct-message-content"><OlderMessages hasMore={Boolean(page?.nextCursor)} loading={olderBusy} error={olderError} retry={()=>void older()}/>{timeline.map((message,index)=><div key={message.id}>{layout[index].showTime&&<time className="message-time-separator" dateTime={message.createdAt}>{directMessageTimeLabel(message.createdAt)}</time>}<article className={`message ${message.fromId===user.id?'user':'peer'} ${layout[index].groupWithPrevious?'dm-group-with-previous':''}`} data-message-id={message.id}><div className="bubble"><CollapsibleMessage text={message.text} assistant={false} social scrollRef={scroll}/></div><LinkPreviews text={message.text} simple/></article></div>)}</div></div>{(away||windowed)&&<button className="latest-chat latest-dm" aria-label="Latest meal messages" onClick={()=>{if(windowed)void load(true);else if(scroll.current){following.current=true;scroll.current.scrollTop=scroll.current.scrollHeight;setAway(false);markRead();}}}><ArrowDown size={22}/></button>}</div>{match.status==='matched'&&<form className="message-compose" onSubmit={send}><label className="sr-only" htmlFor={`meal-${match.id}`}>Message about this recipe</label><textarea id={`meal-${match.id}`} rows={2} maxLength={2000} value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();void send();}}}/><button className="solid" aria-label="Send meal message" disabled={busy||!text.trim()}><ArrowUp size={20} weight="bold"/></button></form>}{error&&<TransientError className="error" role="alert">{error}</TransientError>}</div>;
}

function MatchView({user,matchId,initial,navigate,chat=false,changed}:{user:Profile;matchId:string;initial?:DinderMatch;navigate:Navigate;chat?:boolean;changed:(match:DinderMatch|null)=>void}){
 const visible=usePanelVisible(),[match,setMatch]=useState<DinderMatch|null>(initial||null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),generation=useRef(0),intent=useRef<{signature:string;key:string}|null>(null);
 const load=async()=>{const ticket=++generation.current;try{const current=await operation<DinderMatch>('dinder.get',{matchId},{dedupe:true});if(ticket===generation.current){setMatch(current);setError('');}}catch(cause){if(ticket===generation.current){if(cause instanceof ApiError&&[403,404].includes(cause.status))setMatch(null);setError(errorText(cause));}}};
 useEffect(()=>{if(visible&&!initial)void load();return()=>{generation.current++;};},[visible]);useRecordRefresh(['dinder','people'],()=>{if(visible)void load();});usePanelLoading(visible&&!match&&!error);
 useEffect(()=>{if(visible&&match)changed(match);},[visible,match]);
 const act=async(name:'dinder.cancel'|'dinder.postpone'|'dinder.again',vote?:boolean)=>{if(!match||busy)return;const input={matchId,revision:match.revision,...(vote===undefined?{}:{vote})},signature=JSON.stringify([name,input]);if(intent.current?.signature!==signature)intent.current={signature,key:crypto.randomUUID()};setBusy(true);setError('');try{const next=await operation<DinderMatch>(name,input,{confirmed:true,key:intent.current.key});intent.current=null;setMatch(next);setConfirm(false);if(name==='dinder.cancel'){decks.delete(user.id);navigate({view:'dinder'});}}catch(cause){setError(errorText(cause));void load();}finally{setBusy(false);}};
 if(!match)return error?<TransientError className="error" role="alert">{error}</TransientError>:null;
 const person=match.people.find(person=>person.id!==user.id)!,zone=match.plans.find(plan=>plan.userId===user.id)!.timeZone,again=(match.againVotes||[]).includes(user.id),postpone=match.postponeVotes.includes(user.id);
 if(chat)return <div className="dinder-chat-screen"><div className="dinder-chat-caption"><InlinePerson person={person} navigate={navigate}/><a className="text-link dinder-chat-recipe" href={match.meal.sourceUrl} target="_blank" rel="noopener noreferrer">{match.meal.name}</a></div><MealMessages user={user} match={match} changed={setMatch}/>{error&&<TransientError className="error" role="alert">{error}</TransientError>}</div>;
 return <div className="dinder-match"><div className="dinder-planning"><span>{match.status==='cancelled'?'Made plans with':'Preparing with'} <InlinePerson person={person} navigate={navigate}/></span><span className="quiet small">{dayLabel(match.date)} · {clock(match.startAt,zone)}</span></div><RecipeCard meal={match.meal}/>{match.status==='matched'&&<div className="dinder-match-votes">{match.nextMatchId?<NavLink className="text-link" to={{view:'dinder',resourceId:match.nextMatchId}} navigate={navigate}>Making this again next week →</NavLink>:<div className="dinder-vote"><span>Make this again next week?</span><div className="panel-actions"><button className={again?'solid':undefined} disabled={busy} aria-pressed={again} onClick={()=>void act('dinder.again',true)}>YES</button><button disabled={busy} aria-pressed={!again} onClick={()=>void act('dinder.again',false)}>NO</button></div></div>}<div className="dinder-vote"><span>Postpone until tomorrow?</span><div className="panel-actions"><button className={postpone?'solid':undefined} disabled={busy} aria-pressed={postpone} onClick={()=>void act('dinder.postpone',true)}>YES</button><button disabled={busy} aria-pressed={!postpone} onClick={()=>void act('dinder.postpone',false)}>NO</button></div></div><button className="text-link" onClick={()=>setConfirm(!confirm)}>Unmatch</button>{confirm&&<div className="fields"><p>Unmatch? Your messages will be kept.</p><button className="solid" disabled={busy} onClick={()=>void act('dinder.cancel')}>Unmatch</button><button className="text-link" onClick={()=>setConfirm(false)}>Cancel</button></div>}</div>}{match.status==='cancelled'&&<p className="quiet small">This match has ended. Your messages are kept.</p>}{error&&<TransientError className="error" role="alert">{error}</TransientError>}</div>;
}

function About(){return <section className="dinder-about"><p><strong>Tinder, but for making dinner.</strong></p><p>Swipe on recipes. When you and someone else pick the same one, you match and make it that same evening, virtually.</p><p>Dinder is not (intentionally) for dating. It’s about finding someone else who wants to cook what you want to cook. A cooking buddy!</p><p className="quiet small">Recipes from <a href="https://www.themealdb.com" target="_blank" rel="noopener noreferrer">TheMealDB</a> and <a href="https://based.cooking" target="_blank" rel="noopener noreferrer">Based Cooking</a> (<a href="https://github.com/LukeSmithxyz/based.cooking/blob/master/LICENSE.md" target="_blank" rel="noopener noreferrer">public domain</a>).</p></section>;}

function Catalog(){
 const visible=usePanelVisible(),[items,setItems]=useState<MealCard[]>([]),[total,setTotal]=useState<number|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[width,setWidth]=useState(600),[margin,setMargin]=useState(0);
 const grid=useRef<HTMLDivElement>(null),scroll=useRef<HTMLElement|null>(null),cursor=useRef<string|undefined>(undefined),complete=useRef(false),loaded=useRef<MealCard[]>([]);
 useEffect(()=>{if(!visible||complete.current)return;let cancelled=false;setLoading(true);setError('');void(async()=>{try{while(!cancelled&&loaded.current.length<20000){const before=cursor.current,page=await operation<{items:MealCard[];nextCursor:string|null;total:number}>('dinder.catalog',{limit:100,...(before?{before}:{})},{dedupe:true});if(cancelled)return;loaded.current=[...new Map([...loaded.current,...page.items].map(meal=>[meal.id,meal])).values()];setItems(loaded.current);setTotal(page.total);cursor.current=page.nextCursor||undefined;if(!page.nextCursor){complete.current=true;break;}if(page.nextCursor===before)throw Error('Could not load the next recipes.');}}catch(cause){if(!cancelled)setError(errorText(cause));}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[visible,retry]);
 usePanelLoading(visible&&loading&&!items.length&&!error);
 useLayoutEffect(()=>{const node=grid.current,host=node?.closest<HTMLElement>('.mode-pages > .composer-view')||node?.closest<HTMLElement>('.composer-surface-content');if(!node||!host)return;scroll.current=host;const measure=()=>{if(!visible||!node.clientWidth)return;setWidth(node.clientWidth);setMargin(node.getBoundingClientRect().top-host.getBoundingClientRect().top+host.scrollTop);};measure();const observer=new ResizeObserver(measure);observer.observe(node);return()=>observer.disconnect();},[visible]);
 const columns=Math.max(1,Math.floor((width+12)/182)),virtual=useVirtualizer({count:Math.ceil(items.length/columns),getScrollElement:()=>scroll.current,estimateSize:()=>width/columns+90,getItemKey:index=>items[index*columns]?.id||index,scrollMargin:margin,overscan:2,gap:12,enabled:visible});
 return <section className="dinder-catalog"><p className="quiet small" role="status">{total===null?'Loading recipes…':loading?`${items.length} / ${total} recipes`:`${total} recipes`}</p>{error&&<div><TransientError className="error" role="alert">{error}</TransientError><button className="text-link" onClick={()=>setRetry(value=>value+1)}>Retry</button></div>}<div className="dinder-catalog-grid" ref={grid} data-recipe-count={items.length} style={{height:virtual.getTotalSize()}}>{virtual.getVirtualItems().map(row=><div className="dinder-catalog-row" key={row.key} data-index={row.index} ref={virtual.measureElement} style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`,transform:`translateY(${row.start-margin}px)`}}>{items.slice(row.index*columns,(row.index+1)*columns).map(meal=><RecipeCard key={meal.id} meal={meal} lazy/>)}</div>)}</div>{!loading&&!error&&!items.length&&<p className="quiet">The recipe library is loading.</p>}{items.length>=20000&&!complete.current&&<p className="quiet small">Showing the first 20,000 recipes.</p>}</section>;
}

export function DinderPanel({user,resourceId,navigate,dinderTab}:{user:Profile;resourceId?:string;navigate:Navigate;dinderTab?:'chat'}){
 const entryTab:DinderSection=resourceId==='calendar'||resourceId==='matches'?'calendar':resourceId==='settings'||resourceId==='preferences'?'settings':resourceId==='about'?'about':resourceId?(dinderTab==='chat'?'chat':'preparing'):'swipe';
 const entryMatchId=entryTab==='preparing'||entryTab==='chat'?resourceId:decks.get(user.id)?.match?.id;
 const [tab,setTab]=useState<DinderSection>(entryTab),[matchId,setMatchId]=useState(entryMatchId),[swipeEpoch,setSwipeEpoch]=useState(0);
 useEffect(()=>{setTab(entryTab);setMatchId(entryMatchId);},[user.id,resourceId,dinderTab]);
 const changed=(match:DinderMatch|null)=>{setMatchId(match?.id);if(match)setTab(previous=>previous==='swipe'?'preparing':previous);};
 const localNavigate:Navigate=destination=>{if(destination.view==='dinder'&&!destination.resourceId){if(!decks.has(user.id)){setMatchId(undefined);setSwipeEpoch(value=>value+1);}setTab('swipe');}else navigate(destination);};
 if(resourceId==='catalog')return <Catalog/>;
 const active=tab==='swipe'&&matchId?'preparing':tab,panelKey=tab==='preparing'||tab==='chat'?`${tab}:${matchId}`:tab==='swipe'?`swipe:${swipeEpoch}`:tab;
 const content=tab==='about'?<About/>:tab==='settings'?<Settings user={user} navigate={localNavigate}/>:tab==='calendar'?<Calendar user={user} navigate={navigate}/>:matchId&&(tab==='preparing'||tab==='chat')?<MatchView user={user} matchId={matchId} initial={decks.get(user.id)?.match?.id===matchId?decks.get(user.id)?.match||undefined:undefined} navigate={localNavigate} chat={tab==='chat'} changed={changed}/>:<Swipe user={user} navigate={localNavigate} changed={changed}/>;
 return <div className="dinder-page" data-tab={active}><Sections active={active} matchId={matchId} select={setTab}/><div className="dinder-tab-content"><PreservedPanels retainVisited activeKey={panelKey} ancestorKeys={[]} reset={0}>{content}</PreservedPanels></div></div>;
}
