import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CalendarDots,SquaresFour,List,Plus,CaretLeft,CaretRight,LockSimple,Users,Image,Microphone,Stop,DownloadSimple,BookmarkSimple,X,CircleNotch} from '@phosphor-icons/react';
import {Temporal} from '@js-temporal/polyfill';
import {logFields,logPlainText,recurrenceOn,rebaseLogDraft,type LogEntry,type LogFields,type LogPreferences,type LogPage} from '../shared/log';
import type {Profile} from '../shared/types';
import type {Destination} from '../shared/navigation';
import {operation,errorText,ApiError} from './api';
import {uploadFile} from './uploads';
import type {UploadRef} from '../shared/uploads';
import {useRecordRefresh} from './useRecordRefresh';
import {usePanelVisible} from './PanelReadiness';
import {AgentMarkdown} from './AgentMarkdown';
import {PostPhotos} from './PostPhotos';
import {LinkPreviews} from './LinkPreview';
import {AudioPlayer} from './AudioPlayer';
import {useExperience} from './ExperienceContext';
import {DeleteConfirmation} from './DeleteConfirmation';
import './log.css';

type Navigate=(destination:Destination)=>void;
const today=()=>Temporal.Now.plainDateISO().toString();
const dateLabel=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});
const cover=(entry:LogEntry)=>{const photos=entry.contributors.flatMap(p=>p.files).filter(f=>f.mime.startsWith('image/'));return photos.find(f=>f.id===entry.coverFileId)||photos[0];};
const fields=(entry:LogEntry):LogFields=>({date:entry.date,title:entry.title,place:entry.place,links:entry.links,recurrence:entry.recurrence,coverFileId:entry.coverFileId});
const emit=()=>window.dispatchEvent(new CustomEvent('newdrugs:records',{detail:['log']}));
const emptyPreferences:LogPreferences={arrangement:'calendar',views:[]};

function LogTile({entry,open,compact=false,anniversary=false}:{entry:LogEntry;open():void;compact?:boolean;anniversary?:boolean}){
 const photo=cover(entry);
 return <button className={`log-tile ${compact?'log-tile-compact':''}`} onClick={open} title={entry.title||entry.contributors[0]?.note||'Open entry'}>
  {photo?<img src={photo.url} alt="" loading="lazy"/>:<div className="log-tile-note">{entry.title||entry.contributors[0]?.note||entry.place||'A moment'}</div>}
  <span className="log-tile-caption">{anniversary?'↻ ':''}{entry.title||entry.place||'Untitled'}</span>
  {entry.contributors.length>1&&<span className="log-tile-shared"><Users size={12}/>{entry.contributors.length}</span>}
 </button>;
}
function LogVideo({src}:{src:string}){const visible=usePanelVisible(),ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(!visible)ref.current?.pause();},[visible]);return <video ref={ref} className="log-video" src={src} controls playsInline preload="metadata" controlsList="nodownload"/>;}
function LogMedia({files}:{files:LogEntry['contributors'][number]['files']}){
 const visible=usePanelVisible();return <div className="log-media"><PostPhotos photos={files.filter(f=>f.mime.startsWith('image/'))}/>{files.filter(f=>f.mime.startsWith('audio/')).map(file=><div key={file.id}><span className="quiet small">{file.name}</span><AudioPlayer src={file.url} active={visible}/></div>)}{files.filter(f=>f.mime.startsWith('video/')).map(file=><LogVideo key={file.id} src={file.url}/>)}</div>;
}
function Recorder({add,error,disabled,change}:{add(file:File):Promise<void>;error(message:string):void;disabled:boolean;change(recording:boolean):void}){
 const visible=usePanelVisible(),alive=useRef(true),visibleRef=useRef(visible);visibleRef.current=visible;
 const [recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),discard=useRef(false);
 useEffect(()=>()=>{alive.current=false;discard.current=true;if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());},[]);
 useEffect(()=>{change(recording);},[recording]);
 useEffect(()=>{if(!visible&&recorder.current?.state==='recording')recorder.current.stop();},[visible]);
 useEffect(()=>{if(seconds>=300&&recorder.current?.state==='recording')recorder.current.stop();},[seconds]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>setSeconds(value=>value+1),1000);return()=>clearInterval(timer);},[recording]);
 const start=async()=>{try{
  if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw Error('Recording is unavailable in this browser. You can attach an audio file.');
  stream.current=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current||!visibleRef.current){stream.current.getTracks().forEach(track=>track.stop());return;}discard.current=false;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(value=>MediaRecorder.isTypeSupported(value));
  const rec=new MediaRecorder(stream.current,mime?{mimeType:mime}:undefined),parts:Blob[]=[];let size=0;recorder.current=rec;
  rec.ondataavailable=event=>{parts.push(event.data);size+=event.data.size;if(size>10*1024*1024&&rec.state==='recording')rec.stop();};
  rec.onstop=()=>{stream.current?.getTracks().forEach(track=>track.stop());setRecording(false);if(discard.current)return;const type=rec.mimeType,ext=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'weba';void add(new File(parts,`Recording.${ext}`,{type}));};
  rec.start(1000);setSeconds(0);setRecording(true);
 }catch(e){stream.current?.getTracks().forEach(track=>track.stop());error(errorText(e));}};
 return recording?<div className="log-recording"><span role="timer">{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span><button type="button" aria-label="Cancel recording" onClick={()=>{discard.current=true;recorder.current?.stop();}}><X size={18}/></button><button type="button" aria-label="Use recording" onClick={()=>recorder.current?.stop()}><Stop size={18} weight="fill"/></button></div>:<button type="button" disabled={disabled} onClick={()=>void start()}><Microphone size={19}/>Record</button>;
}

export function LogEditor({user,entry,date,onSaved,cancel}:{user:Profile;entry?:LogEntry;date?:string;onSaved(entry:LogEntry):void;cancel():void}){
 const [base,setBase]=useState(entry),[conflict,setConflict]=useState<LogEntry|null>(null);
 const own=entry?.contributors.find(p=>p.userId===user.id);
 const [draft,setDraft]=useState<LogFields>(entry?fields(entry):logFields.parse({date:date||today()})),[note,setNote]=useState(own?.note||''),[files,setFiles]=useState<LogEntry['contributors'][number]['files']>(own?.files||[]),[link,setLink]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[recording,setRecording]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),intent=useRef<{signature:string;key:string}|null>(null),staged=useRef<string[]>([]),committed=useRef(false);
 useEffect(()=>()=>{if(!committed.current)for(const fileId of staged.current)void operation('files.discard',{fileId}).catch(()=>{});},[]);
 const addFile=async(file:File)=>{setUploading(true);setError('');try{if(files.length>=8)throw Error('An entry can hold eight attachments per person.');const saved=await uploadFile(file,'log_media');staged.current.push(saved.id);setFiles(previous=>[...previous,saved as Required<UploadRef>].slice(0,8));}catch(e){setError(errorText(e));}finally{setUploading(false);}};
 const save=async(event:FormEvent)=>{event.preventDefault();if(busy||uploading||recording)return;setBusy(true);setError('');try{
  const links=link.trim()?[...draft.links,new URL(/^https?:\/\//i.test(link.trim())?link.trim():`https://${link.trim()}`).href]:draft.links;
  const input={...(entry?{entryId:entry.id,revision:base?.revision||entry.revision}:{}),entry:{...draft,links},contribution:{note,fileIds:files.map(file=>file.id)}},signature=JSON.stringify(input);
  if(intent.current?.signature!==signature)intent.current={signature,key:crypto.randomUUID()};
  const saved=await operation<LogEntry>(entry?'log.update':'log.create',input,{key:intent.current.key});committed.current=true;emit();if(!entry){setDraft(logFields.parse({date:draft.date}));setNote('');setFiles([]);setLink('');staged.current=[];committed.current=false;}onSaved(saved);
 }catch(e){setError(errorText(e));if(entry&&e instanceof ApiError&&e.code==='log_changed'){try{setConflict(await operation<LogEntry>('log.get',{entryId:entry.id}));}catch(latestError){setError(errorText(latestError));}}}finally{setBusy(false);}};
 return <form className="log-editor fields" onSubmit={save}>
  <div className="log-editor-top"><span className="log-privacy">{((entry?.contributors.length||0)>1||Boolean(entry?.invitations.length))?<><Users size={15}/>Shared entry</>:<><LockSimple size={15}/>Private until you invite someone</>}</span><input aria-label="Entry date" type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></div>
  <input className="log-title-input" aria-label="Title" placeholder="Give this moment a name" maxLength={160} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/>
  <label>Your note<textarea className="log-note-input" placeholder="What happened?" maxLength={10000} value={note} onChange={e=>setNote(e.target.value)}/></label>
  <div className="log-attachment-tools"><button type="button" disabled={uploading||files.length>=8} onClick={()=>fileInput.current?.click()}><Image size={19}/>Photo or file</button><Recorder change={setRecording} disabled={uploading||files.length>=8} add={addFile} error={setError}/>{uploading&&<CircleNotch className="spin" size={20}/>}<input ref={fileInput} type="file" hidden accept="image/jpeg,image/png,image/webp,audio/*,video/mp4,video/webm" onChange={e=>{const file=e.target.files?.[0];if(file)void addFile(file);e.currentTarget.value='';}}/></div>
  {!!files.length&&<div className="log-editor-files">{files.map(file=><div key={file.id} className="log-editor-file">{file.mime.startsWith('image/')?<img src={file.url} alt={file.name}/>:<span>{file.name}</span>}<div><button type="button" aria-label={`Remove ${file.name}`} onClick={()=>{setFiles(previous=>previous.filter(f=>f.id!==file.id));if(draft.coverFileId===file.id)setDraft({...draft,coverFileId:null});}}><X size={17}/></button>{file.mime.startsWith('image/')&&<button type="button" aria-pressed={draft.coverFileId===file.id} onClick={()=>setDraft({...draft,coverFileId:draft.coverFileId===file.id?null:file.id})}>Cover</button>}</div></div>)}</div>}
  {entry&&entry.contributors.filter(person=>person.userId!==user.id).some(person=>person.files.some(file=>file.mime.startsWith('image/')))&&<div className="log-cover-choices"><span className="quiet small">Other shared photos</span>{entry.contributors.filter(person=>person.userId!==user.id).flatMap(person=>person.files).filter(file=>file.mime.startsWith('image/')).map(file=><button type="button" key={file.id} aria-label={`Use ${file.name} as cover`} aria-pressed={draft.coverFileId===file.id} onClick={()=>setDraft({...draft,coverFileId:file.id})}><img src={file.url} alt={file.name}/></button>)}</div>}
  <label>Place<input placeholder="Optional" maxLength={160} value={draft.place} onChange={e=>setDraft({...draft,place:e.target.value})}/></label>
  <label>Link<input type="text" inputMode="url" placeholder="Optional" value={link} onChange={e=>setLink(e.target.value)}/></label>
  {draft.links.map(url=><div className="log-link-row" key={url}><a href={url} target="_blank" rel="noreferrer">{url.replace(/^https?:\/\/(www\.)?/,'')}</a><button type="button" aria-label="Remove link" onClick={()=>setDraft({...draft,links:draft.links.filter(value=>value!==url)})}><X size={17}/></button></div>)}
  {link.trim()&&draft.links.length<7&&<button type="button" onClick={()=>{try{const url=new URL(/^https?:\/\//i.test(link.trim())?link.trim():`https://${link.trim()}`);if(!/^https?:$/.test(url.protocol))throw Error();setDraft({...draft,links:[...new Set([...draft.links,url.href])]});setLink('');}catch{setError('Enter a valid website link.');}}}>Add another link</button>}
  <div className="log-recurrence" role="group" aria-label="Repeat on the calendar">{(['none','anniversary','birthday'] as const).map(value=><button type="button" key={value} aria-pressed={draft.recurrence===value} onClick={()=>setDraft({...draft,recurrence:value})}>{value==='none'?'One time':value==='anniversary'?'Anniversary':'Birthday'}</button>)}</div>
  {error&&<p className="error" role="alert">{error}</p>}
  {conflict&&base&&<section className="log-conflict"><strong>This entry changed elsewhere.</strong><p>Your draft is still here. Keeping your changes also picks up fields you haven’t edited.</p><details open><summary>Latest version</summary><p>{conflict.title||'Untitled'} · {conflict.date}{conflict.place?` · ${conflict.place}`:''}</p><p className="small">{conflict.contributors.map(person=>person.name).join(', ')}</p><AgentMarkdown text={conflict.contributors.find(person=>person.userId===user.id)?.note||'No note'}/>{conflict.links.map(url=><p key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></p>)}</details><div className="panel-actions"><button type="button" onClick={()=>{const own=conflict.contributors.find(person=>person.userId===user.id);setDraft(fields(conflict));setNote(own?.note||'');setFiles(own?.files||[]);setBase(conflict);setConflict(null);setError('');}}>Discard my draft</button><button type="button" className="solid" onClick={()=>{const merged=rebaseLogDraft(base,conflict,user.id,draft,note,files);setDraft(merged.entry);setNote(merged.note);setFiles(merged.files);setBase(conflict);setConflict(null);setError('');}}>Keep my changes</button></div></section>}
  <div className="panel-actions"><button type="button" onClick={cancel} disabled={busy}>Cancel</button><button className="solid" disabled={busy||uploading||recording||Boolean(conflict)}>{busy?'Saving…':'Save entry'}</button></div>
 </form>;
}

export function LogDetail({entryId,user,navigate,onSaved,onCancel}:{entryId:string;user:Profile;navigate:Navigate;onSaved?(entry:LogEntry):void;onCancel?():void}){
 const [entry,setEntry]=useState<LogEntry|null>(null),[error,setError]=useState(''),[editing,setEditing]=useState(false),[review,setReview]=useState(false),[sharing,setSharing]=useState(false),[friends,setFriends]=useState<Profile[]>([]),[selected,setSelected]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[neighbors,setNeighbors]=useState<{previous:LogEntry|null;next:LogEntry|null}>({previous:null,next:null});
 const experience=useExperience(),intent=useRef<{signature:string;key:string}|null>(null);
 const load=async()=>{try{setEntry(await operation<LogEntry>('log.get',{entryId}));setError('');}catch(e){setError(errorText(e));setEntry(null);}};
 useEffect(()=>{void load();void operation<{previous:LogEntry|null;next:LogEntry|null}>('log.neighbors',{entryId}).then(setNeighbors).catch(()=>{});},[entryId]);useRecordRefresh(['log','people'],()=>{if(!editing)void load();});
 const act=async(name:string,input:Record<string,unknown>={},confirmed=false)=>{if(!entry||busy)return;setBusy(true);setError('');try{const data={entryId:entry.id,revision:entry.revision,...input},signature=JSON.stringify([name,data]);if(intent.current?.signature!==signature)intent.current={signature,key:crypto.randomUUID()};const result=await operation<LogEntry>(name,data,{confirmed,key:intent.current.key});intent.current=null;emit();if(['log.leave','log.delete'].includes(name)||name==='log.respond'&&!input.accept){onCancel?.();navigate({view:'log'});}else setEntry(result);setReview(false);setSelected(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const share=async()=>{setSharing(value=>!value);try{const people:Profile[]=[];let before:string|undefined;do{const page=await operation<{items:{members:string[];status:string}[];people:Profile[];nextCursor:string|null}>('connections.list',{limit:30,...(before?{before}:{})});people.push(...page.people.filter(person=>person.id!==user.id&&page.items.some(connection=>connection.status==='accepted'&&connection.members.includes(person.id))));before=page.nextCursor||undefined;}while(before);setFriends([...new Map(people.map(person=>[person.id,person])).values()]);}catch(e){setError(errorText(e));}};
 if(!entry)return <div className="log-loading">{error?<p className="error" role="alert">{error}</p>:<CircleNotch className="spin" size={24}/>}</div>;
 if(editing)return <LogEditor user={user} entry={entry} onSaved={saved=>{setEntry(saved);setEditing(false);onSaved?.(saved);}} cancel={()=>{setEditing(false);onCancel?.();void load();}}/>;
 const mine=entry.ownerId===user.id;
 return <article className="log-detail">
  <div className="log-detail-meta"><span>{dateLabel(entry.date)}</span><span className="log-privacy">{entry.contributors.length>1||entry.invitations.length?<><Users size={14}/>Shared</>:<><LockSimple size={14}/>Private</>}</span></div>
  <h2>{entry.title||'Untitled'}</h2>{entry.place&&<p className="quiet">{entry.place}</p>}{entry.recurrence!=='none'&&<span className="log-recurrence-label">{entry.recurrence==='birthday'?'Birthday':'Anniversary'}</span>}
  {entry.membership==='invited'?<div className="log-invite-review"><p>You’re invited to share this entry. Join to add your own note and media.</p><div className="panel-actions"><button disabled={busy} onClick={()=>void act('log.respond',{accept:false})}>Decline</button><button className="solid" disabled={busy} onClick={()=>void act('log.respond',{accept:true})}>Join entry</button></div></div>:<div className="panel-actions"><button onClick={()=>setEditing(true)}>Edit entry</button>{experience&&<button onClick={()=>experience.ask({kind:'log',id:entry.id,title:entry.title||'Log entry'})}>Ask agent</button>}{mine&&<button onClick={()=>void share()}>Invite a friend</button>}<button className="quiet" onClick={()=>setReview(value=>!value)}>{mine?'Delete':'Leave'}</button></div>}
  {review&&<DeleteConfirmation title={mine?'Delete this entry?':'Leave this entry?'} detail={mine?'Everyone who shares it loses access. Files remain in Storage.':'Your note and media are removed from the entry. Other people keep their contributions.'} confirmLabel={mine?'Delete':'Leave'} busy={busy} onCancel={()=>setReview(false)} onConfirm={()=>act(mine?'log.delete':'log.leave',{},true)}/>}
  {sharing&&<section className="log-sharing"><h3>Invite a friend</h3>{selected?<><p>Share this entry, its notes and media with <strong>{selected.name||selected.handle}</strong>?</p><div className="panel-actions"><button onClick={()=>setSelected(null)}>Cancel</button><button className="solid" disabled={busy} onClick={()=>void act('log.invite',{personId:selected.id},true)}>Send invitation</button></div></>:<div className="log-friend-list">{friends.filter(person=>!entry.contributors.some(p=>p.userId===person.id)&&!entry.invitations.some(p=>p.userId===person.id)).map(person=><button key={person.id} onClick={()=>setSelected(person)}>{person.name} <span className="quiet">@{person.handle}</span><Plus size={17}/></button>)}{!friends.length&&<p className="quiet">Accepted friends appear here.</p>}</div>}</section>}
  {!!entry.invitations.length&&<div className="log-pending">{entry.invitations.map(person=><span key={person.userId}>Invited {person.name}{mine&&<button aria-label={`Withdraw invitation for ${person.name}`} onClick={()=>void act('log.revoke',{personId:person.userId})}><X size={15}/></button>}</span>)}</div>}
  {error&&<p className="error" role="alert">{error}</p>}
  <div className="log-contributions">{entry.contributors.map(person=><section key={person.userId} className="log-contribution"><button className="log-author" disabled={person.profileVisible===false} onClick={()=>navigate({view:'person',resourceId:person.userId})}>{person.photoId?<img src={`/api/files/${person.photoId}`} alt=""/>:<Users size={24}/>}<strong>{person.name}</strong>{person.handle&&<span className="quiet">@{person.handle}</span>}</button>{person.note&&<AgentMarkdown text={person.note}/>}<LogMedia files={person.files}/>{!person.note&&!person.files.length&&<p className="quiet small">{person.userId===user.id?'Add a note or photo whenever you like.':'No contribution yet.'}</p>}</section>)}</div>
  <LinkPreviews text="" links={entry.links}/><div className="log-adjacent">{neighbors.previous?<button onClick={()=>navigate({view:'log',resourceId:neighbors.previous!.id})}><CaretLeft size={18}/><span>{neighbors.previous.title||neighbors.previous.date}</span></button>:<span/>}{neighbors.next?<button onClick={()=>navigate({view:'log',resourceId:neighbors.next!.id})}><span>{neighbors.next.title||neighbors.next.date}</span><CaretRight size={18}/></button>:<span/>}</div>
 </article>;
}

export function LogPanel({user,navigate,initialQuery='',logMonth,logScope,logArrangement,personId:initialPerson,onStateChange}:{user:Profile;navigate:Navigate;initialQuery?:string;logMonth?:string;logScope?:Destination['logScope'];logArrangement?:Destination['logArrangement'];personId?:string;onStateChange?(context:Partial<Destination>):void}){
 const [preferences,setPreferences]=useState<LogPreferences>({...emptyPreferences,arrangement:logArrangement||'calendar'}),[month,setMonth]=useState(()=>logMonth?Temporal.PlainDate.from(`${logMonth}-01`):Temporal.Now.plainDateISO().with({day:1})),[scope,setScope]=useState<'all'|'private'|'shared'|'invitations'>(logScope||'all'),[query,setQuery]=useState(initialQuery),[applied,setApplied]=useState(initialQuery),[personId,setPersonId]=useState<string|undefined>(initialPerson),[items,setItems]=useState<LogEntry[]>([]),[recurring,setRecurring]=useState<LogEntry[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[savingView,setSavingView]=useState(false),[viewName,setViewName]=useState(''),[exporting,setExporting]=useState(false),[exportOpen,setExportOpen]=useState(false),[selectedView,setSelectedView]=useState<string|null>(null),[people,setPeople]=useState<{userId:string;name:string;handle?:string}[]>([]);
 const sequence=useRef(0);
 useEffect(()=>{setQuery(initialQuery||'');setApplied(initialQuery||'');},[initialQuery]);
 useEffect(()=>setScope(logScope||'all'),[logScope]);
 useEffect(()=>setPersonId(initialPerson),[initialPerson]);
 useEffect(()=>setMonth(logMonth?Temporal.PlainDate.from(`${logMonth}-01`):Temporal.Now.plainDateISO().with({day:1})),[logMonth]);
 useEffect(()=>{if(logArrangement)setPreferences(previous=>({...previous,arrangement:logArrangement}));},[logArrangement]);
 const stateChange=(next:Partial<Destination>)=>onStateChange?.({query:applied||undefined,logScope:scope,personId,logMonth:month.toString().slice(0,7),logArrangement:preferences.arrangement,...next});
 const calendar=preferences.arrangement==='calendar'&&scope!=='invitations';
 const gridStart=month.subtract({days:month.dayOfWeek%7}),gridLength=Math.ceil((month.dayOfWeek%7+month.daysInMonth)/7)*7;
 const range={from:gridStart.toString(),through:gridStart.add({days:gridLength-1}).toString()};
 const load=async(append=false)=>{const ticket=++sequence.current;setBusy(true);setError('');try{
  const input={scope,...(applied?{query:applied}:{}),...(personId?{personId}:{}),...(calendar?range:{}),limit:30,...(append&&cursor?{before:cursor}:{})};
  const page=await operation<LogPage>('log.list',input);
  // Calendar must not silently omit a busy month's later entries.
  if(calendar){while(page.nextCursor){const next=await operation<LogPage>('log.list',{...input,before:page.nextCursor});if(ticket!==sequence.current)return;page.items.push(...next.items);page.nextCursor=next.nextCursor;}}
  if(ticket!==sequence.current)return;setItems(previous=>append?[...previous,...page.items]:page.items);setCursor(page.nextCursor);
  if(calendar){let before:string|undefined,all:LogEntry[]=[];do{const page=await operation<LogPage>('log.list',{scope,recurring:true,limit:30,...(applied?{query:applied}:{}),...(personId?{personId}:{}),...(before?{before}:{})});if(ticket!==sequence.current)return;all.push(...page.items);before=page.nextCursor||undefined;}while(before);setRecurring(all);}
 }catch(e){if(ticket===sequence.current)setError(errorText(e));}finally{if(ticket===sequence.current)setBusy(false);}};
 useEffect(()=>{void operation<{items:{userId:string;name:string;handle?:string}[]}>('log.people').then(result=>setPeople(result.items)).catch(()=>{});void operation<LogPreferences>('log.preferences').then(value=>setPreferences({...value,arrangement:logArrangement||value.arrangement})).catch(e=>setError(errorText(e)));},[]);
 useEffect(()=>{void load();return()=>{sequence.current++;};},[month.toString(),scope,applied,personId,preferences.arrangement]);
 useRecordRefresh(['log'],()=>{void load();void operation<{items:{userId:string;name:string;handle?:string}[]}>('log.people').then(result=>setPeople(result.items)).catch(()=>{});});
 useRecordRefresh(['log_preferences'],()=>{void operation<LogPreferences>('log.preferences').then(setPreferences).catch(()=>{});});
 const prefs=async(value:LogPreferences)=>{setPreferences(value);try{setPreferences(await operation<LogPreferences>('log.preferences_update',value));}catch(e){setError(errorText(e));}};
 const exportLog=async(format:'json'|'txt')=>{setExporting(true);setError('');try{let before:string|undefined;const entries:LogEntry[]=[];do{const page=await operation<LogPage>('log.export',{scope,limit:30,...(applied?{query:applied}:{}),...(personId?{personId}:{}),...(before?{before}:{})});entries.push(...page.items);before=page.nextCursor||undefined;}while(before);const blob=new Blob([format==='json'?JSON.stringify({format:'New Drugs Log',version:1,site:location.origin,exportedAt:new Date().toISOString(),entries},null,2):`New Drugs Log\n${location.origin}\n\n${logPlainText(entries)}`],{type:format==='json'?'application/json':'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`new-drugs-log-${today()}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExportOpen(false);}catch(e){setError(errorText(e));}finally{setExporting(false);}};
 const days=Array.from({length:gridLength},(_,index)=>gridStart.add({days:index}));
 const onDay=(date:string)=>{const actual=items.filter(entry=>entry.date===date);const repeats=recurring.filter(entry=>entry.date!==date&&recurrenceOn(entry,Number(date.slice(0,4)))===date&&!actual.some(item=>item.id===entry.id));return [...actual,...repeats];};
 return <div className="log-browser">
  <div className="log-toolbar"><div className="log-scope" role="group" aria-label="Log scope">{(['all','private','shared','invitations'] as const).map(value=><button key={value} aria-pressed={scope===value} onClick={()=>{setScope(value);setSelectedView(null);stateChange({logScope:value});}}>{value==='all'?'All entries':value==='invitations'?'Invites':value==='private'?'Private':'Shared'}</button>)}</div><div className="log-arrangement" role="group" aria-label="Log arrangement">{([{value:'calendar',label:'Calendar',Icon:CalendarDots},{value:'gallery',label:'Gallery',Icon:SquaresFour},{value:'list',label:'List',Icon:List}] as const).map(({value,label,Icon})=><button key={value} aria-label={label} title={label} aria-pressed={preferences.arrangement===value} onClick={()=>{stateChange({logArrangement:value});void prefs({...preferences,arrangement:value});}}><Icon size={19}/></button>)}</div></div>
  {!!people.filter(person=>person.userId!==user.id).length&&<details className="log-people-filter"><summary><Users size={15}/>{people.find(person=>person.userId===personId)?.name||'Everyone'}</summary><div><button onClick={e=>{setPersonId(undefined);stateChange({personId:undefined});e.currentTarget.closest('details')!.open=false;}}>Everyone</button>{people.filter(person=>person.userId!==user.id).map(person=><button key={person.userId} onClick={e=>{setPersonId(person.userId);setSelectedView(null);stateChange({personId:person.userId});e.currentTarget.closest('details')!.open=false;}}>{person.name}{person.handle?` @${person.handle}`:''}</button>)}</div></details>}
  <form className="log-search" onSubmit={e=>{e.preventDefault();setApplied(query);setSelectedView(null);stateChange({query});}}><input aria-label="Search your Log" placeholder="Search your Log" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit">Search</button><button type="button" aria-label="Save this view" title="Save this view" onClick={()=>setSavingView(value=>!value)}><BookmarkSimple size={20}/></button></form>
  {!!preferences.views.length&&<div className="log-saved-views">{preferences.views.map(view=><span key={view.id}><button aria-pressed={selectedView===view.id} onClick={()=>{setSelectedView(view.id);setQuery(view.query);setApplied(view.query);setScope(view.scope);setPersonId(view.personId);stateChange({query:view.query,logScope:view.scope,personId:view.personId});}}>{view.name}</button>{selectedView===view.id&&<button aria-label={`Remove saved view ${view.name}`} onClick={()=>{setSelectedView(null);void prefs({...preferences,views:preferences.views.filter(item=>item.id!==view.id)});}}><X size={14}/></button>}</span>)}</div>}
  {savingView&&<form className="log-search" onSubmit={e=>{e.preventDefault();if(!viewName.trim())return;void prefs({...preferences,views:[...preferences.views,{id:crypto.randomUUID(),name:viewName.trim(),query:applied,scope:scope==='invitations'?'all':scope,...(personId?{personId}:{})}]});setSavingView(false);setViewName('');}}><input aria-label="View name" required maxLength={40} value={viewName} onChange={e=>setViewName(e.target.value)} placeholder="Name this view"/><button disabled={preferences.views.length>=20}>Save view</button></form>}
  {calendar&&<div className="log-calendar-heading"><button aria-label="Previous month" onClick={()=>{const next=month.subtract({months:1});setMonth(next);stateChange({logMonth:next.toString().slice(0,7)});}}><CaretLeft size={20}/></button><label><strong>{new Date(`${month}T12:00:00`).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><input aria-label="Choose month" type="month" value={month.toString().slice(0,7)} onChange={e=>{if(e.target.value){setMonth(Temporal.PlainDate.from(`${e.target.value}-01`));stateChange({logMonth:e.target.value});}}}/></label><button aria-label="Next month" onClick={()=>{const next=month.add({months:1});setMonth(next);stateChange({logMonth:next.toString().slice(0,7)});}}><CaretRight size={20}/></button><button className="log-today" onClick={()=>{setMonth(Temporal.Now.plainDateISO().with({day:1}));stateChange({logMonth:undefined});}}>Today</button></div>}
  {error&&<p className="error" role="alert">{error}</p>}
  {calendar?<div className="log-calendar" aria-label="Calendar">{['S','M','T','W','T','F','S'].map((day,index)=><span className="log-weekday" key={index}>{day}</span>)}{days.map(day=>{const date=day.toString(),entries=onDay(date);return <div key={date} className="log-day" data-outside={day.month!==month.month||undefined} data-today={date===today()||undefined}><button className="log-day-number" aria-label={`Add entry for ${dateLabel(date)}`} onClick={()=>navigate({view:'log_compose',date})}>{day.day}<Plus size={11}/></button><div className="log-day-entries">{entries.map(entry=><LogTile key={entry.id} entry={entry} compact anniversary={entry.date!==date} open={()=>navigate({view:'log',resourceId:entry.id})}/>)}</div></div>;})}</div>:preferences.arrangement==='gallery'&&scope!=='invitations'?<div className="log-gallery">{items.map(entry=><div key={entry.id}><LogTile entry={entry} open={()=>navigate({view:'log',resourceId:entry.id})}/><time>{dateLabel(entry.date)}</time></div>)}</div>:<div className="log-list">{items.map(entry=><button key={entry.id} onClick={()=>navigate({view:'log',resourceId:entry.id})}>{cover(entry)?<img src={cover(entry)!.url} alt=""/>:<span className="log-list-date">{entry.date.slice(8)}<small>{new Date(`${entry.date}T12:00:00`).toLocaleDateString(undefined,{month:'short'})}</small></span>}<span><strong>{entry.title||'Untitled'}</strong><span className="quiet small">{dateLabel(entry.date)}{entry.place?` · ${entry.place}`:''}</span><span className="log-list-preview">{entry.contributors.map(p=>p.note).filter(Boolean).join(' · ')}</span></span>{entry.membership==='invited'?<span className="log-invited-tag">Invited</span>:entry.contributors.length>1?<Users size={18}/>:null}</button>)}</div>}
  {busy&&<div className="log-loading" role="status" aria-label="Loading entries"><CircleNotch className="spin" size={22}/></div>}
  {!busy&&!items.length&&!calendar&&<div className="log-empty"><CalendarDots size={32}/><p>{scope==='invitations'?'No pending invitations.':applied?'No entries match this view.':'A place for the things you do, and the people you do them with.'}</p>{scope!=='invitations'&&<button className="solid" onClick={()=>navigate({view:'log_compose'})}>Add an entry</button>}</div>}
  {!calendar&&cursor&&<button className="more-messages" disabled={busy} onClick={()=>void load(true)}>More entries</button>}
  <div className="log-bottom-tools"><span className="quiet small">Only you and the people you invite.</span><button aria-label="Export Log" onClick={()=>setExportOpen(value=>!value)}><DownloadSimple size={18}/></button></div>{exportOpen&&<div className="log-export"><p className="quiet small">Export all entries in this filter. Media links remain private.</p><button disabled={exporting} onClick={()=>void exportLog('json')}>{exporting?'Exporting…':'JSON'}</button><button disabled={exporting} onClick={()=>void exportLog('txt')}>Text</button></div>}
 </div>;
}
