import type {Destination} from '../shared/navigation';
import {useEffect,useRef,useState} from 'react';
import {CalendarDots,SquaresFour,List,CircleNotch} from '@phosphor-icons/react';
import type {LogPreferences} from '../shared/log';
import {ownBirthdaySchema,type OwnBirthday} from '../shared/logBirthday';
import {operation,errorText} from './api';
import {usePanelLoading} from './PanelReadiness';
import {downloadLog} from './logExport';
export function LogSettings({close,navigate,closeLabel='Close'}:{closeLabel?:string;close():void;navigate(destination:Destination):void;onLayoutChange?(value:LogPreferences['arrangement']):void}){
 const [prefs,setPrefs]=useState<LogPreferences|null>(null),[birthday,setBirthday]=useState<OwnBirthday|null>(null),[month,setMonth]=useState(''),[day,setDay]=useState(''),[year,setYear]=useState(''),[error,setError]=useState(''),[birthdayBusy,setBirthdayBusy]=useState(false),[layoutBusy,setLayoutBusy]=useState(false),[saved,setSaved]=useState(false),[exporting,setExporting]=useState(false),intent=useRef<{input:string;key:string}|null>(null);
 useEffect(()=>{let alive=true;void Promise.all([operation<LogPreferences>('log.preferences'),operation<{birthday:OwnBirthday|null}>('log.birthday_get')]).then(([preferences,result])=>{if(alive){setPrefs(preferences);setBirthday(result.birthday);setMonth(result.birthday?String(result.birthday.month):'');setDay(result.birthday?String(result.birthday.day):'');setYear(result.birthday?.year?String(result.birthday.year):'');}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[]);
 const saveBirthday=async(value:OwnBirthday|null)=>{if(birthdayBusy)return;setBirthdayBusy(true);setError('');try{if(value)ownBirthdaySchema.parse(value);const input=JSON.stringify(value);if(intent.current?.input!==input)intent.current={input,key:crypto.randomUUID()};const result=await operation<{birthday:OwnBirthday|null}>('log.birthday_update',{birthday:value},{key:intent.current.key});setBirthday(result.birthday);setMonth(result.birthday?String(result.birthday.month):'');setDay(result.birthday?String(result.birthday.day):'');setYear(result.birthday?.year?String(result.birthday.year):'');setSaved(true);window.dispatchEvent(new CustomEvent('newdrugs:records',{detail:['log_birthdays']}));}catch(e){setError(errorText(e));}finally{setBirthdayBusy(false);}};
 const layout=async(arrangement:LogPreferences['arrangement'])=>{if(!prefs||layoutBusy)return;setLayoutBusy(true);setError('');try{setPrefs(await operation<LogPreferences>('log.preferences_update',{...prefs,arrangement}));window.dispatchEvent(new CustomEvent('newdrugs:records',{detail:['log_preferences']}));}catch(e){setError(errorText(e));}finally{setLayoutBusy(false);}};
 const exportFile=async(format:'json'|'txt')=>{setExporting(true);try{await downloadLog(format);}catch(e){setError(errorText(e));}finally{setExporting(false);}};
 usePanelLoading(!prefs&&!error);
 const valid=ownBirthdaySchema.safeParse({month:Number(month),day:Number(day),...(year.trim()?{year:Number(year)}:birthday?.year?{year:null}:{})}),changed=Number(month)!==birthday?.month||Number(day)!==birthday?.day||(year.trim()?Number(year):null)!==(birthday?.year||null);
 return <section className="log-task log-settings"><div className="log-settings-body"><h2>Log settings</h2>{!prefs&&!error?<CircleNotch className="spin" size={24}/>:prefs&&<>
 <section><h3>Birthday</h3><form className="fields" onSubmit={event=>{event.preventDefault();if(valid.success)void saveBirthday(valid.data);}}><div className="log-birthday-fields"><label>Month<select aria-label="Birthday month" value={month} disabled={birthdayBusy} onChange={event=>{setMonth(event.target.value);setSaved(false);}}><option value="">Month</option>{Array.from({length:12},(_,index)=><option key={index+1} value={index+1}>{new Date(2000,index,1).toLocaleDateString(undefined,{month:'long'})}</option>)}</select></label><label>Day<select aria-label="Birthday day" value={day} disabled={birthdayBusy} onChange={event=>{setDay(event.target.value);setSaved(false);}}><option value="">Day</option>{Array.from({length:month?new Date(2000,Number(month),0).getDate():31},(_,index)=><option key={index+1} value={index+1}>{index+1}</option>)}</select></label><label>Year<input aria-label="Birth year" type="number" inputMode="numeric" min="1" max={new Date().getFullYear()} placeholder="optional" value={year} disabled={birthdayBusy} onChange={event=>{setYear(event.target.value);setSaved(false);}}/></label></div><p className="quiet small">Month and day are shown to friends. Year is private.</p><div className="panel-actions"><button className="solid" disabled={birthdayBusy||!valid.success||!changed}>{birthdayBusy?'Saving…':saved?'Saved':'Save birthday'}</button>{birthday&&<button type="button" disabled={birthdayBusy} onClick={()=>void saveBirthday(null)}>Remove birthday</button>}</div></form></section>
 <section><h3>View</h3><div className="view-tabs">{([{value:'calendar',label:'Calendar',Icon:CalendarDots},{value:'gallery',label:'Grid',Icon:SquaresFour},{value:'list',label:'List',Icon:List}] as const).map(({value,label,Icon})=><button key={value} disabled={layoutBusy} aria-pressed={prefs.arrangement===value} onClick={()=>void layout(value)}><Icon size={18}/>{label}</button>)}</div></section>
 <nav className="log-settings-navigation" aria-label="Log pages"><button onClick={()=>navigate({view:'log_people'})}>People</button><button onClick={()=>navigate({view:'log_birthdays'})}>Birthdays</button><button onClick={()=>navigate({view:'log_anniversaries'})}>Anniversaries</button></nav><section><h3>Export</h3><div className="panel-actions"><button disabled={exporting} onClick={()=>void exportFile('json')}>JSON</button><button disabled={exporting} onClick={()=>void exportFile('txt')}>Text</button></div></section>
 </>}{error&&<p className="error" role="alert">{error}</p>}</div><footer className="panel-actions log-task-footer"><button onClick={close}>{closeLabel}</button></footer></section>;
}
