import {useState} from 'react';
import {Sun,Moon,Monitor,Article,Users,CalendarDots,Brain,NotePencil} from '@phosphor-icons/react';
import type {AccountPreferences} from '../shared/preferences';
import {operation,errorText} from './api';
import {NavLink} from './NavLink';
export function PreferencesPanel({value,changed}:{value:AccountPreferences;changed(preferences:AccountPreferences):void}){
 const [pending,setPending]=useState(false),[error,setError]=useState('');
 const choose=async(input:Partial<Pick<AccountPreferences,'appearance'|'font'|'landingPage'>>)=>{if(pending)return;setPending(true);setError('');try{changed(await operation<AccountPreferences>('account.preferences_update',input));}catch(e){setError(errorText(e));}finally{setPending(false);}};
 return <div className="preferences-panel"><section><h3>Theme</h3><div className="view-tabs appearance-options" aria-label="Color theme">{([{mode:'light',label:'Light',Icon:Sun},{mode:'dark',label:'Dark',Icon:Moon},{mode:'system',label:'System',Icon:Monitor}] as const).map(({mode,label,Icon})=><button key={mode} aria-pressed={value.appearance===mode} disabled={pending} onClick={()=>void choose({appearance:mode})}><Icon size={20}/>{label}</button>)}</div></section><section><h3>Font</h3><div className="view-tabs appearance-options" aria-label="Font">{(['mono','sans','serif'] as const).map(font=><button key={font} style={{fontFamily:`var(--font-${font})`}} aria-pressed={(value.font||'mono')===font} disabled={pending} onClick={()=>void choose({font})}>{font==='mono'?'Mono':font==='sans'?'Sans':'Serif'}</button>)}</div></section><section><h3>Landing page</h3><div className="view-tabs appearance-options landing-options" aria-label="Landing page">{([{mode:'agent',label:'Agent',Icon:Brain},{mode:'posts',label:'Posts',Icon:Article},{mode:'friends',label:'Friends',Icon:Users},{mode:'log',label:'Log',Icon:CalendarDots}] as const).map(({mode,label,Icon})=><button key={mode} aria-pressed={value.landingPage===mode} disabled={pending} onClick={()=>void choose({landingPage:mode})}><Icon size={18}/>{label}</button>)}</div></section><section><h3>Agent</h3><div className="settings-utilities agent-preference-actions"><NavLink to={{view:'agent_instructions'}}><NotePencil size={20}/>Guidance</NavLink><NavLink to={{view:'agent_memory'}}><Brain size={20}/>Agent memory</NavLink></div></section>{error&&<p className="error" role="alert">{error}</p>}</div>;
}
