import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Room,RoomEvent,Track,type Participant,type RemoteTrack} from 'livekit-client';
import {Hand,Headphones,Microphone,MicrophoneSlash,ShareNetwork,Waveform,UsersThree,X} from '@phosphor-icons/react';
import type {Space} from '../shared/spaces';
import type {Destination} from '../shared/navigation';
import {api,errorText,operation,post} from './api';
import {NavLink} from './NavLink';
import {usePanelVisible} from './PanelReadiness';
import {useRecordRefresh} from './useRecordRefresh';
import './spaces.css';

type Navigate=(destination:Destination)=>void;
interface SpacePage {items:Space[];nextCursor:string|null}
interface SpeakerRequest {spaceId:string;personId:string;name:string;status:string;createdAt:string}
const avatar=(name:string,photoId?:string)=><span className="space-avatar">{photoId?<img src={`/api/files/${encodeURIComponent(photoId)}`} alt=""/>:name.replace(/^@/,'').slice(0,1).toUpperCase()}</span>;
function livePhoto(participant:Participant){try{const value=JSON.parse(participant.metadata||'{}');return typeof value.photoId==='string'?value.photoId:undefined;}catch{return undefined;}}

export function SpacesPanel({spaceId,navigate}:{spaceId?:string;navigate:Navigate}){
 const visible=usePanelVisible(),[list,setList]=useState<SpacePage|null>(null),[space,setSpace]=useState<Space|null>(null),[requests,setRequests]=useState<SpeakerRequest[]>([]),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[composing,setComposing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [searchInput,setSearchInput]=useState(''),[searchNotice,setSearchNotice]=useState(''),[searchBusy,setSearchBusy]=useState(false),searchTerm=useRef('');
 const [room,setRoom]=useState<Room|null>(null),[members,setMembers]=useState<Participant[]>([]),[speaking,setSpeaking]=useState<Set<string>>(new Set()),[mic,setMic]=useState(false),[audioBlocked,setAudioBlocked]=useState(false),[copied,setCopied]=useState(false);
 const [selectedPerson,setSelectedPerson]=useState<{id:string;name:string;speaker:boolean}|null>(null);
 const audioHost=useRef<HTMLDivElement>(null);
 const load=useCallback(async()=>{
  try{
   if(spaceId){const result=await operation<Space>('spaces.get',{spaceId});setSpace(result);if(result.myRole==='host')setRequests((await operation<{items:SpeakerRequest[]}>('spaces.requests',{spaceId})).items);}
   else if(!searchTerm.current)setList(await operation<SpacePage>('spaces.list',{limit:20}));
   setError('');
  }catch(error){setError(errorText(error));}
 },[spaceId]);
 useEffect(()=>{setList(null);setSpace(null);setRoom(null);setRequests([]);setError('');searchTerm.current='';setSearchInput('');setSearchNotice('');void load();},[load]);
 useRecordRefresh(['spaces'],load);
 useEffect(()=>{if(!visible)return;const timer=setInterval(()=>void load(),spaceId?10000:20000);return()=>clearInterval(timer);},[visible,spaceId,load]);
 useEffect(()=>{if(!room)return;
  const sync=()=>setMembers([room.localParticipant,...room.remoteParticipants.values()]);
  const audio=(track:RemoteTrack)=>{if(track.kind!==Track.Kind.Audio||!audioHost.current)return;const element=track.attach();element.setAttribute('data-track-id',track.sid||'');audioHost.current.append(element);};
  const remove=(track:RemoteTrack)=>{for(const element of track.detach())element.remove();};
  room.on(RoomEvent.ParticipantConnected,sync).on(RoomEvent.ParticipantDisconnected,sync).on(RoomEvent.ParticipantPermissionsChanged,()=>{sync();void load();}).on(RoomEvent.ActiveSpeakersChanged,participants=>setSpeaking(new Set(participants.map(person=>person.identity)))).on(RoomEvent.TrackSubscribed,audio).on(RoomEvent.TrackUnsubscribed,remove);
  room.on(RoomEvent.Disconnected,()=>{setRoom(null);setMic(false);void load();});
  sync();for(const participant of room.remoteParticipants.values())for(const publication of participant.audioTrackPublications.values())if(publication.track)audio(publication.track);
  return()=>{room.removeAllListeners();for(const element of audioHost.current?.children||[])element.remove();void room.disconnect();};
 },[room,load]);
 useEffect(()=>{if(space?.status==='ended'&&room){void room.disconnect();setRoom(null);setMic(false);}},[space?.status,room]);
 const create=async(event:FormEvent)=>{event.preventDefault();if(!title.trim()||!description.trim()||busy)return;setBusy(true);try{const saved=await operation<Space>('spaces.create',{title:title.trim(),description:description.trim()},{confirmed:true});setTitle('');setDescription('');setComposing(false);navigate({view:'spaces',resourceId:saved.id});}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const search=async(event?:FormEvent,cursor?:string)=>{event?.preventDefault();const query=cursor?searchTerm.current:searchInput.trim();if(!query){searchTerm.current='';setSearchNotice('');void load();return;}if(searchBusy)return;setSearchBusy(true);setError('');try{const result=await operation<{matches:{record:Space}[];nextCursor:string|null;retrieval:{notices:string[]}}>('search.query',{query,datasets:['spaces'],mode:'hybrid',limit:20,...(cursor?{cursor}:{})});searchTerm.current=query;setSearchNotice(result.retrieval.notices.join(' '));const items=result.matches.map(match=>match.record);setList(previous=>cursor&&previous?{items:[...previous.items,...items],nextCursor:result.nextCursor}:{items,nextCursor:result.nextCursor});}catch(error){setError(errorText(error));}finally{setSearchBusy(false);}};
 const join=async()=>{if(!spaceId||busy||room)return;setBusy(true);try{
  const access=await post<{url:string;token:string;space:Space}>(`/spaces/${spaceId}/token`),next=new Room({adaptiveStream:true,dynacast:true});
  await next.connect(access.url,access.token);setRoom(next);setSpace(access.space);
  try{await next.startAudio();setAudioBlocked(false);}catch{setAudioBlocked(true);}
 }catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const leave=()=>{if(room){void room.disconnect();setRoom(null);setMic(false);}navigate({view:'spaces'});};
 const end=async()=>{if(!space||busy)return;setBusy(true);try{await operation('spaces.end',{spaceId:space.id,revision:space.revision},{confirmed:true});if(room){void room.disconnect();setRoom(null);}navigate({view:'spaces'});}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const request=async()=>{if(!space||busy)return;setBusy(true);try{await operation(space.myRequest==='pending'?'spaces.cancel_request':'spaces.request_speak',{spaceId:space.id});await load();}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const respond=async(personId:string,approve:boolean)=>{if(!space||busy)return;setBusy(true);try{const value=await operation<{space:Space}>('spaces.respond_speaker',{spaceId:space.id,revision:space.revision,personId,approve},{confirmed:true});setSpace(value.space);await load();}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const revoke=async(personId:string)=>{if(!space||busy)return;setBusy(true);try{const value=await operation<{space:Space}>('spaces.revoke_speaker',{spaceId:space.id,revision:space.revision,personId});setSpace(value.space);setSelectedPerson(null);}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const remove=async(personId:string)=>{if(!space||busy)return;setBusy(true);try{const value=await operation<{space:Space}>('spaces.remove_person',{spaceId:space.id,revision:space.revision,personId},{confirmed:true});setSpace(value.space);setSelectedPerson(null);}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const toggleMic=async()=>{if(!room||busy)return;setBusy(true);try{await room.localParticipant.setMicrophoneEnabled(!mic);setMic(room.localParticipant.isMicrophoneEnabled);}catch(error){setError(errorText(error));}finally{setBusy(false);}};
 const share=async()=>{if(!space)return;const url=new URL(`/spaces/${space.id}`,location.origin).href;try{if(navigator.share)await navigator.share({title:space.title,url});else{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),2000);}}catch(error){if((error as Error).name!=='AbortError')setError(errorText(error));}};
 if(!spaceId)return <section className="spaces-browser"><div className="spaces-list-top"><p>Live audio with people on New Drugs.</p><button type="button" onClick={()=>setComposing(value=>!value)}>{composing?'Cancel':'Start a Space'}</button></div>
  <form className="spaces-search" onSubmit={event=>void search(event)}><label className="sr-only" htmlFor="spaces-query">Search Spaces</label><input id="spaces-query" type="search" value={searchInput} onChange={event=>setSearchInput(event.target.value)} placeholder="Search live Spaces"/><button type="submit" disabled={searchBusy}>Search</button></form>
  {composing&&<form className="spaces-compose" onSubmit={event=>void create(event)}><label htmlFor="space-title">Name your Space</label><input id="space-title" value={title} maxLength={100} onChange={event=>setTitle(event.target.value)} autoFocus/><label htmlFor="space-description">Description</label><textarea id="space-description" value={description} maxLength={500} rows={3} onChange={event=>setDescription(event.target.value)}/><button disabled={busy||!title.trim()||!description.trim()}>Start Space</button></form>}
  <div className="spaces-list">{list?.items.map(item=><NavLink className="space-list-card" key={item.id} to={{view:'spaces',resourceId:item.id}} navigate={()=>navigate({view:'spaces',resourceId:item.id})}><span className="space-live"><Waveform size={15}/> LIVE</span><strong>{item.title}</strong><span>{item.description}</span><span>{item.hostName} is hosting</span><span className="space-speaker-peek">{item.speakers.slice(0,4).map(person=><span key={person.id} title={person.name}>{avatar(person.name,person.photoId)}</span>)}<small>{item.speakerIds.length} speaking</small></span></NavLink>)}</div>
  {list&&!list.items.length&&<p className="quiet">{searchTerm.current?'No live Spaces match that search.':'No Spaces are live right now.'}</p>}{searchNotice&&<p className="quiet small">{searchNotice}</p>}{list?.nextCursor&&<button type="button" className="text-link" onClick={()=>searchTerm.current?void search(undefined,list.nextCursor!):void operation<SpacePage>('spaces.list',{limit:20,before:list.nextCursor}).then(page=>setList(current=>current?{items:[...current.items,...page.items],nextCursor:page.nextCursor}:page)).catch(error=>setError(errorText(error)))}>More Spaces</button>}{error&&<p className="error" role="alert">{error}</p>}</section>;
 if(!space)return <section className="space-room"><NavLink to={{view:'spaces'}} navigate={()=>navigate({view:'spaces'})}>Back to Spaces</NavLink>{error&&<p className="error" role="alert">{error}</p>}</section>;
 const role=space.myRole||'listener',speaker=role==='host'||role==='speaker';
 const participants=members.filter(person=>person.identity),speakers=participants.filter(person=>space.speakerIds.includes(person.identity)),listeners=participants.filter(person=>!space.speakerIds.includes(person.identity));
 return <section className="space-room"><div className="space-room-top"><div><span className="space-live"><Waveform size={15}/> LIVE</span><h2>{space.title}</h2><p>{space.description}</p><p>{space.hostName}’s Space</p></div>{role==='host'?<button type="button" className="space-end" disabled={busy||space.status==='ended'} onClick={()=>void end()}>End</button>:<button type="button" onClick={leave}>{room?'Leave':'Back'}</button>}</div>
  {space.status==='ended'?<p>This Space has ended.</p>:<><div className="space-members"><h3>Speakers</h3><div className="space-avatar-grid">{(room?speakers:space.speakers.map(person=>({identity:person.id,name:person.name,metadata:JSON.stringify({photoId:person.photoId})}))).map(person=><div className={`space-person ${speaking.has(person.identity)?'speaking':''}`} key={person.identity}>{role==='host'&&person.identity!==space.hostId?<button type="button" className="space-avatar-button" aria-label={`Manage ${person.name||'speaker'}`} onClick={()=>setSelectedPerson({id:person.identity,name:person.name||'Member',speaker:true})}>{avatar(person.name||'Member',livePhoto(person as Participant))}</button>:avatar(person.name||'Member',livePhoto(person as Participant))}<strong>{person.name||'Member'}</strong><small>{person.identity===space.hostId?'Host':'Speaker'}</small></div>)}</div>
   <h3>Listeners</h3><div className="space-avatar-grid">{room?listeners.map(person=><div className="space-person" key={person.identity}>{role==='host'?<button type="button" className="space-avatar-button" aria-label={`Manage ${person.name||'listener'}`} onClick={()=>setSelectedPerson({id:person.identity,name:person.name||'Member',speaker:false})}>{avatar(person.name||'Member',livePhoto(person))}</button>:avatar(person.name||'Member',livePhoto(person))}<strong>{person.name||'Member'}</strong></div>):<p>Join to see who is listening.</p>}</div>{selectedPerson&&role==='host'&&<div className="space-person-menu"><strong>{selectedPerson.name}</strong>{selectedPerson.speaker&&<button type="button" disabled={busy} onClick={()=>void revoke(selectedPerson.id)}>Remove mic</button>}<button type="button" disabled={busy} onClick={()=>void remove(selectedPerson.id)}>Remove from Space</button><button type="button" onClick={()=>setSelectedPerson(null)}>Close</button></div>}</div>
   {!room?<div className="space-join"><button type="button" disabled={busy} onClick={()=>void join()}><Headphones size={21}/>Join Space</button></div>:<footer className="space-controls">{speaker?<button type="button" disabled={busy} onClick={()=>void toggleMic()}>{mic?<Microphone size={22}/>:<MicrophoneSlash size={22}/>}<span>{mic?'Mic on':'Mic off'}</span></button>:<button type="button" disabled={busy} onClick={()=>void request()}><Hand size={22}/><span>{space.myRequest==='pending'?'Request sent':'Request to speak'}</span></button>}{role==='host'&&<button type="button" onClick={()=>void load()}><UsersThree size={22}/><span>Requests{requests.length?` ${requests.length}`:''}</span></button>}<button type="button" onClick={()=>void share()}><ShareNetwork size={22}/><span>{copied?'Copied':'Share'}</span></button>{role!=='host'&&<button type="button" className="space-control-leave" onClick={leave}><X size={22}/><span>Leave</span></button>}</footer>}
   {audioBlocked&&<button type="button" className="space-audio-unlock" onClick={()=>void room?.startAudio().then(()=>setAudioBlocked(false)).catch(error=>setError(errorText(error)))}>Tap to hear audio</button>}
   {role==='host'&&requests.length>0&&<div className="space-requests"><h3>Requests to speak</h3>{requests.map(item=><div key={item.personId}><span>{item.name}</span><button type="button" disabled={busy} onClick={()=>void respond(item.personId,true)}>Accept</button><button type="button" disabled={busy} onClick={()=>void respond(item.personId,false)}>Decline</button></div>)}</div>}
  </>}{error&&<p className="error" role="alert">{error}</p>}<div ref={audioHost} hidden aria-hidden="true"/></section>;
}
