import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Waveform,X} from '@phosphor-icons/react';
import type {Space} from '../shared/spaces';
import type {Destination} from '../shared/navigation';
import {errorText,operation} from './api';
import {NavLink} from './NavLink';
import {usePanelVisible} from './PanelReadiness';
import {useRecordRefresh} from './useRecordRefresh';
import {useTalk} from './TalkSession';
import {useTalkCompose} from './TalkCompose';
import {SearchField} from './SearchField';
import './spaces.css';

type Navigate=(destination:Destination)=>void;
interface SpacePage {items:Space[];nextCursor:string|null}
const avatar=(name:string,photoId?:string)=><span className="space-avatar">{photoId?<img src={`/api/files/${encodeURIComponent(photoId)}`} alt=""/>:name.replace(/^@/,'').slice(0,1).toUpperCase()}</span>;
const livePhoto=(metadata?:string)=>{try{const value=JSON.parse(metadata||'{}');return typeof value.photoId==='string'?value.photoId:undefined;}catch{return undefined;}};
export function SpacesPanel({spaceId,navigate}:{spaceId?:string;navigate:Navigate}){
 const talk=useTalk(),compose=useTalkCompose(),composing=Boolean(compose?.composing),visible=usePanelVisible(),[list,setList]=useState<SpacePage|null>(null),[space,setSpace]=useState<Space|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [searchQuery,setSearchQuery]=useState(''),[searchNotice,setSearchNotice]=useState(''),[searchBusy,setSearchBusy]=useState(false),[infoOpen,setInfoOpen]=useState(false),searchTerm=useRef('');
 const load=useCallback(async()=>{try{if(spaceId)setSpace(await operation<Space>('spaces.get',{spaceId}));else if(!searchTerm.current)setList(await operation<SpacePage>('spaces.list',{limit:20}));setError('');}catch(cause){setError(errorText(cause));}},[spaceId]);
 useEffect(()=>{setList(null);setSpace(null);setError('');setInfoOpen(false);searchTerm.current='';setSearchQuery('');setSearchNotice('');void load();},[load]);
 useRecordRefresh(['spaces'],load);
 useEffect(()=>{if(!visible)return;const timer=setInterval(()=>void load(),spaceId?10000:20000);return()=>clearInterval(timer);},[visible,spaceId,load]);
 const create=async(event:FormEvent)=>{event.preventDefault();if(!talk||!title.trim()||talk.room||busy)return;setBusy(true);setError('');try{await talk.create(title.trim(),description.trim());setTitle('');setDescription('');compose?.setComposing(false);void load();}catch(cause){setError(errorText(cause));}finally{setBusy(false);}};
 const join=async(id:string,returnToList=false)=>{if(!talk||busy)return;setBusy(true);setError('');try{await talk.join(id);if(returnToList)navigate({view:'spaces'});}catch(cause){setError(errorText(cause));}finally{setBusy(false);}};
 const search=async(query:string,cursor?:string)=>{if(!query){searchTerm.current='';setSearchQuery('');setSearchNotice('');void load();return;}if(searchBusy)return;if(!cursor){searchTerm.current=query;setSearchQuery(query);setList(null);}setSearchBusy(true);setError('');try{const result=await operation<{matches:{record:Space}[];nextCursor:string|null;retrieval:{notices:string[]}}>('search.query',{query,datasets:['spaces'],mode:'hybrid',limit:20,...(cursor?{cursor}:{})});setSearchNotice(result.retrieval.notices.join(' '));const items=result.matches.map(match=>match.record);setList(previous=>cursor&&previous?{items:[...previous.items,...items],nextCursor:result.nextCursor}:{items,nextCursor:result.nextCursor});}catch(cause){setError(errorText(cause));}finally{setSearchBusy(false);}};
 if(!spaceId)return <section className="spaces-browser">{composing?<form className="spaces-compose" onSubmit={event=>void create(event)}><label htmlFor="space-title">Title</label><input id="space-title" value={title} maxLength={100} onChange={event=>setTitle(event.target.value)} autoFocus/><label htmlFor="space-description">Description (optional)</label><textarea id="space-description" value={description} maxLength={500} rows={3} onChange={event=>setDescription(event.target.value)}/><button disabled={busy||!talk||Boolean(talk.room)||!title.trim()}>Open a talk space</button></form>:<>
  <SearchField label="Search by topic" value={searchQuery} onSearch={query=>void search(query)}/>
  <div className="spaces-list">{list?.items.map(item=>{const ended=item.status==='ended',ownRoom=Boolean(talk?.room&&talk.space?.id===item.id&&talk.members.length),speakers=ownRoom?talk!.members.filter(person=>item.speakerIds.includes(person.identity)).map(person=>({id:person.identity,name:person.name||'Member',photoId:livePhoto(person.metadata)})):item.presentSpeakers||[],count=ownRoom?speakers.length:item.speakingCount??0;return <article className="space-list-card" key={item.id}><NavLink className="space-list-open" to={{view:'spaces',resourceId:item.id}} navigate={()=>navigate({view:'spaces',resourceId:item.id})}><span className={ended?'space-ended':'space-live'}>{ended?'ENDED':<><Waveform size={15}/> LIVE</>}</span><strong>{item.title}</strong>{item.description&&<span className="space-list-description">{item.description}</span>}<span>{ended?`${item.hostName} hosted this talk`:`${item.hostName} is hosting`}</span>{!ended&&<span className="space-speaker-peek">{speakers.slice(0,4).map(person=><span key={person.id} title={person.name}>{avatar(person.name,person.photoId)}</span>)}<small>{count} speaking</small></span>}</NavLink>{!ended&&<div className="space-list-actions"><button type="button" className="solid" disabled={busy||!talk} onClick={()=>void join(item.id)}>{talk?.space?.id===item.id?'Open talk space':'Join talk space'}</button></div>}</article>;})}</div>
  {list&&!list.items.length&&<p className="quiet">{searchQuery?'No live talk spaces match that search.':'No talk spaces are live right now.'}</p>}{searchNotice&&<p className="quiet small">{searchNotice}</p>}{list?.nextCursor&&<button type="button" className="text-link" onClick={()=>searchTerm.current?void search(searchTerm.current,list.nextCursor!):void operation<SpacePage>('spaces.list',{limit:20,before:list.nextCursor}).then(page=>setList(current=>current?{items:[...current.items,...page.items],nextCursor:page.nextCursor}:page)).catch(cause=>setError(errorText(cause)))}>More talk spaces</button>}</>}{error&&<p className="error" role="alert">{error}</p>}</section>;
 if(!space)return <section className="talk-preview"><NavLink className="text-link" to={{view:'spaces'}} navigate={()=>navigate({view:'spaces'})}>Back to Talk</NavLink>{error&&<p className="error" role="alert">{error}</p>}</section>;
 const ended=space.status==='ended',starting=space.status==='starting';
 return <section className="talk-preview"><span className={ended?'space-ended':'space-live'}>{ended?'ENDED':starting?'OPENING':<><Waveform size={15}/> LIVE</>}</span><h2>{space.title}</h2><span className="quiet small">{ended?`${space.hostName} hosted this talk`:starting?'Connecting to Talk…':`${space.hostName} is hosting · ${space.speakingCount??0} speaking`}</span>{(space.description||!ended)&&<div className="talk-preview-actions">{space.description&&<button type="button" onClick={()=>setInfoOpen(value=>!value)} aria-expanded={infoOpen}>About</button>}{!ended&&<button type="button" className="solid" disabled={busy||!talk} onClick={()=>void join(space.id,true)}>{talk?.space?.id===space.id?'Open talk space':starting?'Reconnect':'Join talk space'}</button>}</div>}{infoOpen&&<div className="talk-preview-info" role="dialog" aria-label="Talk space description"><button type="button" aria-label="Close description" onClick={()=>setInfoOpen(false)}><X size={18}/></button><p>{space.description}</p></div>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
