import {useEffect,useLayoutEffect,useRef,useState,type PointerEvent,type CSSProperties} from 'react';
import {ArrowCounterClockwise,ArrowClockwise,CircleNotch,Image,Shapes,PaintBrush,Crop} from '@phosphor-icons/react';
import {usePanelVisible} from './PanelReadiness';
import {SquarePainter,squareImage,madeSquare} from './squareRenderer';
import {emptySquare,squareLayer,checkSquare,movedLayer,resizedLayer,transformedLayer,croppedLayer,squareHit,snappedLayer,squareFonts,SQUARE_SIZE,MAX_SQUARE_LAYERS,type SquareProject,type SquareLayer,type SquarePoint} from './squareModel';
import './square.css';

const palette=['#000000','#ffffff','#285ff4','#65c467','#f8ce46','#ec4d3e','#f49c49','#a87ce5','#ff8bc6'];
const replace=(project:SquareProject,layer:SquareLayer)=>({...project,layers:project.layers.map(value=>value.id===layer.id?layer:value)});
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
interface Gesture {original:SquareProject;base:SquareProject;layer:SquareLayer;mode:'move'|'resize'|'transform'|'draw';before:SquarePoint[];moved:boolean}

/** The composition lives only inside the mounted Log editor, never in account storage. */
export function SquareEditor({active,cancel,useImage}:{active:boolean;cancel():void;useImage(file:File):void|Promise<void>}){
 const panelVisible=usePanelVisible(),visible=active&&panelVisible,visibleRef=useRef(visible);visibleRef.current=visible;
 const [project,setProject]=useState<SquareProject>(emptySquare),[selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<string|null>(null),[cropping,setCropping]=useState<string|null>(null);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[side,setSide]=useState(0),[guides,setGuides]=useState({x:false,y:false});
 const [brush,setBrush]=useState(16),[ink,setInk]=useState('#000000'),[erasing,setErasing]=useState(false);
 const latest=useRef(project);latest.current=project;const past=useRef<SquareProject[]>([]),future=useRef<SquareProject[]>([]),textOrigin=useRef<SquareProject|null>(null);
 const painter=useRef<SquarePainter|null>(null);painter.current ||= new SquarePainter();
 const frame=useRef<HTMLDivElement>(null),body=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),picker=useRef<HTMLInputElement>(null),textInput=useRef<HTMLTextAreaElement>(null),images=useRef(new Map<string,HTMLImageElement>());
 const paint=useRef<HTMLCanvasElement|null>(null),paintSource=useRef<string|undefined>(undefined),paintReady=useRef(false),drawPoint=useRef<SquarePoint|null>(null);
 const pointers=useRef(new Map<number,SquarePoint>()),gesture=useRef<Gesture|null>(null),paintFrame=useRef(0),generation=useRef(0),alive=useRef(true);
 const current=project.layers.find(layer=>layer.id===selected)||null,draw=current?.type==='draw';
 const trimHistory=()=>{past.current=past.current.slice(-20);const cost=()=>{const sources=new Set([latest.current,...past.current,...future.current].flatMap(value=>value.layers.flatMap(layer=>layer.src?[layer.src]:[])));return [...sources].reduce((sum,src)=>sum+src.length,0);};while(past.current.length&&cost()>16*1024*1024)past.current.shift();};
 const preview=(next:SquareProject)=>{latest.current=next;setProject(next);};
 const commit=(next:SquareProject,original=latest.current)=>{try{checkSquare(next);if(next!==original){past.current.push(original);future.current=[];}preview(next);trimHistory();setError('');}catch(e){preview(original);setError(e instanceof Error?e.message:'Could not change this image.');}};
 const update=(changes:Partial<SquareLayer>)=>{const layer=latest.current.layers.find(value=>value.id===selected);if(!layer)return;const next=replace(latest.current,{...layer,...changes});if(editing)preview(next);else commit(next);};
 const render=()=>{if(!visibleRef.current||!canvas.current)return;const layer=latest.current.layers.find(value=>value.id===selected),composition=editing?{...latest.current,layers:latest.current.layers.filter(value=>value.id!==editing)}:latest.current;painter.current!.paint(canvas.current,composition,images.current,layer?.type==='draw'&&paintReady.current&&paint.current?{id:layer.id,canvas:paint.current}:undefined);};
 const schedule=()=>{cancelAnimationFrame(paintFrame.current);paintFrame.current=requestAnimationFrame(render);};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;cancelAnimationFrame(paintFrame.current);painter.current?.dispose();if(paint.current)paint.current.width=paint.current.height=0;};},[]);
 useEffect(()=>{if(!visible){pointers.current.clear();if(gesture.current)preview(gesture.current.original);gesture.current=null;drawPoint.current=null;cancelAnimationFrame(paintFrame.current);return;}const revision=++generation.current;setLoading(true);void painter.current!.prepare(project).then(result=>{if(!alive.current||revision!==generation.current)return;images.current=result;setLoading(false);schedule();}).catch(e=>{if(alive.current&&revision===generation.current){setLoading(false);setError(e instanceof Error?e.message:'Could not open this image.');}});},[project,visible,editing,selected]);
 useLayoutEffect(()=>{if(!visible||!body.current)return;const measure=()=>{const node=body.current!;setSide(Math.min(512,node.clientWidth||512,Math.max(140,(node.clientHeight||660)-150)));};measure();const observer=new ResizeObserver(measure);observer.observe(body.current);return()=>observer.disconnect();},[visible,editing,cropping]);
 useLayoutEffect(()=>{if(editing&&visible){textInput.current?.focus({preventScroll:true});textInput.current?.select();}},[editing,visible]);
 useEffect(()=>{if(!draw)return;const layer=current!,source=layer.src;paint.current ||= document.createElement('canvas');const buffer=paint.current;buffer.width=buffer.height=SQUARE_SIZE;paintReady.current=false;paintSource.current=source;
  const ready=()=>{if(!alive.current||paintSource.current!==source)return;paintReady.current=true;schedule();};if(source)void painter.current!.image(source).then(image=>{if(alive.current&&paintSource.current===source){buffer.getContext('2d')?.drawImage(image,0,0,SQUARE_SIZE,SQUARE_SIZE);ready();}}).catch(e=>setError(e.message));else ready();
 },[selected,current?.src,draw]);
 const undo=(redo=false)=>{if(busy||editing)return;const from=redo?future:past,to=redo?past:future,next=from.current.pop();if(next){to.current.push(latest.current);preview(next);setSelected(value=>next.layers.some(layer=>layer.id===value)?value:null);setError('');}};
 const startText=(layer:SquareLayer,next=latest.current,original=latest.current)=>{textOrigin.current=original;setSelected(layer.id);preview(next);setEditing(layer.id);};
 const finishText=(save=true)=>{if(textOrigin.current){if(save)commit(latest.current,textOrigin.current);else preview(textOrigin.current);}textOrigin.current=null;setEditing(null);textInput.current?.blur();};
 const add=async(type:SquareLayer['type'],file?:File)=>{if(busy||loading)return;if(type==='draw'){const old=latest.current.layers.find(layer=>layer.type==='draw');if(old){setSelected(old.id);return;}}if(latest.current.layers.length>=MAX_SQUARE_LAYERS){setError('Use up to 32 layers.');return;}
  try{let data:Partial<SquareLayer>={};if(file){setBusy(true);const image=await squareImage(file);if(!alive.current||!visibleRef.current)return;const empty=!latest.current.layers.length,w=empty?Math.max(1,image.aspect):Math.min(.85,.65*image.aspect),h=empty?Math.max(1,1/image.aspect):w/image.aspect;data={src:image.src,w,h,x:(1-w)/2,y:(1-h)/2};}if(type==='shape')data={x:.25,y:.25,w:.5,h:.5,color:'#285ff4'};
   const layer=squareLayer(type,data),original=latest.current,next={...original,layers:[...original.layers,layer]};if(type==='text')startText({...layer,text:'Text'},replace(next,{...layer,text:'Text'}),original);else{commit(next);setSelected(layer.id);}setError('');
  }catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not add this image.');}finally{if(alive.current)setBusy(false);}
 };
 const point=(event:{clientX:number;clientY:number}):SquarePoint=>{const rect=frame.current!.getBoundingClientRect();return {x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height};};
 const brushTo=(next:SquarePoint)=>{const buffer=paint.current,ctx=buffer?.getContext('2d');if(!ctx||!drawPoint.current)return;ctx.globalCompositeOperation=erasing?'destination-out':'source-over';ctx.strokeStyle=ink;ctx.lineWidth=brush;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(drawPoint.current.x*SQUARE_SIZE,drawPoint.current.y*SQUARE_SIZE);ctx.lineTo(next.x*SQUARE_SIZE+.001,next.y*SQUARE_SIZE+.001);ctx.stroke();drawPoint.current=next;schedule();};
 const down=(event:PointerEvent<HTMLDivElement>,resize=false)=>{
  if(busy||loading||editing||cropping||event.pointerType==='mouse'&&event.button!==0||pointers.current.size>=2)return;const next=point(event);event.stopPropagation();
  if(draw){if(pointers.current.size||!paintReady.current)return;event.preventDefault();pointers.current.set(event.pointerId,next);gesture.current={original:latest.current,base:latest.current,layer:current!,mode:'draw',before:[next],moved:false};drawPoint.current=next;brushTo(next);event.currentTarget.setPointerCapture(event.pointerId);return;}
  const existing=gesture.current;pointers.current.set(event.pointerId,next);
  if(existing){existing.base=latest.current;existing.layer=latest.current.layers.find(layer=>layer.id===existing.layer.id)!;existing.before=[...pointers.current.values()];existing.mode='transform';existing.moved=true;}
  else{const layer=resize?current:[...latest.current.layers].reverse().find(layer=>layer.type!=='draw'&&squareHit(layer,next));if(!layer){pointers.current.delete(event.pointerId);setSelected(null);return;}setSelected(layer.id);gesture.current={original:latest.current,base:latest.current,layer,mode:resize?'resize':'move',before:[next],moved:false};}
  event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);
 };
 const move=(event:PointerEvent<HTMLDivElement>)=>{const g=gesture.current;if(!g||!pointers.current.has(event.pointerId))return;event.preventDefault();const next=point(event);pointers.current.set(event.pointerId,next);if(g.mode==='draw'){brushTo(next);g.moved=true;return;}const after=[...pointers.current.values()],dx=after[0].x-g.before[0].x,dy=after[0].y-g.before[0].y;if(Math.hypot(dx,dy)>.006)g.moved=true;const transformed=g.mode==='transform'?transformedLayer(g.layer,g.before,after):g.mode==='resize'?resizedLayer(g.layer,dx,dy):movedLayer(g.layer,dx,dy),snap=snappedLayer(transformed,frame.current!.clientWidth);setGuides({x:snap.x,y:snap.y});preview(replace(g.base,snap.layer));};
 const up=(event:PointerEvent<HTMLDivElement>,cancelled=false)=>{const g=gesture.current;if(!g||!pointers.current.has(event.pointerId))return;event.preventDefault();event.stopPropagation();pointers.current.delete(event.pointerId);
  if(cancelled){pointers.current.clear();preview(g.original);if(g.mode==='draw'){paintReady.current=false;setSelected(null);}gesture.current=null;drawPoint.current=null;setGuides({x:false,y:false});return;}
  if(pointers.current.size){g.base=latest.current;g.layer=latest.current.layers.find(layer=>layer.id===g.layer.id)!;g.before=[...pointers.current.values()];g.mode='move';return;}
  if(g.mode==='draw'&&paint.current){const next=replace(latest.current,{...g.layer,src:paint.current.toDataURL('image/png')});commit(next,g.original);}
  else if(g.moved)commit(latest.current,g.original);else if(g.layer.type==='text'&&selected===g.layer.id)startText(g.layer);
  gesture.current=null;drawPoint.current=null;setGuides({x:false,y:false});
 };
 const reorder=(front:boolean)=>{if(!current)return;const others=latest.current.layers.filter(layer=>layer.id!==current.id);commit({...latest.current,layers:front?[...others,current]:[current,...others]});};
 const remove=()=>{if(current){commit({...latest.current,layers:latest.current.layers.filter(layer=>layer.id!==current.id)});setSelected(null);}};
 const finish=async()=>{if(busy||loading||gesture.current)return;setBusy(true);setError('');try{const file=await madeSquare(latest.current,painter.current!);if(alive.current&&visibleRef.current)await useImage(file);}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not prepare this image.');}finally{if(alive.current)setBusy(false);}};
 const selectedStyle=current?{left:`${current.x*100}%`,top:`${current.y*100}%`,width:`${current.w*100}%`,height:`${current.h*100}%`,transform:`rotate(${current.angle}deg)`}:undefined;
 const corner=current?{x:current.x+current.w/2+Math.cos(current.angle*Math.PI/180)*current.w/2+Math.sin(current.angle*Math.PI/180)*current.h/2,y:current.y+current.h/2+Math.sin(current.angle*Math.PI/180)*current.w/2-Math.cos(current.angle*Math.PI/180)*current.h/2}:null;
 const handleStyle=corner?{left:`${clamp(corner.x,20/(side||320),1-20/(side||320))*100}%`,top:`${clamp(corner.y,20/(side||320),1-20/(side||320))*100}%`}:undefined;
 const fit=()=>{if(!current?.src)return;const image=images.current.get(current.src);if(!image)return;const aspect=image.naturalWidth/image.naturalHeight,w=aspect>=1?.9:.9*aspect,h=aspect>=1?.9/aspect:.9;update({x:(1-w)/2,y:(1-h)/2,w,h,angle:0,crop:undefined});};
 const colors=<div className="square-palette" aria-label="Colors">{palette.map(color=><button key={color} type="button" aria-label={`Color ${color}`} aria-pressed={(draw?ink:current?.color||project.color)===color} style={{'--swatch':color} as CSSProperties} onClick={()=>{if(draw)setInk(color);else if(current)update({color});else commit({...project,color});}}/>)}<label className="square-custom-color">+<input type="color" aria-label="Custom color" value={draw?ink:current?.color||(project.color==='transparent'?'#000000':project.color)} onChange={event=>{if(draw)setInk(event.target.value);else if(current)update({color:event.target.value});else commit({...project,color:event.target.value});}}/></label></div>;
 const escape=()=>{if(editing)finishText(false);else if(cropping)setCropping(null);else if(selected)setSelected(null);else cancel();};
 return <section className="log-task square-editor" aria-label="Make image" hidden={!active} inert={!active} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();escape();return;}if((event.target as HTMLElement).matches('input,textarea,select'))return;if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo(event.shiftKey);return;}if(event.metaKey||event.ctrlKey||event.altKey||!current)return;if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();remove();}const step=event.shiftKey ? .02 : .005,direction=({ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]} as Record<string,number[]>)[event.key];if(direction){event.preventDefault();commit(replace(project,movedLayer(current,direction[0],direction[1])));}}}>
  <div className="square-editor-body log-task-content" ref={body}>
   {cropping&&current?.src?<SquareCrop layer={current} painter={painter.current!} cancel={()=>setCropping(null)} use={region=>{commit(replace(project,croppedLayer(current,region)));setCropping(null);}}/>:<>
    {!editing&&<div className="square-toolbar panel-actions"><button type="button" aria-label="Add image" title="Add image" disabled={busy} onClick={()=>picker.current?.click()}><Image size={18}/><span className="square-tool-name">Image</span></button><button type="button" aria-label="Add shape" title="Add shape" disabled={busy} onClick={()=>void add('shape')}><Shapes size={18}/><span className="square-tool-name">Shape</span></button><button type="button" aria-label="Add text" title="Add text" disabled={busy} onClick={()=>void add('text')}>Aa</button><button type="button" aria-label="Draw" title="Draw" disabled={busy} aria-pressed={draw} onClick={()=>draw?setSelected(null):void add('draw')}><PaintBrush size={18}/><span className="square-tool-name">Draw</span></button><span className="square-toolbar-gap"/><button type="button" aria-label="Undo" title="Undo" disabled={!past.current.length||busy} onClick={()=>undo()}><ArrowCounterClockwise size={19}/></button><button type="button" aria-label="Redo" title="Redo" disabled={!future.current.length||busy} onClick={()=>undo(true)}><ArrowClockwise size={19}/></button></div>}
    <input type="file" ref={picker} hidden accept="image/jpeg,image/png,image/webp" aria-label="Choose image for square" onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(file)void add('image',file);}}/>
    <div className="square-stage" ref={frame} style={{width:side||undefined,touchAction:draw?'pinch-zoom':'none'}} tabIndex={0} role="group" aria-label="Square canvas. Drag layers, pinch to resize and rotate, or use arrow keys." onPointerDown={down} onPointerMove={move} onPointerUp={event=>up(event)} onPointerCancel={event=>up(event,true)}>
     <canvas ref={canvas} width={512} height={512} aria-label="Image preview"/>
     {current&&!draw&&!editing&&<><div className="square-selection" style={selectedStyle}/><button type="button" className="square-resize" style={handleStyle} aria-label="Resize selected layer" onPointerDown={event=>{event.stopPropagation();down(event as unknown as PointerEvent<HTMLDivElement>,true);}}>↗</button></>}
     {guides.x&&<div className="square-guide square-guide-x"/>}{guides.y&&<div className="square-guide square-guide-y"/>}
     {editing&&current&&<textarea ref={textInput} className="square-text-input" aria-label="Image text" maxLength={1000} value={current.text} style={{color:current.color,fontFamily:squareFonts[current.font],fontWeight:current.bold?700:400,fontStyle:current.italic?'italic':'normal',textAlign:current.align,fontSize:Math.max(16,Math.min(48,(side||320)/8))}} onChange={event=>update({text:event.target.value})}/>}
     {(busy||loading)&&<span className="square-loading" role="status" aria-label={busy?'Preparing image':'Loading image'}><CircleNotch className="spin" size={26}/></span>}
    </div>
    {colors}
    {draw?<div className="square-context panel-actions"><button type="button" aria-pressed={erasing} onClick={()=>setErasing(value=>!value)}>{erasing?'Eraser':'Pen'}</button>{[8,16,32,64].map(size=><button type="button" key={size} aria-label={`Brush size ${size}`} aria-pressed={brush===size} onClick={()=>setBrush(size)}><span className="square-brush-dot" style={{width:size/2,height:size/2}}/></button>)}<button type="button" onClick={()=>setSelected(null)}>Done drawing</button></div>:current?.type==='text'?<div className="square-text-controls panel-actions"><select aria-label="Text font" value={current.font} onChange={event=>update({font:event.target.value as SquareLayer['font']})}>{Object.entries(squareFonts).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select><button type="button" aria-label="Bold text" aria-pressed={current.bold} onClick={()=>update({bold:!current.bold})}><b>B</b></button><button type="button" aria-label="Italic text" aria-pressed={current.italic} onClick={()=>update({italic:!current.italic})}><i>I</i></button><button type="button" aria-label="Text alignment" onClick={()=>update({align:current.align==='left'?'center':current.align==='center'?'right':'left'})}>{current.align}</button>{!editing&&<button type="button" onClick={()=>startText(current)}>Edit text</button>}</div>:current?.type==='image'?<div className="square-context panel-actions"><button type="button" onClick={()=>setCropping(current.id)}><Crop size={17}/>Crop</button><button type="button" onClick={fit}>Fit</button></div>:null}
    {current&&!editing&&!draw&&<div className="square-layer-actions panel-actions"><button type="button" onClick={()=>reorder(true)}>Front</button><button type="button" onClick={()=>reorder(false)}>Back</button><button type="button" disabled={project.layers.length>=MAX_SQUARE_LAYERS} onClick={()=>{const copy={...current,id:crypto.randomUUID(),x:current.x+.03,y:current.y+.03};commit({...project,layers:[...project.layers,copy]});setSelected(copy.id);}}>Duplicate</button><button type="button" onClick={remove}>Delete</button><button type="button" onClick={()=>setSelected(null)}>Done</button></div>}
    {!editing&&<details className="square-style"><summary>{current?'Style':'Background'}</summary>{current?<div className="square-style-fields">
     <label>Opacity<input aria-label="Layer opacity" type="range" min="0" max="1" step=".01" value={current.opacity} onChange={event=>update({opacity:Number(event.target.value)})}/></label>
     {current.type!=='draw'&&<label>Rotation<input aria-label="Layer rotation" type="range" min="-180" max="180" step="1" value={current.angle} onChange={event=>update({angle:Number(event.target.value)})}/></label>}
     {current.type==='shape'||current.type==='image'?<><button type="button" aria-pressed={current.oval} onClick={()=>update({oval:!current.oval})}>Oval</button><button type="button" aria-pressed={current.border} onClick={()=>update({border:!current.border})}>Border</button>{current.border&&<><input type="color" aria-label="Border color" value={current.borderColor} onChange={event=>update({borderColor:event.target.value})}/><input type="range" aria-label="Border width" min="1" max="10" value={current.borderWidth} onChange={event=>update({borderWidth:Number(event.target.value)})}/></>}</>:null}
     {current.type==='text'&&<><button type="button" aria-pressed={current.outline} onClick={()=>update({outline:!current.outline})}>Outline</button>{current.outline&&<><input type="color" aria-label="Outline color" value={current.outlineColor} onChange={event=>update({outlineColor:event.target.value})}/><input type="range" aria-label="Outline width" min="1" max="10" value={current.outlineWidth} onChange={event=>update({outlineWidth:Number(event.target.value)})}/></>}</>}
     <button type="button" aria-pressed={current.shadow} onClick={()=>update({shadow:!current.shadow})}>Shadow</button>{current.shadow&&<><input type="color" aria-label="Shadow color" value={current.shadowColor} onChange={event=>update({shadowColor:event.target.value})}/><label>Across<input type="range" aria-label="Shadow horizontal offset" min="-10" max="10" value={current.shadowX} onChange={event=>update({shadowX:Number(event.target.value)})}/></label><label>Down<input type="range" aria-label="Shadow vertical offset" min="-10" max="10" value={current.shadowY} onChange={event=>update({shadowY:Number(event.target.value)})}/></label></>}
    </div>:<div className="panel-actions"><button type="button" aria-pressed={project.color==='transparent'} onClick={()=>commit({...project,color:project.color==='transparent'?'#ffffff':'transparent'})}>Transparent</button><button type="button" disabled={!project.layers.length} onClick={()=>commit(emptySquare())}>Clear square</button></div>}</details>}
    {project.layers.length>1&&!editing&&<div className="square-layers" aria-label="Layers">{[...project.layers].reverse().map((layer,index)=><button type="button" key={layer.id} aria-pressed={layer.id===selected} onClick={()=>setSelected(layer.id)}>{layer.type==='text'?layer.text||'Text':layer.type==='shape'?(layer.oval?'Oval':'Shape'):layer.type==='draw'?'Drawing':`Image ${project.layers.length-index}`}</button>)}</div>}
   </>}
   {error&&<p className="error" role="alert">{error}</p>}
  </div>
  {!cropping&&<footer className="log-task-footer panel-actions square-footer"><button type="button" onClick={()=>editing?finishText(false):cancel()}>Cancel</button><button type="button" className="solid" disabled={busy||loading} onClick={()=>editing?finishText():void finish()}>{editing?'Done':busy?'Preparing…':'Use image'}</button></footer>}
 </section>;
}

function SquareCrop({layer,painter,cancel,use}:{layer:SquareLayer;painter:SquarePainter;cancel():void;use(region:NonNullable<SquareLayer['crop']>):void}){
 const [region,setRegion]=useState(layer.crop||{x:0,y:0,w:1,h:1}),[aspect,setAspect]=useState(1),frame=useRef<HTMLDivElement>(null),start=useRef<{point:SquarePoint;region:typeof region;corner:'move'|'ne'|'sw'}|null>(null);
 useEffect(()=>{let alive=true;void painter.image(layer.src!).then(image=>{if(alive)setAspect(image.naturalWidth/image.naturalHeight);});return()=>{alive=false;};},[layer.src]);
 const down=(event:PointerEvent<HTMLDivElement>,corner:'move'|'ne'|'sw')=>{event.preventDefault();event.stopPropagation();const rect=frame.current!.getBoundingClientRect();start.current={point:{x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height},region,corner};event.currentTarget.setPointerCapture(event.pointerId);};
 const move=(event:PointerEvent<HTMLDivElement>)=>{const source=start.current;if(!source)return;const rect=frame.current!.getBoundingClientRect(),dx=(event.clientX-rect.left)/rect.width-source.point.x,dy=(event.clientY-rect.top)/rect.height-source.point.y,r=source.region;if(source.corner==='move')setRegion({...r,x:clamp(r.x+dx,0,1-r.w),y:clamp(r.y+dy,0,1-r.h)});else if(source.corner==='ne'){const right=clamp(r.x+r.w+dx,r.x+.01,1),top=clamp(r.y+dy,0,r.y+r.h-.01);setRegion({x:r.x,y:top,w:right-r.x,h:r.y+r.h-top});}else{const left=clamp(r.x+dx,0,r.x+r.w-.01),bottom=clamp(r.y+r.h+dy,r.y+.01,1);setRegion({x:left,y:r.y,w:r.x+r.w-left,h:bottom-r.y});}};
 return <section className="square-crop" aria-label="Crop layer"><div ref={frame} className="square-crop-frame" style={{aspectRatio:aspect}} onPointerMove={move} onPointerUp={()=>{start.current=null;}} onPointerCancel={()=>{start.current=null;}}><img src={layer.src} alt="Image to crop" draggable={false}/><div className="square-crop-mask" style={{left:`${region.x*100}%`,top:`${region.y*100}%`,width:`${region.w*100}%`,height:`${region.h*100}%`}} onPointerDown={event=>down(event,'move')}><div className="square-crop-handle square-crop-ne" role="button" aria-label="Crop upper right corner" onPointerDown={event=>down(event,'ne')}/><div className="square-crop-handle square-crop-sw" role="button" aria-label="Crop lower left corner" onPointerDown={event=>down(event,'sw')}/></div></div><div className="panel-actions"><button type="button" onClick={()=>setRegion({x:0,y:0,w:1,h:1})}>Reset crop</button></div><footer className="log-task-footer panel-actions square-footer"><button type="button" onClick={cancel}>Cancel</button><button type="button" className="solid" onClick={()=>use(region)}>Use crop</button></footer></section>;
}
