import {TransientError} from './TransientError';
import {useEffect,useLayoutEffect,useRef,useState,type DragEvent,type PointerEvent,type CSSProperties} from 'react';
import {ArrowCounterClockwise,ArrowClockwise,ArrowDown,ArrowUp,ArrowsOutSimple,Check,CircleNotch,CopySimple,Eraser,FadersHorizontal,Image,PencilSimple,SelectionSlash,Shapes,PaintBrush,Crop,Shuffle,TextAa,TextAlignCenter,TextAlignLeft,TextAlignRight,Trash,X} from '@phosphor-icons/react';
import {usePanelVisible} from './PanelReadiness';
import {SquarePainter,squareImage,madeSquare} from './squareRenderer';
import {ensureSquareFonts} from './squareFonts';
import {SquareFontPicker} from './SquareFontPicker';
import {emptySquare,squareLayer,checkSquare,movedLayer,resizedLayer,transformedLayer,croppedLayer,squareHit,snappedLayer,squareFonts,SQUARE_SIZE,MAX_SQUARE_LAYERS,type SquareProject,type SquareLayer,type SquarePoint} from './squareModel';
import './square.css';

const palette=['#000000','#ffffff','#285ff4','#65c467','#f8ce46','#ec4d3e','#f49c49','#a87ce5','#ff8bc6'];
const replace=(project:SquareProject,layer:SquareLayer)=>({...project,layers:project.layers.map(value=>value.id===layer.id?layer:value)});
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
const sliderFill=(value:number,min:number,max:number):CSSProperties=>({'--square-range-progress':`${(value-min)/(max-min)*100}%`} as CSSProperties);
const readableBacking=(color:string)=>{const hex=color.slice(1),full=hex.length===3?[...hex].map(value=>value+value).join(''):hex,r=parseInt(full.slice(0,2),16),g=parseInt(full.slice(2,4),16),b=parseInt(full.slice(4,6),16);return (r*299+g*587+b*114)/1000<140?'#ffffff':'#000000';};
const randomColor=()=>`#${Math.floor(Math.random()*0x1000000).toString(16).padStart(6,'0')}`;
async function droppedImage(url:string){
 let source:URL;try{source=new URL(url);}catch{throw Error('Drop an image file or image link.');}if(source.protocol!=='https:'&&source.protocol!=='http:')throw Error('Drop an image file or image link.');
 let response:Response;try{response=await fetch(source.href,{mode:'cors',credentials:'omit',referrerPolicy:'no-referrer'});}catch{throw Error('Could not open that image link. Save the image and upload it instead.');}const limit=12*1024*1024;
 if(!response.ok||!response.body)throw Error('Could not open that image link. Save the image and upload it instead.');
 if(Number(response.headers.get('content-length'))>limit)throw Error('Choose an image smaller than 12 MB.');
 const reader=response.body.getReader(),chunks:ArrayBuffer[]=[];let size=0;
 try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw Error('Choose an image smaller than 12 MB.');}const chunk=new Uint8Array(value.byteLength);chunk.set(value);chunks.push(chunk.buffer);}}finally{reader.releaseLock();}
 return new File(chunks,'Dropped image',{type:response.headers.get('content-type')?.split(';')[0]||'application/octet-stream'});
}
interface Gesture {original:SquareProject;base:SquareProject;layer:SquareLayer;mode:'move'|'resize'|'transform'|'draw';before:SquarePoint[];moved:boolean}

/** The composition lives only inside the mounted Log editor, never in account storage. */
export function SquareEditor({active,cancel,useImage}:{active:boolean;cancel():void;useImage(file:File):void|Promise<void>}){
 const panelVisible=usePanelVisible(),visible=active&&panelVisible,visibleRef=useRef(visible);visibleRef.current=visible;
 const [project,setProject]=useState<SquareProject>(emptySquare),[selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<string|null>(null),[cropping,setCropping]=useState<string|null>(null),[placingText,setPlacingText]=useState(false);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[side,setSide]=useState(0),[guides,setGuides]=useState({x:false,y:false}),[moreOpen,setMoreOpen]=useState(false),[clearPending,setClearPending]=useState(false);
 const [brush,setBrush]=useState(16),[ink,setInk]=useState('#000000'),[customColor,setCustomColor]=useState('#285ff4'),[erasing,setErasing]=useState(false);
 const [drawColors,setDrawColors]=useState([...palette]),[drawColorIndex,setDrawColorIndex]=useState(0);
 const latest=useRef(project);latest.current=project;const past=useRef<SquareProject[]>([]),future=useRef<SquareProject[]>([]),textOrigin=useRef<SquareProject|null>(null);
 const textBackings=useRef(new Map<string,string>());
 const painter=useRef<SquarePainter|null>(null);painter.current ||= new SquarePainter();
 const frame=useRef<HTMLDivElement>(null),canvasColumn=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),picker=useRef<HTMLInputElement>(null),textInput=useRef<HTMLTextAreaElement>(null),images=useRef(new Map<string,HTMLImageElement>());
 const paint=useRef<HTMLCanvasElement|null>(null),paintSource=useRef<string|undefined>(undefined),paintReady=useRef(false),drawPoint=useRef<SquarePoint|null>(null);
 const pointers=useRef(new Map<number,SquarePoint>()),gesture=useRef<Gesture|null>(null),paintFrame=useRef(0),generation=useRef(0),alive=useRef(true),prepared=useRef<SquareProject|null>(null);
 const current=project.layers.find(layer=>layer.id===selected)||null,draw=current?.type==='draw';
 const AlignIcon=current?.align==='center'?TextAlignCenter:current?.align==='right'?TextAlignRight:TextAlignLeft;
 const textLayout=editing&&current?.type==='text'?painter.current!.layoutText(current):null,stagePixels=frame.current?.clientWidth||side||320;
 const textFontSize=textLayout?Math.max(16,textLayout.size*stagePixels/SQUARE_SIZE):16,textPadTop=textLayout&&current?Math.max(0,(current.h*SQUARE_SIZE-textLayout.lines.length*textLayout.size*1.1)*stagePixels/(2*SQUARE_SIZE)):0;
 const trimHistory=()=>{past.current=past.current.slice(-20);const cost=()=>{const sources=new Set([latest.current,...past.current,...future.current].flatMap(value=>value.layers.flatMap(layer=>layer.src?[layer.src]:[])));return [...sources].reduce((sum,src)=>sum+src.length,0);};while(past.current.length&&cost()>16*1024*1024)past.current.shift();};
 const preview=(next:SquareProject)=>{latest.current=next;setProject(next);};
 const commit=(next:SquareProject,original=latest.current)=>{try{checkSquare(next);if(next!==original){past.current.push(original);future.current=[];}preview(next);trimHistory();setError('');}catch(e){preview(original);setError(e instanceof Error?e.message:'Could not change this image.');}};
 const update=(changes:Partial<SquareLayer>)=>{const layer=latest.current.layers.find(value=>value.id===selected);if(!layer)return;const next=replace(latest.current,{...layer,...changes});if(editing)preview(next);else commit(next);};
 const render=()=>{if(!visibleRef.current||!canvas.current)return;try{const layer=latest.current.layers.find(value=>value.id===selected);painter.current!.paint(canvas.current,latest.current,images.current,layer?.type==='draw'&&paintReady.current&&paint.current?{id:layer.id,canvas:paint.current}:undefined);}catch(e){setError(e instanceof Error?e.message:'Could not show this image.');}};
 const schedule=()=>{cancelAnimationFrame(paintFrame.current);paintFrame.current=requestAnimationFrame(render);};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;cancelAnimationFrame(paintFrame.current);painter.current?.dispose();if(paint.current)paint.current.width=paint.current.height=0;};},[]);
 useEffect(()=>{if(visible)void ensureSquareFonts().catch(e=>{if(alive.current)setError(e instanceof Error?e.message:'Could not load image fonts.');});},[visible]);
 useEffect(()=>{if(!visible){generation.current++;prepared.current=null;pointers.current.clear();if(gesture.current)preview(gesture.current.original);gesture.current=null;drawPoint.current=null;cancelAnimationFrame(paintFrame.current);return;}
  const before=prepared.current,resourcesChanged=!before||before.layers.length!==project.layers.length||project.layers.some((layer,index)=>{const prior=before.layers[index];return layer.src!==prior?.src||layer.type==='text'&&(prior.type!=='text'||layer.font!==prior.font||layer.bold!==prior.bold||layer.italic!==prior.italic);});
  if(!resourcesChanged){schedule();return;}prepared.current=project;const revision=++generation.current;setLoading(true);void painter.current!.prepare(project).then(result=>{if(!alive.current||revision!==generation.current)return;images.current=result;setLoading(false);schedule();}).catch(e=>{if(alive.current&&revision===generation.current){setLoading(false);setError(e instanceof Error?e.message:'Could not open this image.');}});
 },[project,visible,editing,selected]);
 useLayoutEffect(()=>{if(!visible||!canvasColumn.current)return;const column=canvasColumn.current,measure=()=>setSide(Math.min(512,column.clientWidth));measure();const observer=new ResizeObserver(measure);observer.observe(column);return()=>observer.disconnect();},[visible,cropping]);
 useLayoutEffect(()=>{if(editing&&visible){textInput.current?.focus({preventScroll:true});textInput.current?.select();}},[editing,visible]);
 useEffect(()=>{setClearPending(false);setMoreOpen(false);},[selected]);
 useEffect(()=>{if(!draw)return;const layer=current!,source=layer.src;paint.current ||= document.createElement('canvas');const buffer=paint.current;buffer.width=buffer.height=SQUARE_SIZE;paintReady.current=false;paintSource.current=source;
  const ready=()=>{if(!alive.current||paintSource.current!==source)return;paintReady.current=true;schedule();};if(source)void painter.current!.image(source).then(image=>{if(alive.current&&paintSource.current===source){buffer.getContext('2d')?.drawImage(image,0,0,SQUARE_SIZE,SQUARE_SIZE);ready();}}).catch(e=>setError(e.message));else ready();
 },[selected,current?.src,draw]);
 const undo=(redo=false)=>{if(busy)return;if(editing)finishText(true);const from=redo?future:past,to=redo?past:future,next=from.current.pop();if(next){to.current.push(latest.current);preview(next);setSelected(value=>next.layers.some(layer=>layer.id===value)?value:null);setError('');}};
 const startText=(layer:SquareLayer,next=latest.current,original=latest.current)=>{textOrigin.current=original;setSelected(layer.id);preview(next);setEditing(layer.id);};
 const placeText=(where:SquarePoint)=>{if(latest.current.layers.length>=MAX_SQUARE_LAYERS){setError('Use up to 32 layers.');setPlacingText(false);return;}const layer=squareLayer('text',{x:where.x-.25,y:where.y-.1,w:.5,h:.2,align:'center',text:''}),original=latest.current;startText(layer,{...original,layers:[...original.layers,layer]},original);setPlacingText(false);};
 const finishText=(save=true)=>{if(textOrigin.current){const next=save&&editing&&!latest.current.layers.find(layer=>layer.id===editing)?.text.trim()?{...latest.current,layers:latest.current.layers.filter(layer=>layer.id!==editing)}:latest.current;if(save)commit(next,textOrigin.current);else preview(textOrigin.current);if(save&&editing&&!next.layers.some(layer=>layer.id===editing))setSelected(null);}textOrigin.current=null;setEditing(null);textInput.current?.blur();};
 const add=async(type:SquareLayer['type'],file?:File|string)=>{if(busy||loading)return;if(type==='draw'){const old=latest.current.layers.find(layer=>layer.type==='draw');if(old){setSelected(old.id);return;}}if(latest.current.layers.length>=MAX_SQUARE_LAYERS){setError('Use up to 32 layers.');return;}
  try{let data:Partial<SquareLayer>={};if(file){setBusy(true);const image=await squareImage(typeof file==='string'?await droppedImage(file):file);if(!alive.current||!visibleRef.current)return;const empty=!latest.current.layers.length,w=empty?Math.max(1,image.aspect):Math.min(.85,.65*image.aspect),h=empty?Math.max(1,1/image.aspect):w/image.aspect;data={src:image.src,w,h,x:(1-w)/2,y:(1-h)/2};}if(type==='shape')data={x:.25,y:.25,w:.5,h:.5,color:'#285ff4'};
   const layer=squareLayer(type,data),original=latest.current,next={...original,layers:[...original.layers,layer]};if(type==='text')startText({...layer,text:'Text'},replace(next,{...layer,text:'Text'}),original);else{commit(next);setSelected(layer.id);}setError('');
  }catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not add this image.');}finally{if(alive.current)setBusy(false);}
 };
 const point=(event:{clientX:number;clientY:number}):SquarePoint=>{const rect=frame.current!.getBoundingClientRect();return {x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height};};
 const brushTo=(next:SquarePoint)=>{const buffer=paint.current,ctx=buffer?.getContext('2d');if(!ctx||!drawPoint.current)return;ctx.globalCompositeOperation=erasing?'destination-out':'source-over';ctx.strokeStyle=ink;ctx.lineWidth=brush;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(drawPoint.current.x*SQUARE_SIZE,drawPoint.current.y*SQUARE_SIZE);ctx.lineTo(next.x*SQUARE_SIZE+.001,next.y*SQUARE_SIZE+.001);ctx.stroke();drawPoint.current=next;schedule();};
 const down=(event:PointerEvent<HTMLDivElement>,resize=false)=>{
  if(busy||loading||cropping||event.pointerType==='mouse'&&event.button!==0||pointers.current.size>=2)return;const next=point(event);event.stopPropagation();if(editing){const layer=latest.current.layers.find(value=>value.id===editing);if(layer&&squareHit(layer,next))return;finishText(true);}if(placingText){event.preventDefault();placeText(next);return;}
  if(draw){if(pointers.current.size){const existing=gesture.current;if(existing){preview(existing.original);gesture.current=null;drawPoint.current=null;setSelected(null);setGuides({x:false,y:false});}pointers.current.clear();return;}if(!paintReady.current)return;event.preventDefault();pointers.current.set(event.pointerId,next);gesture.current={original:latest.current,base:latest.current,layer:current!,mode:'draw',before:[next],moved:false};drawPoint.current=next;brushTo(next);event.currentTarget.setPointerCapture(event.pointerId);return;}
  const existing=gesture.current;pointers.current.set(event.pointerId,next);
  if(existing){existing.base=latest.current;existing.layer=latest.current.layers.find(layer=>layer.id===existing.layer.id)!;existing.before=[...pointers.current.values()];existing.mode='transform';existing.moved=true;}
  else{const layer=resize?current:[...latest.current.layers].reverse().find(layer=>layer.type!=='draw'&&squareHit(layer,next));if(!layer){pointers.current.delete(event.pointerId);setSelected(null);return;}setSelected(layer.id);gesture.current={original:latest.current,base:latest.current,layer,mode:resize?'resize':'move',before:[next],moved:false};}
  event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);
 };
 const move=(event:PointerEvent<HTMLDivElement>)=>{const g=gesture.current;if(!g||!pointers.current.has(event.pointerId))return;event.preventDefault();const next=point(event);pointers.current.set(event.pointerId,next);if(g.mode==='draw'){brushTo(next);g.moved=true;return;}const after=[...pointers.current.values()],dx=after[0].x-g.before[0].x,dy=after[0].y-g.before[0].y;if(Math.hypot(dx,dy)>.006)g.moved=true;const transformed=g.mode==='transform'?transformedLayer(g.layer,g.before,after):g.mode==='resize'?resizedLayer(g.layer,dx,dy):movedLayer(g.layer,dx,dy),snap=snappedLayer(transformed,frame.current!.clientWidth);setGuides({x:snap.x,y:snap.y});preview(replace(g.base,snap.layer));};
 const up=(event:PointerEvent<HTMLDivElement>,cancelled=false)=>{const g=gesture.current;if(!g||!pointers.current.has(event.pointerId))return;event.preventDefault();event.stopPropagation();pointers.current.delete(event.pointerId);
  if(cancelled){pointers.current.clear();preview(g.original);if(g.mode==='draw'){paintReady.current=false;setSelected(null);}gesture.current=null;drawPoint.current=null;setGuides({x:false,y:false});return;}
  if(pointers.current.size){g.base=latest.current;g.layer=latest.current.layers.find(layer=>layer.id===g.layer.id)!;g.before=[...pointers.current.values()];g.mode='move';return;}
  if(g.mode==='draw'&&paint.current){const next=replace(latest.current,{...g.layer,src:paint.current.toDataURL('image/png')});commit(next,g.original);}
  else if(g.moved)commit(latest.current,g.original);
  gesture.current=null;drawPoint.current=null;setGuides({x:false,y:false});
 };
 const reorder=(front:boolean)=>{if(editing)finishText(true);const layer=latest.current.layers.find(value=>value.id===selected);if(!layer)return;const others=latest.current.layers.filter(value=>value.id!==layer.id);commit({...latest.current,layers:front?[...others,layer]:[layer,...others]});};
 const duplicate=()=>{if(editing)finishText(true);const layer=latest.current.layers.find(value=>value.id===selected);if(!layer)return;const copy={...layer,id:crypto.randomUUID(),x:layer.x+.03,y:layer.y+.03};commit({...latest.current,layers:[...latest.current.layers,copy]});setSelected(copy.id);};
 const remove=()=>{if(editing)finishText(true);const layer=latest.current.layers.find(value=>value.id===selected);if(layer)commit({...latest.current,layers:latest.current.layers.filter(value=>value.id!==layer.id)});setSelected(null);};
 const deselect=()=>{if(editing)finishText(true);setSelected(null);};
 const finish=async()=>{if(busy||loading||gesture.current||placingText||cropping)return;if(editing)finishText(true);setBusy(true);setError('');try{const file=await madeSquare(latest.current,painter.current!);if(alive.current&&visibleRef.current)await useImage(file);}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not prepare this image.');}finally{if(alive.current)setBusy(false);}};
 const selectedStyle=current?{left:`${current.x*100}%`,top:`${current.y*100}%`,width:`${current.w*100}%`,height:`${current.h*100}%`,transform:`rotate(${current.angle}deg)`}:undefined;
 const corner=current?{x:current.x+current.w/2+Math.cos(current.angle*Math.PI/180)*current.w/2+Math.sin(current.angle*Math.PI/180)*current.h/2,y:current.y+current.h/2+Math.sin(current.angle*Math.PI/180)*current.w/2-Math.cos(current.angle*Math.PI/180)*current.h/2}:null;
 const handlePixels=frame.current?.clientWidth||side||320,handleStyle=corner?{left:`${clamp(corner.x,20/handlePixels,1-20/handlePixels)*100}%`,top:`${clamp(corner.y,20/handlePixels,1-20/handlePixels)*100}%`}:undefined;
 const fit=()=>{if(current?.src)update({x:0,y:0,w:1,h:1,angle:0});};
 const setDrawColor=(color:string)=>{setDrawColors(values=>values.map((value,index)=>index===drawColorIndex?color:value));setInk(color);};
 const chooseColor=(color:string,random=false)=>{if(draw)setDrawColor(color);else if(current)update({color,...(random&&current.type==='text'&&current.background!=='transparent'?{background:readableBacking(color)}:{})});else commit({...latest.current,color});};
 const setBacking=(color:string)=>{if(current?.type!=='text')return;textBackings.current.set(current.id,color);update({background:color});};
 const toggleBacking=()=>{if(current?.type!=='text')return;if(current.background==='transparent')setBacking(textBackings.current.get(current.id)||readableBacking(current.color));else{textBackings.current.set(current.id,current.background);update({background:'transparent'});}};
 const drop=(event:DragEvent<HTMLElement>)=>{if(!event.dataTransfer.types.includes('Files')&&!event.dataTransfer.types.includes('text/uri-list'))return;event.preventDefault();if(busy||loading||cropping)return;const file=event.dataTransfer.files[0],uri=event.dataTransfer.getData('text/uri-list').split(/\r?\n/).find(value=>value&&!value.startsWith('#'));if(!file&&!uri)return;if(editing)finishText(true);setPlacingText(false);void add('image',file||uri);};
 const colors=<div className="square-palette" aria-label={draw?'Drawing colors':'Colors'}>{(draw?drawColors:palette).map((color,index)=><button key={index} type="button" aria-label={`Color ${color}`} aria-pressed={draw?drawColorIndex===index:(current?.color||project.color)===color} style={{'--swatch':color} as CSSProperties} onClick={()=>{if(draw){setDrawColorIndex(index);setInk(color);}else chooseColor(color);}}/>)}<label className="square-custom-color"><input type="color" aria-label={draw?'Edit drawing swatch':'Custom color'} value={draw?drawColors[drawColorIndex]:customColor} onClick={()=>{if(!draw&&(current?.color||project.color)!==customColor)chooseColor(customColor);}} onChange={event=>{if(draw)setDrawColor(event.target.value);else{setCustomColor(event.target.value);chooseColor(event.target.value);}}}/></label><button type="button" className="square-palette-random" aria-label="Random color" title="Random color" onClick={()=>chooseColor(randomColor(),true)}><Shuffle size={18}/></button></div>;
 const escape=()=>{if(editing)finishText(false);else if(cropping)setCropping(null);else if(placingText)setPlacingText(false);else if(selected)setSelected(null);else cancel();};
 return <section className="log-task square-editor" aria-label="Make image" hidden={!active} inert={!active} onDragOver={event=>{if(event.dataTransfer.types.includes('Files')||event.dataTransfer.types.includes('text/uri-list')){event.preventDefault();event.dataTransfer.dropEffect='copy';}}} onDrop={drop} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();escape();return;}if(placingText&&event.target===frame.current&&(event.key==='Enter'||event.key===' ')){event.preventDefault();placeText({x:.5,y:.5});return;}if((event.target as HTMLElement).matches('input,textarea,select'))return;if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo(event.shiftKey);return;}if(event.metaKey||event.ctrlKey||event.altKey||!current)return;if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();remove();}const step=event.shiftKey ? .02 : .005,direction=({ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]} as Record<string,number[]>)[event.key];if(direction){event.preventDefault();commit(replace(project,movedLayer(current,direction[0],direction[1])));}}}>
  <div className="square-editor-body log-task-content">
    <input type="file" ref={picker} hidden accept="image/jpeg,image/png,image/webp" aria-label="Choose image for square" onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(file)void add('image',file);}}/>
    <div className="square-toolbar panel-actions"><button type="button" aria-label="Add image" title="Add image" disabled={busy||Boolean(cropping)} onClick={()=>{if(editing)finishText(true);setPlacingText(false);picker.current?.click();}}><Image size={18}/><span className="square-tool-name">Image</span></button><button type="button" aria-label="Add shape" title="Add shape" disabled={busy||Boolean(cropping)} onClick={()=>{if(editing)finishText(true);setPlacingText(false);void add('shape');}}><Shapes size={18}/><span className="square-tool-name">Shape</span></button><button type="button" aria-label="Add text" title="Add text" disabled={busy||Boolean(cropping)} aria-pressed={placingText} onClick={()=>{if(editing)finishText(true);setSelected(null);setPlacingText(value=>!value);}}><TextAa size={18}/><span className="square-tool-name">Text</span></button><button type="button" aria-label="Draw" title="Draw" disabled={busy||Boolean(cropping)} aria-pressed={draw} onClick={()=>{if(editing)finishText(true);setPlacingText(false);if(draw)setSelected(null);else void add('draw');}}><PaintBrush size={18}/><span className="square-tool-name">Draw</span></button><span className="square-toolbar-gap"/><button type="button" aria-label="Undo" title="Undo" disabled={busy||Boolean(cropping)||(!past.current.length&&!editing)} onClick={()=>undo()}><ArrowCounterClockwise size={19}/></button><button type="button" aria-label="Redo" title="Redo" disabled={!future.current.length||busy||Boolean(editing)||Boolean(cropping)} onClick={()=>undo(true)}><ArrowClockwise size={19}/></button></div>
   {cropping&&current?.src?<SquareCrop layer={current} painter={painter.current!} cancel={()=>setCropping(null)} use={region=>{commit(replace(project,croppedLayer(current,region)));setCropping(null);}}/>:<>
    <div className="square-workspace"><div className="square-canvas-column" ref={canvasColumn}><div className="square-stage" ref={frame} style={{width:side||undefined,touchAction:draw?'pinch-zoom':'none'}} tabIndex={0} role="group" aria-label="Image canvas" data-placing-text={placingText||undefined} onPointerDown={down} onPointerMove={move} onPointerUp={event=>up(event)} onPointerCancel={event=>up(event,true)}>
     <canvas ref={canvas} width={512} height={512} aria-label="Image preview"/>
     {current&&!draw&&<div className="square-selection" style={selectedStyle}/>} {current&&!draw&&!editing&&<button type="button" className="square-resize" style={handleStyle} aria-label="Resize selected layer" onPointerDown={event=>{event.stopPropagation();down(event as unknown as PointerEvent<HTMLDivElement>,true);}}><ArrowsOutSimple size={18}/></button>}
     {guides.x&&<div className="square-guide square-guide-x"/>}{guides.y&&<div className="square-guide square-guide-y"/>}
    {editing&&current&&<textarea ref={textInput} className="square-text-input" aria-label="Image text" maxLength={1000} value={current.text} style={{...selectedStyle,color:'transparent',caretColor:current.color,fontFamily:squareFonts[current.font],fontWeight:current.bold?700:400,fontStyle:current.italic?'italic':'normal',textAlign:current.align,fontSize:textFontSize,paddingTop:textPadTop}} onChange={event=>update({text:event.target.value})}/>}
     {(busy||loading)&&<span className="square-loading" role="status" aria-label={busy?'Preparing image':'Loading image'}><CircleNotch className="spin" size={26}/></span>}
    </div>
    </div><div className="square-inspector">
    {!moreOpen&&current?.type!=='image'&&colors}
    {!moreOpen&&(draw?<div className="square-context square-draw-controls panel-actions"><button type="button" aria-label={erasing?'Use pen':'Use eraser'} aria-pressed={erasing} onClick={()=>setErasing(value=>!value)}>{erasing?<Eraser size={18}/>:<PencilSimple size={18}/>}<span className="square-tool-name">{erasing?'Eraser':'Pen'}</span></button>{[8,16,32,64].map(size=><button type="button" key={size} aria-label={`Brush size ${size}`} aria-pressed={brush===size} onClick={()=>setBrush(size)}><span className="square-brush-dot" style={{width:size/2,height:size/2}}/></button>)}<button type="button" aria-label="Reset drawing swatch" disabled={drawColors[drawColorIndex]===palette[drawColorIndex]} onClick={()=>setDrawColor(palette[drawColorIndex])}><ArrowCounterClockwise size={18}/><span className="square-tool-name">Reset</span></button></div>:current?.type==='text'?<div className="square-text-controls panel-actions"><SquareFontPicker value={current.font} change={font=>update({font})} active={visible&&!cropping}/><button type="button" aria-label="Bold text" aria-pressed={current.bold} onClick={()=>update({bold:!current.bold})}><b>B</b></button><button type="button" aria-label="Italic text" aria-pressed={current.italic} onClick={()=>update({italic:!current.italic})}><i>I</i></button><button type="button" aria-label="Text alignment" title={`Align ${current.align}`} onClick={()=>update({align:current.align==='left'?'center':current.align==='center'?'right':'left'})}><AlignIcon className="square-action-icon" size={18}/><span className="square-action-name">{current.align}</span></button><button type="button" aria-label={editing?"End edit":"Edit text"} onClick={()=>editing?finishText(true):startText(current)}>{editing?<Check className="square-action-icon" size={18}/>:<TextAa className="square-action-icon" size={18}/>}<span className="square-action-name">{editing?"End edit":"Edit text"}</span></button></div>:current?.type==='image'?<div className="square-context panel-actions"><button type="button" onClick={()=>setCropping(current.id)}><Crop size={17}/>Crop</button><button type="button" onClick={fit}><ArrowsOutSimple size={17}/>Fill frame</button></div>:null)}
    {current&&<div className="square-layer-actions panel-actions">{!moreOpen&&<><button type="button" aria-label="Bring to front" title="Bring to front" onClick={()=>reorder(true)}><ArrowUp className="square-action-icon" size={18}/><span className="square-action-name">Front</span></button><button type="button" aria-label="Send to back" title="Send to back" onClick={()=>reorder(false)}><ArrowDown className="square-action-icon" size={18}/><span className="square-action-name">Back</span></button>{!draw&&<button type="button" aria-label="Duplicate layer" title="Duplicate layer" disabled={project.layers.length>=MAX_SQUARE_LAYERS} onClick={duplicate}><CopySimple className="square-action-icon" size={18}/><span className="square-action-name">Dupe</span></button>}<button type="button" aria-label="Delete layer" title="Delete layer" onClick={remove}><Trash className="square-action-icon" size={18}/><span className="square-action-name">Delete</span></button><button type="button" aria-label="Deselect layer" title="Deselect layer" onClick={deselect}><SelectionSlash className="square-action-icon" size={18}/><span className="square-action-name">Deselect</span></button></>}{current.type!=='shape'&&<button type="button" aria-label="More options" title="More options" aria-expanded={moreOpen} onClick={()=>{if(editing)finishText(true);setMoreOpen(value=>!value);}}><FadersHorizontal className="square-action-icon" size={18}/><span className="square-action-name">More</span></button>}</div>}
    {current&&(moreOpen||current.type==='shape')&&<div className="square-style-fields">
     <label>Opacity<input aria-label="Layer opacity" type="range" min="0" max="1" step=".01" value={current.opacity} style={sliderFill(current.opacity,0,1)} onChange={event=>update({opacity:Number(event.target.value)})}/></label>
     {current.type!=='draw'&&<label>Rotation<input aria-label="Layer rotation" type="range" min="-180" max="180" step="1" value={current.angle} style={sliderFill(current.angle,-180,180)} onChange={event=>update({angle:Number(event.target.value)})}/></label>}
     {current.type==='text'&&<div className="square-style-toggle-row"><button type="button" aria-pressed={current.background!=='transparent'} onClick={toggleBacking}>Background</button>{current.background!=='transparent'&&<input type="color" aria-label="Text background color" value={current.background} onChange={event=>setBacking(event.target.value)}/>}</div>}
     {(current.type==='shape'||current.type==='image')&&<><div className="square-style-toggle-row"><button type="button" aria-pressed={current.oval} onClick={()=>update({oval:!current.oval})}>Oval</button></div><div className="square-style-toggle-row"><button type="button" aria-pressed={current.border} onClick={()=>update({border:!current.border})}>Border</button>{current.border&&<input type="color" aria-label="Border color" value={current.borderColor} onChange={event=>update({borderColor:event.target.value})}/>}</div>{current.border&&<label>Border width<input type="range" aria-label="Border width" min="1" max="10" value={current.borderWidth} style={sliderFill(current.borderWidth,1,10)} onChange={event=>update({borderWidth:Number(event.target.value)})}/></label>}</>}
     {current.type==='text'&&<><div className="square-style-toggle-row"><button type="button" aria-pressed={current.outline} onClick={()=>update({outline:!current.outline})}>Outline</button>{current.outline&&<input type="color" aria-label="Outline color" value={current.outlineColor} onChange={event=>update({outlineColor:event.target.value})}/>}</div>{current.outline&&<label>Outline width<input type="range" aria-label="Outline width" min="1" max="10" value={current.outlineWidth} style={sliderFill(current.outlineWidth,1,10)} onChange={event=>update({outlineWidth:Number(event.target.value)})}/></label>}</>}
     <div className="square-style-toggle-row"><button type="button" aria-pressed={current.shadow} onClick={()=>update({shadow:!current.shadow})}>Shadow</button>{current.shadow&&<input type="color" aria-label="Shadow color" value={current.shadowColor} onChange={event=>update({shadowColor:event.target.value})}/>}</div>{current.shadow&&<><label>Across<input type="range" aria-label="Shadow horizontal offset" min="-64" max="64" value={current.shadowX} style={sliderFill(current.shadowX,-64,64)} onChange={event=>update({shadowX:Number(event.target.value)})}/></label><label>Down<input type="range" aria-label="Shadow vertical offset" min="-64" max="64" value={current.shadowY} style={sliderFill(current.shadowY,-64,64)} onChange={event=>update({shadowY:Number(event.target.value)})}/></label></>}
    </div>}
    {!editing&&!current&&project.layers.length>0&&(clearPending?<div className="square-clear-confirm"><button type="button" onClick={()=>setClearPending(false)}>Cancel</button><button type="button" onClick={()=>{commit(emptySquare());setClearPending(false);}}>Confirm clear</button></div>:<button type="button" className="square-clear" onClick={()=>setClearPending(true)}><Trash size={18}/>Clear all</button>)}
    {project.layers.length>1&&!editing&&!moreOpen&&<div className="square-layers" aria-label="Layers">{[...project.layers].reverse().map((layer,index)=><button type="button" key={layer.id} aria-pressed={layer.id===selected} onClick={()=>setSelected(layer.id)}>{layer.type==='text'?layer.text||'Text':layer.type==='shape'?(layer.oval?'Oval':'Shape'):layer.type==='draw'?'Drawing':`Image ${project.layers.length-index}`}</button>)}</div>}
    </div></div>
   </>}
   {error&&<TransientError className="error" role="alert">{error}</TransientError>}
  </div>
  <footer className="log-task-footer panel-actions square-footer"><button type="button" onClick={cancel}>Cancel</button><button type="button" className="solid" disabled={busy||loading||placingText||Boolean(cropping)} onClick={()=>void finish()}>{busy&&<CircleNotch className="spin" size={18}/>}Add to Log entry</button></footer>
 </section>;
}

function SquareCrop({layer,painter,cancel,use}:{layer:SquareLayer;painter:SquarePainter;cancel():void;use(region:NonNullable<SquareLayer['crop']>):void}){
 const [region,setRegion]=useState(layer.crop||{x:0,y:0,w:1,h:1}),[aspect,setAspect]=useState(1),frame=useRef<HTMLDivElement>(null),start=useRef<{point:SquarePoint;region:typeof region;corner:'move'|'ne'|'sw'}|null>(null);
 useEffect(()=>{let alive=true;void painter.image(layer.src!).then(image=>{if(alive)setAspect(image.naturalWidth/image.naturalHeight);});return()=>{alive=false;};},[layer.src]);
 const down=(event:PointerEvent<HTMLDivElement>,corner:'move'|'ne'|'sw')=>{event.preventDefault();event.stopPropagation();const rect=frame.current!.getBoundingClientRect();start.current={point:{x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height},region,corner};event.currentTarget.setPointerCapture(event.pointerId);};
 const move=(event:PointerEvent<HTMLDivElement>)=>{const source=start.current;if(!source)return;const rect=frame.current!.getBoundingClientRect(),dx=(event.clientX-rect.left)/rect.width-source.point.x,dy=(event.clientY-rect.top)/rect.height-source.point.y,r=source.region;if(source.corner==='move')setRegion({...r,x:clamp(r.x+dx,0,1-r.w),y:clamp(r.y+dy,0,1-r.h)});else if(source.corner==='ne'){const right=clamp(r.x+r.w+dx,r.x+.01,1),top=clamp(r.y+dy,0,r.y+r.h-.01);setRegion({x:r.x,y:top,w:right-r.x,h:r.y+r.h-top});}else{const left=clamp(r.x+dx,0,r.x+r.w-.01),bottom=clamp(r.y+r.h+dy,r.y+.01,1);setRegion({x:left,y:r.y,w:r.x+r.w-left,h:bottom-r.y});}};
 return <section className="square-crop" aria-label="Crop layer"><div ref={frame} className="square-crop-frame" style={{aspectRatio:aspect}} onPointerMove={move} onPointerUp={()=>{start.current=null;}} onPointerCancel={()=>{start.current=null;}}><img src={layer.src} alt="Image to crop" draggable={false}/><div className="square-crop-mask" style={{left:`${region.x*100}%`,top:`${region.y*100}%`,width:`${region.w*100}%`,height:`${region.h*100}%`}} onPointerDown={event=>down(event,'move')}><div className="square-crop-handle square-crop-ne" role="button" aria-label="Crop upper right corner" onPointerDown={event=>down(event,'ne')}/><div className="square-crop-handle square-crop-sw" role="button" aria-label="Crop lower left corner" onPointerDown={event=>down(event,'sw')}/></div></div><div className="panel-actions square-crop-actions"><button type="button" onClick={()=>setRegion({x:0,y:0,w:1,h:1})}>Reset crop</button><button type="button" onClick={cancel}>Cancel crop</button><button type="button" onClick={()=>use(region)}>Use crop</button></div></section>;
}
