import {TransientError} from './TransientError';
import {usePanelVisible} from './PanelReadiness';
import {DeleteConfirmation} from './DeleteConfirmation';
import { useCallback, useEffect, useRef, useState } from 'react';
import { File, Trash, CircleNotch } from '@phosphor-icons/react';
import {storageTypes,storageLocations,type StorageLocation,type StorageType,type StoredFile,type LinkedVideoItem,type StoragePage} from '../shared/storage';
import type {Destination} from '../shared/navigation';
import { errorText, operation } from './api';
import { useRecordRefresh } from './useRecordRefresh';

const size = (bytes: number) => bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.ceil(bytes / 1024))} KB`;
function LinkedVideoRow({item,navigate}:{item:LinkedVideoItem;navigate(destination:Destination):void}){
 const post=item.attachments[0];return <li><div className="storage-row">{item.posterUrl?<img src={item.posterUrl} alt=""/>:<File size={32}/>}<div className="storage-file"><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">{item.title}</a><span className="quiet small">Video · {item.bytes?`${size(item.bytes)} stored`:'External link'}</span>{post&&<div className="storage-attachments"><a href={post.url} onClick={event=>{if(event.button===0&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey){event.preventDefault();navigate(post.destination!);}}}>Attached to post</a></div>}</div></div></li>;
}
export function StoragePanel({navigate}:{navigate(destination:Destination):void}) {
  const visible=usePanelVisible();
  const [expanded,setExpanded]=useState<string|null>(null),[attachmentBusy,setAttachmentBusy]=useState<string|null>(null);
  const [attachedTo,setAttachedTo]=useState<StorageLocation>('all'),[type,setType]=useState<StorageType>('all'),[loading,setLoading]=useState(false);
  const [storage, setStorage] = useState<StoragePage | null>(null), [review, setReview] = useState<string | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const generation = useRef(0), keys = useRef(new Map<string, string>());
  const loadedFilter=useRef('');
  const waitingForFiles=!storage||loadedFilter.current!==`${attachedTo}:${type}`;
  const load = useCallback(async (before?: string) => {
    const request = ++generation.current;setLoading(true);
    try { const next = await operation<StoragePage>('storage.list', {type,attachedTo,...(before?{before}:{})}); if (request === generation.current) { loadedFilter.current=`${attachedTo}:${type}`;setStorage(previous => before && previous ? { ...next, items: [...previous.items, ...next.items] } : next); setError(''); } }
    catch (error) { if (request === generation.current) setError(errorText(error)); }
    finally {if(request===generation.current)setLoading(false);}
  }, [type,attachedTo]);
  useEffect(() => { void load(); return () => { generation.current++; }; }, [load]); useRecordRefresh(['storage','posts','log','chat_history'], load);
  useEffect(()=>{if(!visible||!storage?.indexing||loading)return;const timer=setTimeout(()=>void load(),2000);return()=>clearTimeout(timer);},[visible,storage?.indexing,loading,load]);
  const moreAttachments=async(file:StoredFile)=>{
    if(!file.attachmentCursor||attachmentBusy)return;const request=generation.current;setAttachmentBusy(file.id);
    try{const page=await operation<{items:StoredFile['attachments'];nextCursor:string|null}>('storage.attachments',{fileId:file.id,before:file.attachmentCursor,attachedTo});if(request===generation.current)setStorage(previous=>previous&&{...previous,items:previous.items.map(item=>item.id===file.id?{...item,attachments:[...new Map([...item.attachments,...page.items].map(attachment=>[attachment.url,attachment])).values()],attachmentCursor:page.nextCursor}:item)});}
    catch(error){if(request===generation.current)setError(errorText(error));}finally{setAttachmentBusy(null);}
  };
  const remove = async (file: StoredFile) => {
    setBusy(true); if (!keys.current.has(file.id)) keys.current.set(file.id, crypto.randomUUID());
    try { await operation('files.delete', { fileId: file.id }, { key: keys.current.get(file.id), confirmed: true }); setReview(null); await load(); }
    catch (error) { setError(errorText(error)); } finally { setBusy(false); }
  };
  return <><div className="storage-summary"><p className="storage-total">{storage?<><strong>{storage.usedBytes ? size(storage.usedBytes) : '0 MB'}</strong> of {size(storage.limitBytes)}</>:<span className="quiet">Loading storage…</span>}</p><progress className="storage-meter" max={storage?.limitBytes||1} value={storage?.usedBytes} aria-label="Storage used" /></div><div className="storage-filters"><nav className="view-tabs storage-types" aria-label="Attachment locations">{storageLocations.map(value=><button key={value} type="button" disabled={busy} aria-pressed={attachedTo===value} onClick={()=>{if(attachedTo!==value){generation.current++;setAttachedTo(value);setLoading(true);setExpanded(null);setReview(null);setError('');}}}>{({all:'All',hangouts:'Hangouts',profile:'Profile',posts:'Posts',chat:'Chat',websites:'Websites'})[value]}</button>)}</nav><nav className="view-tabs storage-types" aria-label="File types">{storageTypes.map(value=><button key={value} type="button" disabled={busy} aria-pressed={type===value} onClick={()=>{if(type!==value){generation.current++;setType(value);setLoading(true);setExpanded(null);setReview(null);setError('');}}}>{({all:'All',images:'Images',audio:'Audio',video:'Video',documents:'Documents'})[value]}</button>)}</nav></div><div className="storage-results" aria-busy={waitingForFiles&&loading}>{waitingForFiles&&loading&&<div className="storage-loading" role="status" aria-label="Loading files"><CircleNotch size={22} className="spin"/></div>}<div style={waitingForFiles?{visibility:'hidden'}:undefined} inert={waitingForFiles}>{storage && <>
    <ul className="storage-list">{storage.items.map(file => 'kind' in file&&file.kind==='linked_video'?<LinkedVideoRow key={file.id} item={file} navigate={navigate}/>:<li key={file.id}><div className="storage-row">{file.ready && file.mime.startsWith('image/') ? <img src={`/api/files/${encodeURIComponent(file.id)}`} alt="" /> : file.ready&&file.mime.startsWith('video/')?<img src={`/api/files/${encodeURIComponent(file.id)}/poster`} alt=""/>:<File size={32} />}<div className="storage-file">{file.ready ? <a href={`/api/files/${encodeURIComponent(file.id)}`} target="_blank" rel="noopener noreferrer">{file.originalName??file.name}</a> : <span>{file.originalName??file.name}</span>}<span className="quiet small">{size(file.bytes+(file.posterBytes||0))} · {file.inWebsite ? 'Website media' : file.inProfile ? 'Profile photo' : file.attached ? file.purpose==='log_media'?'Log attachment':'Attached file' : 'Unattached'}</span>{(file.attachments?.length>0||file.attachmentCursor)&&<div className="storage-attachments">{(file.attachments.length>1||file.attachmentCursor)&&<button type="button" aria-expanded={expanded===file.id} aria-controls={`storage-places-${file.id}`} onClick={()=>setExpanded(previous=>previous===file.id?null:file.id)}>{file.attachments.length}{file.attachmentCursor?'+':''} attachments</button>}{(file.attachments.length===1&&!file.attachmentCursor||expanded===file.id)&&<div className={file.attachments.length>1?'storage-places':undefined} id={`storage-places-${file.id}`}>{file.attachments.map(attachment=><a key={attachment.url} href={attachment.url} target={attachment.destination?undefined:'_blank'} rel={attachment.destination?undefined:'noopener noreferrer'} onClick={event=>{if(attachment.destination&&event.button===0&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey){event.preventDefault();navigate(attachment.destination);}}}>{attachment.label}</a>)}{file.attachmentCursor&&<button className="text-link small" disabled={attachmentBusy===file.id} onClick={()=>void moreAttachments(file)}>{attachmentBusy===file.id?'Loading...':'More attachments'}</button>}</div>}</div>}</div><button type="button" className="storage-delete" aria-label={`Delete ${file.originalName??file.name}`} disabled={busy} onClick={() => setReview(review === file.id ? null : file.id)}><Trash size={20} /></button></div>
      {review === file.id && <DeleteConfirmation title={`Delete ${file.originalName??file.name}?`} detail={file.inWebsite?'It will be removed from your website draft and any published version, and previous chat links may stop working.':file.inProfile?'It will also be removed from your profile.':file.attached?'It will be removed from any attached posts or Log entries, and previous chat links will stop working.':'This can’t be undone.'} confirmLabel="Delete file" busy={busy} onCancel={()=>setReview(null)} onConfirm={()=>remove(file)}/>}
    </li>)}</ul>{storage.indexing&&<p className="quiet small">Finding attachments...</p>}{!storage.items.length&&!storage.indexing && <p className="quiet">{type==='all'&&attachedTo==='all'?'No stored files.':'No matching files.'}</p>}{storage.nextCursor && <button className="text-link" disabled={loading} onClick={() => void load(storage.nextCursor!)}>{loading?'Loading…':'More files'}</button>}</>}</div></div>{error && <TransientError className="error" role="alert">{error}</TransientError>}</>;
}
