import {TransientError} from './TransientError';
import {avatarImageUrl} from './logImageCache';
import {useContext,useEffect,useLayoutEffect,useRef,useState,type FormEvent,type MouseEvent,type RefObject} from 'react';
import {CaretDown,CaretLeft,CaretRight,CaretUp,Flag,Hand,Info,LinkSimple,Microphone,MicrophoneSlash,PhoneDisconnect,ShareNetwork,Smiley,Waveform,X} from '@phosphor-icons/react';
import {useTalk} from './TalkSession';
import {NavLink,plainLinkClick} from './NavLink';
import {talkReactions,type TalkReactionKey} from '../shared/talkReactions';
import {errorText,operation,uploadReportAudio} from './api';
import {LinkPreviews} from './LinkPreview';
import {PostCard,type Post} from './PostPanels';
import {NavigationContext} from './NavigationContext';
import {useRecordRefresh} from './useRecordRefresh';
import {DeleteConfirmation} from './DeleteConfirmation';
import type {Profile} from '../shared/types';
import './spaces.css';

const avatar=(name:string,photoId?:string,reaction?:string)=><span className="space-avatar">{reaction?<span className="talk-avatar-reaction">{reaction}</span>:photoId?<img src={avatarImageUrl(photoId)} alt=""/>:name.replace(/^@/,'').slice(0,1).toUpperCase()}</span>;
const photo=(metadata?:string)=>{try{const value=JSON.parse(metadata||'{}');return typeof value.photoId==='string'?value.photoId:undefined;}catch{return undefined;}};
function TalkCarouselPost({postId,user}:{postId:string;user?:Profile}){
 const navigate=useContext(NavigationContext),[post,setPost]=useState<Post|null>(null),[error,setError]=useState('');
 const load=()=>operation<Post>('posts.get',{postId},{dedupe:true}).then(value=>{setPost(value);setError('');}).catch(cause=>setError(errorText(cause)));
 useEffect(()=>{setPost(null);void load();},[postId]);useRecordRefresh(['posts'],()=>void load());
 if(!user||!navigate)return <NavLink to={{view:'post',resourceId:postId}}>Open post</NavLink>;
 return post?<div className="posts-list"><div><PostCard post={post} user={user} navigate={navigate} changed={setPost} deleted={()=>void load()} eagerMedia inTalkJumbotron/></div></div>:error?<TransientError className="error" role="alert">{error}</TransientError>:<div className="talk-carousel-loading" aria-busy="true"/>;
}
function TalkElapsedTime({startedAt}:{startedAt:string}){
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const seconds=Math.max(0,Math.floor((now-Date.parse(startedAt))/1000))||0,minutes=Math.floor(seconds/60),hours=Math.floor(minutes/60);
 const clock=hours?`${hours}:${String(minutes%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`:`${minutes}:${String(seconds%60).padStart(2,'0')}`;
 return <time className="talk-live-time" dateTime={startedAt}>Live {clock}</time>;
}
export function TalkDock({anchor,user}:{anchor?:RefObject<HTMLElement|null>;user?:Profile}={}){
 const talk=useTalk(),[infoOpen,setInfoOpen]=useState(false),[selected,setSelected]=useState<{id:string;name:string;speaker:boolean}|null>(null),[reactionOpen,setReactionOpen]=useState(false),[linkOpen,setLinkOpen]=useState(false),[linkDraft,setLinkDraft]=useState(''),[linkError,setLinkError]=useState(''),[reporting,setReporting]=useState(false),[reportReason,setReportReason]=useState(''),[reportBusy,setReportBusy]=useState(false),[reportError,setReportError]=useState(''),[confirmLeaving,setConfirmLeaving]=useState(false);
 const [pinIndex,setPinIndex]=useState(0),previousPins=useRef({spaceId:'',count:0});
 const dock=useRef<HTMLElement>(null);
 const reportIntent=useRef<{key:string;personId:string;spaceId:string;reason:string;audio:Blob|null}|null>(null);
 const pins=talk?.space?.pins||[];
 useEffect(()=>{if(!talk?.expanded)setConfirmLeaving(false);},[talk?.expanded]);
 useEffect(()=>{const before=previousPins.current;if(before.spaceId!==talk?.space?.id||pins.length>before.count)setPinIndex(Math.max(0,pins.length-1));else setPinIndex(value=>Math.min(value,Math.max(0,pins.length-1)));previousPins.current={spaceId:talk?.space?.id||'',count:pins.length};},[talk?.space?.id,pins.length]);
 useLayoutEffect(()=>{
  const node=dock.current,slot=anchor?.current,parent=slot?.parentElement;if(!node||!slot||!parent)return;
  let frame=0;const sync=()=>{frame=0;const expanded=node.hasAttribute('data-expanded'),carousel=node.hasAttribute('data-has-carousel'),mobile=window.matchMedia('(max-width:760px)').matches,fullscreen=expanded&&mobile&&(carousel||window.matchMedia('(max-height:820px)').matches);if(fullscreen){for(const name of ['left','top','width','height'])node.style.removeProperty(name);return;}const rect=slot.getBoundingClientRect();node.style.left=`${rect.left}px`;node.style.width=`${rect.width}px`;if(expanded&&carousel){node.style.removeProperty('top');node.style.removeProperty('height');return;}node.style.top=`${rect.top}px`;node.style.height=`${rect.height}px`;};
  const schedule=()=>{if(!frame)frame=requestAnimationFrame(sync);};
  const resize=new ResizeObserver(schedule),position=new MutationObserver(schedule);resize.observe(slot);resize.observe(parent);position.observe(parent,{attributes:true,attributeFilter:['style','class']});
  window.addEventListener('resize',schedule);window.visualViewport?.addEventListener('resize',schedule);window.visualViewport?.addEventListener('scroll',schedule);sync();
  return()=>{cancelAnimationFrame(frame);resize.disconnect();position.disconnect();window.removeEventListener('resize',schedule);window.visualViewport?.removeEventListener('resize',schedule);window.visualViewport?.removeEventListener('scroll',schedule);};
 },[anchor,talk?.expanded,talk?.space?.pins?.length]);
 if(!talk?.space||!talk.room)return null;
 const {space,members,speaking,requests,mic,audioBlocked,expanded,busy,error,copied}=talk,role=space.myRole||'listener',canSpeak=role==='host'||role==='speaker';
 const participants=members.filter(person=>person.identity),speakers=participants.filter(person=>space.speakerIds.includes(person.identity)),listeners=participants.filter(person=>!space.speakerIds.includes(person.identity));
 const profileIds=new Set(space.profileIds||[]);
 const reactionFor=(id:string)=>{const active=talk.reactions.filter(item=>item.personId===id).at(-1);return active?talkReactions[active.key]:undefined;};
 const microphoneOn=(person:typeof members[number])=>[...person.audioTrackPublications.values()].some(publication=>Boolean(publication.track)&&!publication.isMuted);
 const action=(work:Promise<unknown>)=>void work.catch(()=>{});
 const leave=async()=>{try{await(role==='host'?talk.end():talk.leave());setConfirmLeaving(false);}catch{/* Talk shows the operation error and keeps the confirmation open. */}};
 const openProfile=(event:MouseEvent<HTMLAnchorElement>)=>{if(plainLinkClick(event)){setSelected(null);talk.setExpanded(false);}};
 const profileTo=(id:string)=>({view:'person' as const,resourceId:id});
 const personButton=(person:typeof members[number],speaker:boolean)=>{const name=person.name||'Member';return <button type="button" className="space-person-open" aria-label={`Options for ${name}`} aria-expanded={selected?.id===person.identity} onClick={()=>{setReporting(false);setReportReason('');setReportError('');reportIntent.current=null;setSelected(current=>current?.id===person.identity?null:{id:person.identity,name,speaker});}}>{avatar(name,photo(person.metadata),reactionFor(person.identity))}<strong>{name}</strong></button>;};
 const submitReport=async(event:FormEvent)=>{event.preventDefault();if(!selected||reportBusy||!reportReason.trim())return;const reason=reportReason.trim(),prior=reportIntent.current;
  const intent=prior?.personId===selected.id&&prior.spaceId===space.id&&prior.reason===reason?prior:{key:crypto.randomUUID(),personId:selected.id,spaceId:space.id,reason,audio:talk.recentAudio()};reportIntent.current=intent;
  setReportBusy(true);setReportError('');try{const result=await operation<{id:string}>('people.report',{personId:intent.personId,spaceId:intent.spaceId,reason:intent.reason},{confirmed:true,key:intent.key});if(intent.audio)await uploadReportAudio(result.id,intent.audio);setReporting(false);setSelected(null);setReportReason('');reportIntent.current=null;}catch(cause){setReportError(errorText(cause));}finally{setReportBusy(false);}};
 const personMenu=()=>{if(!selected)return null;const canManage=role==='host'&&selected.id!==space.hostId,card=space.participantCards?.find(person=>person.id===selected.id),name=card?.name||selected.name,handle=card?.handle?`@${card.handle}`:undefined,requested=requests.some(item=>item.personId===selected.id),invited=space.invitedSpeakerIds?.includes(selected.id);return <div className="space-person-menu"><div className="space-person-menu-head"><strong>{name}</strong>{handle&&<small>{handle}</small>}</div><div className="space-person-actions">{profileIds.has(selected.id)?<NavLink to={profileTo(selected.id)} onClick={openProfile}>View profile</NavLink>:<span className="quiet">Profile unavailable</span>}{canManage&&!selected.speaker&&(invited?<button type="button" disabled={busy} onClick={()=>action(talk.cancelSpeakerInvite(selected.id))}>Cancel invite</button>:requested?<button type="button" disabled={busy} onClick={()=>action(talk.respond(selected.id,true))}>Accept request</button>:<button type="button" disabled={busy} onClick={()=>action(talk.inviteSpeaker(selected.id))}>Invite to speak</button>)}{canManage&&selected.speaker&&!space.hostOffer&&<button type="button" disabled={busy} onClick={()=>{action(talk.offerHost(selected.id));setSelected(null);}}>Offer host</button>}{canManage&&selected.speaker&&<button type="button" disabled={busy} onClick={()=>{action(talk.revoke(selected.id));setSelected(null);}}>Remove mic</button>}{canManage&&<button type="button" disabled={busy} onClick={()=>{action(talk.remove(selected.id));setSelected(null);}}>Remove from talk</button>}{selected.id!==talk.room?.localParticipant.identity&&<button type="button" disabled={reportBusy} onClick={()=>setReporting(true)}><Flag size={15}/>Report</button>}<button type="button" onClick={()=>{setReporting(false);setSelected(null);}}>Close</button></div>{reporting&&<form className="fields talk-report-form" onSubmit={event=>void submitReport(event)}><label>What happened?<textarea value={reportReason} maxLength={1000} onChange={event=>setReportReason(event.target.value)}/></label><p className="quiet small">{talk.audioEvidenceAvailable?'Your last minute of Talk audio will be attached.':'Audio is unavailable here; you can still report.'}</p><div className="panel-actions"><button type="button" className="text-action" onClick={()=>setReporting(false)} disabled={reportBusy}>Cancel</button><button className="solid" disabled={reportBusy||!reportReason.trim()}>Submit report</button></div>{reportError&&<TransientError className="error" role="alert">{reportError}</TransientError>}</form>}</div>;};
 const addLink=async(event:FormEvent)=>{event.preventDefault();if(!linkDraft.trim()||busy)return;setLinkError('');try{await talk.pinLink(linkDraft);setLinkDraft('');setLinkOpen(false);}catch(cause){setLinkError(cause instanceof Error?cause.message:'Could not add link.');}};
 const activePin=pins[pinIndex];
 return <section ref={dock} className="talk-dock" data-expanded={expanded||undefined} data-has-carousel={pins.length>0||undefined} aria-label={`Talk space: ${space.title}`}>
  <div className="talk-dock-bar"><button className="talk-dock-title" type="button" aria-expanded={expanded} onClick={()=>talk.setExpanded(!expanded)}><Waveform size={20}/><span><strong>{space.title}</strong>{!expanded&&(space.hostOffer?.toId===talk.room.localParticipant.identity?<small className="talk-host-notice">Host offer · Open to respond</small>:<small className="talk-compact-presence"><span className="talk-presence-group" role="img" aria-label={`${speakers.length} speaking`} title="Speakers"><span className="talk-compact-avatars">{speakers.slice(0,3).map(person=><span key={person.identity} title={person.name||'Speaker'}>{avatar(person.name||'Member',photo(person.metadata),reactionFor(person.identity))}</span>)}</span></span>{listeners.length>0&&<span className="talk-presence-group" role="img" aria-label={`${listeners.length} listening`} title="Listeners"><span className="talk-compact-avatars">{listeners.slice(0,3).map(person=><span key={person.identity} title={person.name||'Listener'}>{avatar(person.name||'Member',photo(person.metadata),reactionFor(person.identity))}</span>)}</span></span>}</small>)}</span></button>
   {audioBlocked&&<button type="button" className="talk-dock-audio" onClick={()=>action(talk.startAudio())}>Hear audio</button>}
   <button type="button" className="talk-dock-icon talk-hangup" aria-label={role==='host'?'End talk space':'Leave talk space'} disabled={busy} onClick={()=>{setConfirmLeaving(true);talk.setExpanded(true);}}><PhoneDisconnect size={21}/></button>
   {canSpeak?<button type="button" className="talk-dock-icon talk-mic" data-mic-active={mic||undefined} aria-label={mic?'Mic on. Mute microphone':'Mic off. Unmute microphone'} disabled={busy} onClick={()=>action(talk.toggleMic())}>{mic?<Microphone size={21}/>:<MicrophoneSlash size={21}/>}</button>:<button type="button" className="talk-dock-icon" aria-label={space.myRequest==='pending'?'Cancel speaking request':'Request to speak'} aria-pressed={space.myRequest==='pending'} disabled={busy} onClick={()=>action(talk.request())}><Hand size={21} weight={space.myRequest==='pending'?'fill':'regular'}/></button>}
   <button type="button" className="talk-dock-icon" aria-label={expanded?'Collapse talk space':'Expand talk space'} aria-expanded={expanded} onClick={()=>talk.setExpanded(!expanded)}>{expanded?<CaretDown size={21}/>:<CaretUp size={21}/>}</button>
  </div>
  {expanded&&<div className="talk-dock-body">{confirmLeaving&&<DeleteConfirmation title={role==='host'?'End this talk space?':'Leave this talk space?'} detail={role==='host'?'Everyone will be disconnected.':undefined} confirmLabel={role==='host'?'End talk space':'Leave talk space'} pendingLabel={role==='host'?'Ending…':'Leaving…'} busy={busy} onCancel={()=>setConfirmLeaving(false)} onConfirm={leave}/>} {space.hostOffer&&<div className="talk-host-offer"><span>{role==='host'?`Host offer sent to ${members.find(person=>person.identity===space.hostOffer?.toId)?.name||space.speakers.find(person=>person.id===space.hostOffer?.toId)?.name||'speaker'}`:'Become host?'}</span>{role==='host'?<button type="button" disabled={busy} onClick={()=>action(talk.cancelHostOffer())}>Cancel offer</button>:<><button type="button" disabled={busy} onClick={()=>action(talk.acceptHost())}>Accept</button><button type="button" disabled={busy} onClick={()=>action(talk.declineHost())}>Decline</button></>}</div>}{space.mySpeakerInvite&&<div className="talk-host-offer"><span>Speak in this Talk?</span><button type="button" disabled={busy} onClick={()=>action(talk.respondSpeakerInvite(true))}>Accept</button><button type="button" disabled={busy} onClick={()=>action(talk.respondSpeakerInvite(false))}>Decline</button></div>}{space.description&&<div className="talk-dock-heading"><button type="button" aria-label="Talk space description" aria-expanded={infoOpen} onClick={()=>setInfoOpen(value=>!value)}><Info size={21}/></button></div>}
    {infoOpen&&space.description&&<div className="talk-info-panel"><p>{space.description}</p></div>}
    {activePin&&<section className="talk-pin-carousel" aria-label="Links in this Talk"><div className="talk-carousel-content" key={activePin.id}>{activePin.kind==='post'?<TalkCarouselPost postId={activePin.postId!} user={user}/>:<LinkPreviews text="" links={[activePin.url]} eager/>}</div><div className="talk-carousel-nav"><span className="talk-carousel-by">Shared by {activePin.addedByName||'a speaker'}</span>{(activePin.addedBy===talk.room?.localParticipant.identity||role==='host')&&<button type="button" className="talk-pin-remove" aria-label="Remove link from Talk" disabled={busy} onClick={()=>action(talk.unpin(activePin.id))}><X size={18}/></button>}<button type="button" aria-label="Previous Talk link" disabled={pinIndex===0} onClick={()=>setPinIndex(value=>value-1)}><CaretLeft size={20}/></button><span>{pinIndex+1} / {pins.length}</span><button type="button" aria-label="Next Talk link" disabled={pinIndex===pins.length-1} onClick={()=>setPinIndex(value=>value+1)}><CaretRight size={20}/></button></div></section>}
    <div className="talk-dock-people"><h3>Speakers</h3><div className="space-avatar-grid">{speakers.map(person=>{const live=microphoneOn(person);return <div className={`space-person ${speaking.has(person.identity)?'speaking':''}`} key={person.identity}>{personButton(person,true)}{!live&&<span className="talk-person-mic" role="img" aria-label={`${person.name||'Speaker'} muted`} title="Muted"><MicrophoneSlash size={13}/></span>}<small>{person.identity===space.hostId?'Host':'Speaker'}</small></div>;})}</div>{selected?.speaker&&personMenu()}
     {role==='host'&&requests.length>0&&<div className="space-requests"><h3>Requests to speak</h3>{requests.map(item=><div key={item.personId}><span>{item.name}</span><button type="button" disabled={busy} onClick={()=>action(talk.respond(item.personId,true))}>Accept</button><button type="button" disabled={busy} onClick={()=>action(talk.respond(item.personId,false))}>Decline</button></div>)}</div>}
     <h3>Listeners</h3><div className="space-avatar-grid">{listeners.length?listeners.map(person=><div className="space-person" key={person.identity}>{personButton(person,false)}</div>):<p>No listeners yet.</p>}</div>{selected&&!selected.speaker&&personMenu()}
    </div>{error&&<TransientError className="error" role="alert">{error}</TransientError>}
    {linkOpen&&canSpeak&&<form className="fields talk-pin-form" onSubmit={event=>void addLink(event)}><label>Link<input type="text" inputMode="url" autoCapitalize="none" autoComplete="off" spellCheck={false} value={linkDraft} onChange={event=>setLinkDraft(event.target.value)} placeholder="example.com" autoFocus/></label><div className="panel-actions"><button type="button" className="text-action" onClick={()=>setLinkOpen(false)}>Cancel</button><button className="solid" disabled={busy||!linkDraft.trim()}>Add link</button></div>{linkError&&<TransientError className="error" role="alert">{linkError}</TransientError>}</form>}
    {reactionOpen&&<div className="talk-reaction-picker" aria-label="React to Talk">{(Object.entries(talkReactions) as [TalkReactionKey,string][]).map(([key,emoji])=><button type="button" key={key} aria-label={`React ${key}`} onClick={()=>{action(talk.react(key));setReactionOpen(false);}}>{emoji}</button>)}</div>}
    <footer className="talk-dock-footer">{copied?<span className="quiet small">Link copied</span>:<TalkElapsedTime startedAt={space.createdAt}/>}{canSpeak&&<button type="button" aria-label="Add link to Talk" aria-expanded={linkOpen} onClick={()=>{setLinkOpen(value=>!value);setReactionOpen(false);}}><LinkSimple size={21}/></button>}<button type="button" aria-label="React to Talk" aria-expanded={reactionOpen} onClick={()=>{setReactionOpen(value=>!value);setLinkOpen(false);}}><Smiley size={21}/></button><button type="button" aria-label="Share talk space" onClick={()=>action(talk.share())}><ShareNetwork size={21}/></button></footer>
   </div>}
 </section>;
}
