import {useLayoutEffect,useState,type RefObject} from 'react';
/** Only the main panel rises. Side navigation/information retains its original inset. */
export function useTopControlClearance(panel:RefObject<HTMLElement|null>,active:boolean,layoutKey:string){
 const [offset,setOffset]=useState(0);
 useLayoutEffect(()=>{if(!active||!panel.current)return;let frame=0;const controls=[...document.querySelectorAll<HTMLElement>('.mode-switch:not(.mode-switch-measure), .settings-controls')];
  const fit=()=>{if(!panel.current)return;const rect=panel.current.getBoundingClientRect();const css=getComputedStyle(panel.current),gap=parseFloat(css.getPropertyValue('--top-control-gap'))||12,base=parseFloat(css.getPropertyValue('--mode-top'))||12;const top=(window.visualViewport?.offsetTop||0)+base;let edge=top;for(const control of controls){const style=getComputedStyle(control);if(style.visibility==='hidden'||style.display==='none')continue;const box=control.getBoundingClientRect();if(box.width&&box.height&&rect.left<box.right&&rect.right>box.left)edge=Math.max(edge,box.bottom+gap);}setOffset(Math.max(0,edge-top));};
  const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(fit);};fit();const resize=new ResizeObserver(schedule);resize.observe(panel.current);controls.forEach(control=>resize.observe(control));const mutations=new MutationObserver(schedule);controls.forEach(control=>mutations.observe(control,{attributes:true,attributeFilter:['style','class','data-collapsed']}));window.addEventListener('resize',schedule);window.visualViewport?.addEventListener('resize',schedule);document.addEventListener('focusin',schedule);document.addEventListener('focusout',schedule);return()=>{cancelAnimationFrame(frame);resize.disconnect();mutations.disconnect();window.removeEventListener('resize',schedule);window.visualViewport?.removeEventListener('resize',schedule);document.removeEventListener('focusin',schedule);document.removeEventListener('focusout',schedule);};
 },[panel,active,layoutKey]);return offset;
}
